// Auto-generated harness for: strncat
// Source: src/c2goto/library/string.c:99
// Generated by Byte Repair Contractor

#include <stddef.h>

extern char *strncat(char *dst, const char *src, size_t n);

void __byterepair_harness_main(void) {
    // --- Symbolic inputs ---
    char dbuf[16], sbuf[8];
    dbuf[0] = '\0';
    sbuf[7] = '\0';
    char *dst = dbuf;
    const char *src = (const char *)sbuf;
    size_t n = nondet_uint();
    __ESBMC_assume(n <= 8);

    // --- Call under test ---
    char *result = strncat(dst, src, n);

    // --- Postcondition assertions ---
    __ESBMC_assert(result == dst, "system property: strncat returns dst");
}
