/**
 * ============================================================================
 * Name        : digitalfilter.h
 * Author      : Renato Abreu
 * Version     : 0.3
 * Copyright   : Copyright by Renato Abreu
 * Description : BMC verification of digital filters
 * ============================================================================
 */

#ifndef _DIGITALFILTER_H
#define _DIGITALFILTER_H	1

#ifdef __cplusplus

extern "C" { 

#endif

#define CLOCK		16000000
#define CYCLE		1/CLOCK
#define OVERHEAD	80				//Initialized considering overhead (time for data conditioning, DAC, ADC, etc...)
#define SAMPLERATE 	48000
#define DEADLINE 	1/SAMPLERATE

#define WRAP		0
#define NOWRAP		1
#define SATURATE	2

#if 1
  /* functions */
  float shiftL(float zIn, float z[], int N);
  int order(int Na, int Nb);
  float powInt(int x, int y);
  int roundInt(float number);
  int ceilInt(float number);
  int floorInt(float number);
  float maxFixed(int k, int l);
  float minFixed(int k, int l);
  int wrap(int kX, int kLowerBound, int kUpperBound);
  float wrapF(float fX, float fLowerBound, float fUpperBound);
  float floatToFix(float number, float delta, float minFix, float maxFix, int mode);
  float fixedDelta(int l);

  /* Timing data got using WCET analysis of assembly code generated by MSP430 CCS compiler */
  float iirOutTime(float y[], float x[], float a[], float b[], int Na, int Nb);
  float iirOutFixed(float y[], float x[], float a[], float b[], int Na, int Nb, float delta, float minFix, float maxFix, int mode);
  float iirIIOutFixed(float w[], float x, float a[], float b[], int Na, int Nb, float delta, float minFix, float maxFix, int mode);
  float iirIItOutFixed(float w[], float x, float a[], float b[], int Na, int Nb, float delta, float minFix, float maxFix, int mode);
  int nondet_int();
  float nondet_float();

  /* overflow checking */
  int overflow(float *a, float *b, int k, int l, int Na, int Nb, float max, float min, int xsize);

    /* limit cycle checking */
    int limitCycle(float *a, float *b, int k, int l, int Na, int Nb, float max, float min, int xsize);

  /* timing verification */
  int timing(float *a, float *b, int k, int l, int Na, int Nb, float max, float min, int xsize);
#endif

#ifdef __cplusplus

}

#endif

#endif	/* digitalfilter.h */
