// Auto-generated harness for: strpbrk
// Source: src/c2goto/library/string.c:305
// Generated by Byte Repair Contractor

#include <stddef.h>

extern char *strpbrk(const char *s, const char *accept);

void __byterepair_harness_main(void) {
    // --- Symbolic inputs ---
    char a[8], b[8];
    a[7] = '\0';
    b[7] = '\0';
    const char *s = (const char *)a;
    const char *accept = (const char *)b;

    // --- Call under test ---
    char *result = strpbrk(s, accept);

    // --- Postcondition assertions ---
    __ESBMC_assert(result == ((char *)0) || result >= s,
        "system property: strpbrk returns NULL or ptr into s");
}
