// Auto-generated harness for: isxdigit
// Source: src/c2goto/library/ctype.c:123
// Generated by Byte Repair Contractor

extern int isxdigit(int c);

void __byterepair_harness_main(void) {
    // --- Symbolic inputs ---
    int c = nondet_int();

    // --- Precondition assumptions ---
    __ESBMC_assume((c >= -1) && (c <= 255));

    // --- Call under test ---
    int result = isxdigit(c);

    // --- Postcondition assertions ---
    __ESBMC_assert((result != 0) == ((c >= '0' && c <= '9') || (c >= 'A' && c <= 'F') || (c >= 'a' && c <= 'f')), "system property");
    // __ESBMC_assert(/* mirror __ESBMC_ensures conditions */, "description");
}
