# Module to find and configure Csmith

if(ENABLE_CSMITH)
    find_package(CSMITH csmith REQUIRED)

    # Creates a csmith target
    # - csmith_args: args to be passed to csmith
    # - esbmc_args: args to be passed to esbmc
    # - c_file_name: unique name for the C generated by csmith
    # - destiny: where the wrapper will be saved
    function(create_csmith_wrapper csmith_args esbmc_args c_file_name destiny)
        assert_variable_is_defined(${ESBMC_BIN})
        set(CSMITH_CMD "#!/bin/sh\nwhile true; do ${CSMITH} ${csmith_args} > ${c_file_name}; ${ESBMC_BIN} ${esbmc_args} ${c_file_name}; if [[ \"$?\" > 1 ]]; then break; fi; done")
        file(WRITE ${destiny} ${CSMITH_CMD})
    endfunction()

    # For default args
    set(CSMITH_DEFAULT "")
    # k-induction

    # incremental
endif()