/* Generated by scripts/rv2c.py from cxl_bind.gen.h -- do not edit.
 *
 * Linux RV monitor 'cxl_bind', as an ESBMC-checkable specification.
 * The obligation is the one in include/rv/da_monitor.h: an event that
 * has no transition from the current state drives the automaton to
 * INVALID_STATE, and the monitor reacts. Here that is an assertion.
 *
 * This file is the SPECIFICATION. Supply an implementation that calls
 * rv_cxl_bind_event() and prove it never trips the assertion; driving
 * it with unconstrained events reaches INVALID_STATE at once and
 * establishes nothing.
 */
#ifndef RV_SPEC_CXL_BIND_H
#define RV_SPEC_CXL_BIND_H

#include <assert.h>

enum rv_cxl_bind_state { unbound, bind_initiated, bound, host_enumerated, host_recognized, RV_CXL_BIND_INVALID };
enum rv_cxl_bind_event { fm_bind, fm_confirm, fm_unbind, host_enumerate, host_recognize };

#define RV_CXL_BIND_STATES 5
#define RV_CXL_BIND_EVENTS 5

static const unsigned char rv_cxl_bind_function[5][5] = {
  /* unbound                      */ { bind_initiated, RV_CXL_BIND_INVALID, RV_CXL_BIND_INVALID, RV_CXL_BIND_INVALID, RV_CXL_BIND_INVALID },
  /* bind_initiated               */ { RV_CXL_BIND_INVALID, RV_CXL_BIND_INVALID, RV_CXL_BIND_INVALID, RV_CXL_BIND_INVALID, host_recognized },
  /* bound                        */ { RV_CXL_BIND_INVALID, RV_CXL_BIND_INVALID, unbound, RV_CXL_BIND_INVALID, RV_CXL_BIND_INVALID },
  /* host_enumerated              */ { RV_CXL_BIND_INVALID, bound, RV_CXL_BIND_INVALID, RV_CXL_BIND_INVALID, RV_CXL_BIND_INVALID },
  /* host_recognized              */ { RV_CXL_BIND_INVALID, RV_CXL_BIND_INVALID, RV_CXL_BIND_INVALID, host_enumerated, RV_CXL_BIND_INVALID },
};

static enum rv_cxl_bind_state rv_cxl_bind_cur = unbound;

static void rv_cxl_bind_reset(void) { rv_cxl_bind_cur = unbound; }

/* Feed one event. Trips the RV obligation if the automaton rejects it. */
static void rv_cxl_bind_event(enum rv_cxl_bind_event ev)
{
  assert(rv_cxl_bind_cur < RV_CXL_BIND_STATES);
  assert((unsigned)ev < RV_CXL_BIND_EVENTS);
  enum rv_cxl_bind_state next =
    (enum rv_cxl_bind_state)rv_cxl_bind_function[rv_cxl_bind_cur][ev];
  /* include/rv/da_monitor.h:690 -- the monitor's whole obligation. */
  assert(next != RV_CXL_BIND_INVALID);
  rv_cxl_bind_cur = next;
}

#endif