# Auto-generated by ESBMC 7.11.0
# Original file: test.py
# Generated: 2026-Jan-14 02:13:50.932850

from test import *
import pytest

@pytest.mark.parametrize("arg0,arg1", [
    (" i", "mem"),
    (":i", "member"),
    ("\x1ei", 0),
    ("vip", 0),
])
def test_add_positive(arg0,arg1):
    """Auto-generated test cases for add_positive"""
    add_positive(arg0,arg1)

