#include <clang-c-frontend/clang_c_language.h>
#include <ac_config.h>
#include <util/filesystem.h>

#ifdef ESBMC_CLANG_HEADERS_BUNDLED
extern "C"
{
#  include <headers/cheaders.h> /* generated by build system */
#  undef ESBMC_FLAIL
}

/* Digests of the bundled headers, emitted next to the arrays by
 * scripts/flail.py, so this key tracks any edit to any of them. */
static std::string bundled_headers_key()
{
  std::string key;
#  define ESBMC_FLAIL(body, size, hash, ...) key += hash;
#  include <headers/cheaders.h>
#  undef ESBMC_FLAIL
  return key;
}
#endif

const std::string &clang_c_languaget::clang_resource_dir()
{
#ifdef ESBMC_CLANG_HEADERS_BUNDLED
  /* Clang appends /include to the resource dir, hence the layout below. */
  static const auto dir = file_operations::cached_extract_dir(
    "clang-headers", bundled_headers_key(), [](const std::string &root) {
      const std::string path = root + "/include";
#  define ESBMC_FLAIL(body, size, hash, ...)                                   \
    file_operations::create_path_and_write(path + "/" #__VA_ARGS__, body, size);
#  include <headers/cheaders.h>
#  undef ESBMC_FLAIL
    });
  return dir.path();
#else
  // clang headers not bundled, return the path set at compile time
  static const std::string path = ESBMC_CLANG_HEADER_DIR "/..";
  return path;
#endif
}
