// Auto-generated harness for: memchr
// Source: src/c2goto/library/string.c:400
// Generated by Byte Repair Contractor

#include <stddef.h>

extern void *memchr(const void *buf, int ch, size_t n);

void __byterepair_harness_main(void) {
    // --- Symbolic inputs ---
    size_t n = nondet_uint();
    __ESBMC_assume(n <= 8);
    unsigned char buf_arr[8];
    const void *buf = (const void *)buf_arr;
    int ch = nondet_int();

    // --- Precondition assumptions ---

    // --- Call under test ---
    void *result = memchr(buf, ch, n);

    // --- Postcondition assertions ---
    // System property: result == NULL iff no byte in [0, n) equals (uchar)ch.
    int found = 0;
    __ESBMC_unroll(9);
    for (size_t k = 0; k < n; k++) {
        if (((const unsigned char *)buf)[k] == (unsigned char)ch) {
            found = 1;
            break;
        }
    }
    __ESBMC_assert((result == ((void *)0)) == (found == 0),
        "system property: memchr returns NULL iff ch not in [buf, buf+n)");
}
