// Auto-generated by ESBMC 8.1.0
//
// This header declares the __VERIFIER_* functions used by the
// SV-COMP / ESBMC verification interface.  It is force-included
// by the generated CMakeLists.txt (via -include) so that the
// original source file compiles correctly even if it does not
// declare these functions itself.
//
// You may also add  #include "esbmc_verifier.h"  to your own
// source file; duplicate declarations are harmless in C and C++.
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

/* Nondeterministic value functions */
char __VERIFIER_nondet_char(void);
short __VERIFIER_nondet_short(void);
int __VERIFIER_nondet_int(void);
long long __VERIFIER_nondet_long(void);
unsigned char __VERIFIER_nondet_uchar(void);
unsigned short __VERIFIER_nondet_ushort(void);
unsigned int __VERIFIER_nondet_uint(void);
unsigned long long __VERIFIER_nondet_ulong(void);
float __VERIFIER_nondet_float(void);
double __VERIFIER_nondet_double(void);
/* In C++ 'bool' is a built-in type; in C use _Bool (native C99
   type, always available without any #include). */
#ifdef __cplusplus
bool __VERIFIER_nondet_bool(void);
#else
_Bool __VERIFIER_nondet_bool(void);
#endif
void *__VERIFIER_nondet_pointer(void);

/* Assumption function */
void __VERIFIER_assume(int cond);

#ifdef __cplusplus
} /* extern "C" */
#endif
