// Auto-generated by ESBMC 8.1.0
// Test case 2 of 4
// This file provides concrete implementations of __VERIFIER_nondet_* functions

void __VERIFIER_assume(int cond) { (void)cond; }

int __VERIFIER_nondet_int(void) {
  static int i = 0;
  static const int v[] = { -2147483633, -2147483648 };
  return v[i++];
}

