// Auto-generated by ESBMC 7.11.0
// Test case 4 of 6
// This file provides concrete implementations of __VERIFIER_nondet_* functions

int __VERIFIER_nondet_int(void) {
  static int i = 0;
  static const int v[] = { 1, 0 };
  return v[i++];
}

