// Auto-generated harness for: strcat
// Source: src/c2goto/library/string.c:85
// Generated by Byte Repair Contractor

#include <stddef.h>

extern char *strcat(char *dst, const char *src);

void __byterepair_harness_main(void) {
    // --- Symbolic inputs ---
    char dbuf[16], sbuf[8];
    dbuf[0] = '\0';
    sbuf[7] = '\0';
    char *dst = dbuf;
    const char *src = (const char *)sbuf;

    // --- Call under test ---
    char *result = strcat(dst, src);

    // --- Postcondition assertions ---
    __ESBMC_assert(result == dst, "system property: strcat returns dst");
}
