# Auto-generated by ESBMC 8.4.0
# Original file: main.py
# Generated: 2026-Aug-14 17:19:40.274305

from main import *
import pytest

@pytest.mark.parametrize("n", [
    9223372036854775807,
    -1,
    100,
    0,
    -101,
])
def test_classify_number(n):
    """Auto-generated test cases for classify_number"""
    classify_number(n)

