// Auto-generated harness for: isalnum
// Source: src/c2goto/library/ctype.c:19
// Generated by Byte Repair Contractor

extern int isalnum(int c);

void __byterepair_harness_main(void) {
    // --- Symbolic inputs ---
    int c = nondet_int();

    // --- Precondition assumptions ---
    __ESBMC_assume((c >= -1) && (c <= 255));

    // --- Call under test ---
    int result = isalnum(c);

    // --- Postcondition assertions ---
    __ESBMC_assert((result != 0) == ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9')), "system property");
    // __ESBMC_assert(/* mirror __ESBMC_ensures conditions */, "description");
}
