// Auto-generated harness for: memcpy
// Source: src/c2goto/library/string.c:287
// Generated by Byte Repair Contractor

#include <stddef.h>

extern void *memcpy(void *dst, const void *src, size_t n);

void __byterepair_harness_main(void) {
    // --- Symbolic inputs ---
    size_t n = nondet_uint();
    __ESBMC_assume(n <= 8);
    unsigned char dst_buf[8];
    unsigned char src_buf[8];
    void *dst = (void *)dst_buf;
    const void *src = (const void *)src_buf;

    // --- Precondition assumptions ---
    // Two disjoint stack buffers satisfy no-overlap implicitly. The contract's
    // non-null requires holds for stack-array addresses.

    // --- Call under test ---
    void *result = memcpy(dst, src, n);

    // --- Postcondition assertions ---
    __ESBMC_assert(result == dst, "system property: memcpy returns dst");

    size_t i;
    __ESBMC_assert(
        __ESBMC_forall(&i,
            !(i < n) || ((unsigned char *)dst)[i]
                        == ((const unsigned char *)src)[i]),
        "system property: memcpy copies every byte of [src, src+n) to [dst, dst+n)");
}
