/* Generated by scripts/rv2c.py from cxl_region.gen.h -- do not edit.
 *
 * Linux RV monitor 'cxl_region', as an ESBMC-checkable specification.
 * The obligation is the one in include/rv/da_monitor.h: an event that
 * has no transition from the current state drives the automaton to
 * INVALID_STATE, and the monitor reacts. Here that is an assertion.
 *
 * This file is the SPECIFICATION. Supply an implementation that calls
 * rv_cxl_region_event() and prove it never trips the assertion; driving
 * it with unconstrained events reaches INVALID_STATE at once and
 * establishes nothing.
 */
#ifndef RV_SPEC_CXL_REGION_H
#define RV_SPEC_CXL_REGION_H

#include <assert.h>

enum rv_cxl_region_state { cfg_idle, cfg_active, cfg_commit, cfg_interleave_active, RV_CXL_REGION_INVALID };
enum rv_cxl_region_event { add_target, commit, reset, set_size };

#define RV_CXL_REGION_STATES 4
#define RV_CXL_REGION_EVENTS 4

static const unsigned char rv_cxl_region_function[4][4] = {
  /* cfg_idle                     */ { RV_CXL_REGION_INVALID, RV_CXL_REGION_INVALID, RV_CXL_REGION_INVALID, cfg_interleave_active },
  /* cfg_active                   */ { cfg_active, cfg_commit, RV_CXL_REGION_INVALID, RV_CXL_REGION_INVALID },
  /* cfg_commit                   */ { RV_CXL_REGION_INVALID, RV_CXL_REGION_INVALID, cfg_idle, RV_CXL_REGION_INVALID },
  /* cfg_interleave_active        */ { cfg_active, RV_CXL_REGION_INVALID, RV_CXL_REGION_INVALID, RV_CXL_REGION_INVALID },
};

static enum rv_cxl_region_state rv_cxl_region_cur = cfg_idle;

static void rv_cxl_region_reset(void) { rv_cxl_region_cur = cfg_idle; }

/* Feed one event. Trips the RV obligation if the automaton rejects it. */
static void rv_cxl_region_event(enum rv_cxl_region_event ev)
{
  assert(rv_cxl_region_cur < RV_CXL_REGION_STATES);
  assert((unsigned)ev < RV_CXL_REGION_EVENTS);
  enum rv_cxl_region_state next =
    (enum rv_cxl_region_state)rv_cxl_region_function[rv_cxl_region_cur][ev];
  /* The monitor's whole obligation, from include/rv/da_monitor.h:
   * an event with no transition drives the automaton to INVALID_STATE
   * and the monitor reacts. No line number is cited -- the check moved
   * between 6.15 and 7.1.5, and is written with the sense inverted in
   * the older one. */
  assert(next != RV_CXL_REGION_INVALID);
  rv_cxl_region_cur = next;
}

#endif