# Auto-generated by ESBMC 8.0.0
# Original file: test.py
# Generated: 2026-Jan-29 04:53:53.070233

from test import *
import pytest

@pytest.mark.parametrize("dict0,list0", [
    ({0: 0}, [0]),
    ({0: 0}, [0]),
    ({0: 0}, [0]),
    ({0: 0}, [0, 0]),
    ({0: 0}, [0]),
])
def test_sum_of_positive_elements(dict0,list0):
    """Auto-generated test cases for sum_of_positive_elements"""
    sum_of_positive_elements(dict0,list0)

