# Auto-generated by ESBMC 8.4.0
# Original file: main.py
# Generated: 2026-Aug-14 17:20:07.249733

from main import *
import pytest

@pytest.mark.parametrize("__nd_size_0&0#1", [
    1,
    0,
    2,
])
def test_sum_of_positive_elements(__nd_size_0&0#1):
    """Auto-generated test cases for sum_of_positive_elements"""
    sum_of_positive_elements(__nd_size_0&0#1)

