#!/usr/bin/env python3
"""
P4a Conformance Testing — Step 3: GOTO-IR Concrete Executor
SAFE-LD: Formal Verification of IEC 61131-3 Ladder Diagram Programs
University of Manchester — Systems & Software Security Group

Extracts the scan_loop from each benchmark's GOTO IR via
--goto-functions-only, then re-executes it with concrete input
values from the input sequences generated by gen_inputs.py.

Key implementation notes:
  1. Parallel rungs (multiple ASSIGN to same var) use OR semantics
  2. Leading coil-energise prefix '1 &&' stripped only at start of expression
  3. Persistent state (timers, latches) maintained across scans within a sequence
  4. Two benchmarks skipped: water_control, stairs_light (graphical tc6_0201)

Usage:
    python3 concrete_executor.py \\
        --inputs  conformance/inputs/ \\
        --output  conformance/esbmc_goto_outputs/ \\
        --esbmc   ./build/src/esbmc/esbmc
"""

import json
import subprocess
import re
import argparse
from pathlib import Path

# ── Benchmark registry ────────────────────────────────────────────────────────
LD_FILES = {
    "traffic_light_safe":  "benchmarks/traffic_light/traffic_light_safe.ld",
    "bottle_filling_safe": "benchmarks/bottle_filling/bottle_filling_safe.ld",
    "elevator_safe":       "benchmarks/elevator/elevator_safe.ld",
    "tank_level_safe":     "benchmarks/tank_level_control/tank_level_control.ld",
}

PROPS_FILES = {
    "traffic_light_safe":  "benchmarks/traffic_light/props.yaml",
    "bottle_filling_safe": "benchmarks/bottle_filling/props.yaml",
    "elevator_safe":       "benchmarks/elevator/props.yaml",
    "tank_level_safe":     "benchmarks/tank_level_control/props.yaml",
}

SKIPPED = {
    "water_control": "graphical tc6_0201 format — rung logic not yet converted",
    "stairs_light":  "graphical tc6_0201 format — rung logic not yet converted",
}

# ── GOTO IR extraction ────────────────────────────────────────────────────────

def get_goto_ir(esbmc_bin: str, ld_file: str, props_file: str) -> str:
    """Extract the GOTO IR text using --goto-functions-only."""
    r = subprocess.run(
        [esbmc_bin, ld_file, "--ld-props", props_file, "--goto-functions-only"],
        capture_output=True, text=True, check=False
    )
    return r.stdout + r.stderr

def parse_scan_loop(ir_text: str):
    """
    Parse the scan_loop function from the GOTO IR.

    Returns:
        nondet_vars: list of input variable names (re-sampled each scan)
        assignments: list of (dest, expr) tuples in execution order

    The GOTO IR scan_loop structure is:
        1: IF !1 THEN GOTO N          ← loop header (always-true loop)
           ASSIGN input1 = NONDET()   ← input re-sampling
           ASSIGN output = expr;      ← rung logic
           ASSERT property            ← safety checks (ignored here)
           GOTO 1                     ← loop back
        N: END_FUNCTION
    """
    in_scan = False
    assignments = []
    nondet_vars = []

    for line in ir_text.split('\n'):
        # Strip leading label numbers (e.g., "  1: ASSIGN ...")
        line = re.sub(r'^\s*\d+:\s*', '', line.strip())
        if not line:
            continue

        # Detect scan_loop function start
        if 'scan_loop' in line and 'ld::scan_loop' in line:
            in_scan = True
            continue
        if not in_scan:
            continue
        if 'END_FUNCTION' in line:
            break

        # NONDET input re-sampling
        m = re.match(r'ASSIGN\s+(\w+)=NONDET\(', line)
        if m:
            nondet_vars.append(m.group(1))
            continue

        # Rung assignments (skip ASSERT, IF, GOTO lines)
        m = re.match(r'ASSIGN\s+(\w+)=(.+);', line)
        if m:
            assignments.append((m.group(1), m.group(2).strip()))

    return nondet_vars, assignments

# ── Expression evaluator ──────────────────────────────────────────────────────

def eval_expr(expr: str, state: dict) -> int:
    """
    Evaluate a GOTO IR boolean expression given the current state.

    Handles:
    - Variable substitution (longest-name-first to avoid partial matches)
    - Boolean operators: &&, ||, !
    - Arithmetic: >=, +
    - Coil-energise prefix: '1 &&' at start of expression only

    Critical fix: the leading '1 &&' prefix (coil energise) must be stripped
    only at the START of the expression. Stripping all occurrences of '1 and'
    would incorrectly remove logical conjuncts involving the literal 1.
    """
    # Substitute variable names with their current integer values
    # Sort by length descending to avoid partial name substitution
    for var in sorted(state.keys(), key=len, reverse=True):
        expr = re.sub(rf'\b{re.escape(var)}\b', str(int(bool(state[var]))), expr)

    # Convert GOTO IR operators to Python operators
    expr = expr.replace('&&', ' and ').replace('||', ' or ')
    expr = re.sub(r'!(\w)', r'not \1', expr)
    expr = re.sub(r'!\(', r'not (', expr)

    # Strip leading coil-energise prefix '1 and' (ONLY at start)
    expr = re.sub(r'^\s*1\s+and\s+', '', expr)

    try:
        # Sandboxed evaluation of a boolean expression with no builtins.
        return int(bool(eval(expr, {"__builtins__": {}}, {})))  # pylint: disable=eval-used
    except Exception:
        return 0

# ── Scan cycle executor ───────────────────────────────────────────────────────

def execute_scan(nondet_vars: list, assignments: list,
                 inputs: dict, persistent: dict) -> dict:
    """
    Execute one scan cycle with concrete inputs.

    IEC 61131-3 scan semantics:
    1. All inputs are sampled at the start of the scan
    2. Rungs are evaluated left-to-right, top-to-bottom
    3. Multiple rungs driving the same coil = OR (parallel rungs)
    4. Persistent state (timers, latches) carries across scans

    Args:
        nondet_vars: input variables to inject from `inputs`
        assignments: ordered list of (dest, expr) from GOTO IR
        inputs:      concrete input values for this scan
        persistent:  mutable dict of persistent state (timers, etc.)

    Returns:
        Full state dict after scan execution
    """
    # Start from persistent state
    state = dict(persistent)

    # Inject concrete inputs (override any previous values)
    for var in nondet_vars:
        if var in inputs:
            state[var] = inputs[var]

    # Execute rung assignments with OR semantics for parallel rungs
    written_this_scan = {}
    for dest, expr in assignments:
        val = eval_expr(expr, state)
        if dest in written_this_scan:
            # Parallel rung: OR with previous value
            new_val = int(bool(written_this_scan[dest] or val))
            written_this_scan[dest] = new_val
            state[dest] = new_val
        else:
            written_this_scan[dest] = val
            state[dest] = val

    # Update persistent state with all written variables
    for dest in written_this_scan:
        persistent[dest] = state[dest]

    return state

# ── Benchmark processor ───────────────────────────────────────────────────────

def run_sequences(nondet_vars: list, assignments: list,
                  sequences: list, out_vars: list) -> list:
    """Execute every sequence/scan and collect the output variables per scan."""
    all_outputs = []
    for seq in sequences:
        persistent = {}
        seq_outputs = []
        for scan_inputs in seq["scans"]:
            state = execute_scan(nondet_vars, assignments, scan_inputs, persistent)
            seq_outputs.append({v: state.get(v, 0) for v in out_vars})
        all_outputs.append(seq_outputs)
    return all_outputs

def process_benchmark(name: str, ld_file: str, inp_file: Path,
                      output_dir: Path, esbmc_bin: str) -> None:
    """Process one benchmark: extract IR, execute all sequences, save outputs."""

    # Extract GOTO IR
    ir_text = get_goto_ir(esbmc_bin, ld_file, PROPS_FILES.get(name))
    nondet_vars, assignments = parse_scan_loop(ir_text)

    if not nondet_vars:
        print(f"  ⚠  {name}: no NONDET inputs found in GOTO IR — skipping")
        return

    # Load input sequences and execute them
    data      = json.loads(inp_file.read_text())
    sequences = data["sequences"]
    all_outputs = run_sequences(nondet_vars, assignments, sequences, data["outputs"])

    total = len(sequences) * len(sequences[0]["scans"])
    print(f"  → {name}")
    print(f"    inputs ({len(nondet_vars)}): {nondet_vars}")
    print(f"    rungs : {len(assignments)} assignments")

    # Save results
    result = {
        "benchmark":    name,
        "ld_file":      ld_file,
        "n_sequences":  len(sequences),
        "n_scans":      len(sequences[0]["scans"]),
        "nondet_vars":  nondet_vars,
        "n_assignments": len(assignments),
        "outputs":      all_outputs,
    }
    out_file = output_dir / f"{name}_outputs.json"
    out_file.write_text(json.dumps(result, indent=2))
    print(f"    ✓ {total} scans → {out_file}")

# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="P4a Step 3 — GOTO-IR Concrete Executor"
    )
    parser.add_argument("--inputs",    default="conformance/inputs/",
                        help="Directory with input JSON files from gen_inputs.py")
    parser.add_argument("--output",    default="conformance/esbmc_goto_outputs/",
                        help="Output directory for GOTO-IR execution results")
    parser.add_argument("--esbmc",     default="./build/src/esbmc/esbmc",
                        help="Path to ESBMC binary")
    parser.add_argument("--benchmark", default=None,
                        help="Run a single benchmark only")
    args = parser.parse_args()

    inputs_dir = Path(args.inputs)
    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    manifest   = json.loads((inputs_dir / "manifest.json").read_text())
    benchmarks = [args.benchmark] if args.benchmark else manifest["benchmarks"]

    print("\nP4a GOTO-IR Concrete Executor")
    print(f"  ESBMC  : {args.esbmc}")
    print(f"  Inputs : {inputs_dir}")
    print(f"  Output : {output_dir}\n")

    for name in benchmarks:
        # Check if this benchmark should be skipped
        if name in SKIPPED:
            print(f"  ⚠  {name}: SKIP — {SKIPPED[name]}")
            continue

        ld_file = LD_FILES.get(name)

        if not ld_file:
            print(f"  ⚠  {name}: not in benchmark registry")
            continue
        if not Path(ld_file).exists():
            print(f"  ⚠  {name}: LD file not found: {ld_file}")
            continue

        inp_file = inputs_dir / f"{name}_inputs.json"
        if not inp_file.exists():
            print(f"  ⚠  {name}: inputs not found: {inp_file}")
            continue

        process_benchmark(name, ld_file, inp_file, output_dir, args.esbmc)

    print("\n✓ Done.")


if __name__ == "__main__":
    main()
