// Auto-generated harness for: strcspn
// Source: src/c2goto/library/string.c:284
// Generated by Byte Repair Contractor

#include <stddef.h>

extern size_t strcspn(const char *s, const char *reject);

void __byterepair_harness_main(void) {
    // --- Symbolic inputs ---
    char a[8], b[8];
    a[7] = '\0';
    b[7] = '\0';
    const char *s = (const char *)a;
    const char *reject = (const char *)b;

    // --- Call under test ---
    size_t result = strcspn(s, reject);

    // --- Postcondition assertions ---
    __ESBMC_assert(result <= 7, "system property: strcspn result <= len(s)");
}
