#define yy_create_buffer yycvc_create_buffer
#define yy_delete_buffer yycvc_delete_buffer
#define yy_scan_buffer yycvc_scan_buffer
#define yy_scan_string yycvc_scan_string
#define yy_scan_bytes yycvc_scan_bytes
#define yy_flex_debug yycvc_flex_debug
#define yy_init_buffer yycvc_init_buffer
#define yy_flush_buffer yycvc_flush_buffer
#define yy_load_buffer_state yycvc_load_buffer_state
#define yy_switch_to_buffer yycvc_switch_to_buffer
#define yyin yycvcin
#define yyleng yycvcleng
#define yylex yycvclex
#define yyout yycvcout
#define yyrestart yycvcrestart
#define yytext yycvctext

#line 19 "lex.yy.cpp"
/* A lexical scanner generated by flex*/

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* Some routines like yy_flex_realloc() are emitted as static but are
   not called by all lexers. This generates warnings in some compilers,
   notably GCC. Arrange to suppress these. */
#ifdef __GNUC__
#define YY_MAY_BE_UNUSED __attribute__((unused))
#else
#define YY_MAY_BE_UNUSED
#endif

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t )) YY_MAY_BE_UNUSED;
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 77
#define YY_END_OF_BUFFER 78
static yyconst short int yy_accept[379] =
    {   0,
        0,    0,   78,   76,    2,    1,   36,   45,   44,   49,
       15,   16,   42,   40,   38,   41,   34,   43,   75,   31,
       33,   17,   39,   18,   35,   37,   74,   74,   74,    7,
       28,    8,   48,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   11,   27,   12,    0,
        1,   36,   45,   44,   49,   16,   42,   40,   38,   41,
       34,   43,   31,   33,    0,   39,   18,   35,   37,    0,
        0,    7,   28,    8,   48,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   11,   27,   12,
        1,   36,   47,   45,   44,   49,   15,   42,   40,   38,

       41,    0,   29,   34,   50,   43,   32,   75,   31,   33,
       17,   30,   19,   39,   46,   20,   35,   37,   74,   74,
       74,   74,   74,    7,    9,   24,   21,   28,    8,   10,
       48,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   11,    0,   13,   27,   22,   23,   14,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   47,    0,    3,   29,   50,   32,   30,   19,
       46,   20,   74,   74,   74,    9,   24,   21,   10,   74,

       74,   74,   74,   74,   74,   74,   74,   67,   74,   74,
       74,   74,   74,   74,   66,   74,   74,   74,   74,   74,
       74,    0,    0,   13,   22,   23,   26,   25,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   74,
       52,   51,   65,   74,   74,   74,   61,   74,   74,   62,
       67,   74,   74,   74,   70,   74,   64,   66,   63,   74,
       74,   54,   74,   74,    0,    0,    4,   26,   25,    0,
       52,   51,    0,   61,    0,    0,   62,    0,    0,    0,
        0,   63,    0,    0,   54,    0,    0,   53,   65,   74,

       74,   74,   61,   69,   55,   62,   60,   74,   73,   70,
       74,   64,   63,   68,   74,   59,   74,    4,   53,    0,
       55,   60,    0,    0,    0,   59,    0,   53,    6,   74,
       74,   69,   60,   74,   73,   74,   68,   74,   59,   74,
        6,    0,    0,    0,    0,    6,   74,   74,   72,   74,
       74,   71,    0,    0,   56,   74,   72,   74,   74,   71,
        0,    0,   56,   57,   58,   74,    0,   57,   58,   74,
        0,   74,    0,    0,    5,   74,   74,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    5,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   26,   26,   26,
       26,   28,   29,   26,   30,   26,   26,   26,   31,   32,
       26,   26,   33,   34,   26,   26,   26,   26,   26,   26,
       35,   36,   37,   38,   39,    1,   40,   41,   42,   43,

       44,   45,   26,   46,   47,   26,   26,   48,   49,   50,
       51,   52,   26,   53,   54,   55,   56,   26,   57,   26,
       58,   26,   59,   60,   61,   62,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[63] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    1,    1,    1,
        1,    1,    1,    1,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    1,    1,    1,    1,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1,
        1,    1
    } ;

static yyconst short int yy_base[384] =
    {   0,
        0,    0,  873,  874,   61,   67,   89,   84,   87,  100,
      111,  874,  121,  123,  125,  127,  129,  131,  855,  133,
      135,  137,  140,  850,  143,  145,  862,   87,  142,  150,
      152,  154,  157,  154,  155,  156,  157,  158,  162,  166,
      169,  167,  161,  175,  170,  172,  179,  186,  874,    0,
      192,  222,  197,  224,  227,  874,  229,  231,  233,  235,
      238,  242,  248,  252,   79,  256,  848,  258,  260,  840,
      156,  262,  264,  266,  268,  202,  820,  818,  825,  820,
      123,  232,  233,  810,  234,  812,  814,  279,  283,  874,
      286,  288,  292,  298,  302,  304,  306,  308,  310,  312,

      314,  857,  316,  321,  323,  325,  327,  842,  329,  331,
      333,  335,  338,  344,  346,  348,  350,  352,  850,  849,
      271,  163,  171,  354,  356,  358,  360,  362,  364,  366,
      368,  334,  364,  365,  366,  367,  368,  371,  370,  378,
      374,   70,  375,  376,  234,  377,  385,  381,  383,  384,
      386,  382,  393,  842,  395,  397,  399,  401,  874,  795,
      829,  824,  821,  808,  796,  804,  794,  799,  806,  404,
      790,  795,  792,  787,  792,  785,  406,  792,  794,  374,
      790,  781,  413,  832,  874,  432,  436,  439,  441,  443,
      445,  447,  290,  428,  443,  450,  452,  454,  456,  460,

      456,  415,  458,  459,  461,  417,  464,  471,  462,  176,
      468,  475,  471,  478,  482,  474,  479,  480,  481,  482,
      485,  820,  477,  492,  494,  499,  506,  508,  802,  800,
      799,  510,  786,  784,  784,  773,  783,  781,  783,  768,
      514,  778,  516,  773,  770,  769,  774,  766,  770,  189,
      807,  806,  518,  484,  491,  495,  524,  532,  516,  540,
      542,  506,  520,  544,  551,  528,  553,  555,  559,  562,
      531,  805,  541,  543,  798,  552,  566,  569,  571,  778,
      874,  874,  757,  573,  575,  765,  577,  755,  693,  579,
      680,  584,  586,  680,  874,  683,  685,  590,  592,  576,

      588,  589,  597,  599,  723,  601,  603,  599,  606,  612,
      602,  614,  616,  618,  604,  620,  616,  623,  627,  675,
      874,  631,  689,  670,  674,  633,  675,  635,  638,  619,
      634,  641,  646,  649,  651,  637,  656,  642,  659,  661,
      668,  670,  672,  682,  672,  674,  676,  647,  678,  657,
      660,  685,  677,  667,  690,  692,  694,  696,  675,  700,
      703,  376,  705,  707,  709,  677,  367,  712,  714,  682,
      358,  737,  408,  299,  874,  715,    0,  874,  290,  799,
      801,  803,  805
    } ;

static yyconst short int yy_def[384] =
    {   0,
      378,    1,  378,  378,  378,    5,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  379,  379,  379,  378,
      378,  378,  378,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  378,  378,  378,    5,
        5,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
        5,  378,  378,  378,  378,  378,  378,  378,  378,  378,

      378,  380,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  379,
      379,  379,  379,  378,  378,  378,  378,  378,  378,  378,
      378,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  378,  381,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  380,  378,  378,  378,  378,  378,  378,
      378,  378,  379,  379,  379,  378,  378,  378,  378,  379,

      379,  379,  379,  379,  379,  379,  379,  378,  379,  379,
      379,  379,  379,  379,  378,  379,  379,  379,  379,  379,
      379,  381,  382,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  379,
      379,  379,  378,  379,  379,  379,  379,  379,  379,  379,
      378,  379,  379,  379,  378,  379,  378,  378,  379,  379,
      379,  379,  379,  379,  381,  382,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  379,  378,  379,

      379,  379,  378,  378,  379,  378,  379,  379,  378,  378,
      379,  378,  378,  378,  379,  379,  379,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  379,  379,
      379,  378,  378,  379,  378,  379,  378,  379,  378,  379,
      378,  378,  378,  378,  378,  378,  379,  379,  378,  379,
      379,  378,  378,  378,  378,  379,  378,  379,  379,  378,
      378,  378,  378,  378,  378,  379,  378,  378,  378,  379,
      378,  378,  383,  383,  378,  383,  372,    0,  378,  378,
      378,  378,  378
    } ;

static yyconst short int yy_nxt[937] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,    4,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   27,   28,   27,   27,   27,
       27,   27,   29,   27,   30,   31,   32,   33,    4,   34,
       27,   35,   36,   37,   38,   39,   40,   41,   27,   42,
       43,   27,   27,   27,   44,   45,   46,   27,   47,   48,
       49,    4,   50,   51,   52,   53,   54,   55,   91,   91,
       56,   57,   58,   59,   60,   61,   62,  119,   63,   64,
       65,   66,   67,   68,   69,   94,   94,   70,   95,   95,
       92,   92,  112,   71,  119,   72,   73,   74,   75,  113,

       76,   96,   96,   77,   78,   79,   80,   81,   82,   93,
       83,   84,   97,   97,  121,   85,   86,   87,  210,   88,
       89,   90,   98,   98,   99,   99,  100,  100,  101,  101,
      104,  104,  106,  106,  109,  109,  110,  110,  111,  111,
      102,  114,  114,  105,  117,  117,  118,  118,  103,  119,
      112,  124,  124,  128,  128,  129,  129,  113,  131,  131,
      115,  119,  119,  119,  119,  119,  107,  170,  119,  119,
      119,  122,  171,  119,  119,  123,  119,  119,  119,  119,
      153,  153,  119,  119,  125,  162,  126,  156,  156,  163,
      130,  194,  154,   91,   91,  135,  119,  138,   94,   94,

      134,  195,  136,  132,  137,  139,  145,  133,  142,  127,
      140,  143,  144,  147,  148,  141,  263,  146,  152,  151,
      149,  298,  157,   92,   92,   95,   95,  150,   96,   96,
       98,   98,   99,   99,  100,  100,  101,  101,  155,  104,
      104,  119,   93,  106,  106,  158,  159,  160,  102,  109,
      109,  164,  105,  110,  110,  165,  103,  114,  114,  117,
      117,  118,  118,  124,  124,  128,  128,  129,  129,  131,
      131,  172,  175,  178,  173,  174,  115,  107,  119,  179,
      153,  153,  213,  176,  156,  156,  180,   91,   91,   92,
       92,  120,  154,  183,  183,  193,  125,  119,  126,   94,

       94,  375,  130,   95,   95,   96,   96,   97,   97,   98,
       98,   99,   99,  100,  100,  101,  101,  186,  186,  157,
      250,  127,  104,  104,  187,  187,  106,  106,  188,  188,
      109,  109,  110,  110,  111,  111,  189,  189,  155,  190,
      190,  119,  158,  159,  160,  114,  114,  191,  191,  192,
      192,  117,  117,  118,  118,  124,  124,  196,  196,  197,
      197,  198,  198,  128,  128,  129,  129,  199,  199,  131,
      131,  119,  119,  119,  119,  119,  200,  119,  119,  208,
      208,  119,  119,  119,  119,  119,  215,  215,  119,  119,
      119,  119,  119,  119,  153,  153,  224,  224,  156,  156,

      225,  225,  226,  226,  202,  208,  208,  215,  215,  207,
      375,  204,  373,  246,  183,  183,  371,  201,  206,  367,
      203,  205,  119,  218,  119,  211,  217,  216,  209,  247,
      212,  214,  220,  186,  186,  119,  221,  187,  187,  219,
      188,  188,  189,  189,  190,  190,  191,  191,  192,  192,
      119,  196,  196,  197,  197,  198,  198,  199,  199,  251,
      227,  253,  253,  119,  255,  119,  119,  119,  119,  119,
      259,  119,  261,  261,  252,  119,  265,  265,  119,  267,
      267,  119,  119,  268,  268,  119,  119,  119,  119,  119,
      276,  119,  119,  224,  224,  225,  225,  256,  119,  254,

      226,  226,  119,  257,  258,  262,  260,  278,  278,  279,
      279,  253,  253,  119,  266,  265,  265,  267,  267,  299,
      299,  269,  264,  119,  272,  303,  303,  119,  270,  271,
      274,  119,  273,  304,  304,  119,  300,  277,  119,  119,
      301,  306,  306,  261,  261,  309,  309,  119,  119,  302,
      119,  119,  310,  310,  312,  312,  268,  268,  307,  305,
      313,  313,  308,  314,  314,  276,  119,  318,  318,  119,
      278,  278,  279,  279,  303,  303,  304,  304,  306,  306,
      309,  309,  311,  119,  315,  313,  313,  314,  314,  317,
      316,  328,  328,  299,  299,  119,  119,  119,  303,  303,

      332,  332,  306,  306,  333,  333,  119,  335,  335,  119,
      119,  119,  378,  310,  310,  312,  312,  313,  313,  337,
      337,  339,  339,  119,  318,  318,  119,  119,  328,  328,
      329,  330,  333,  333,  339,  339,  328,  328,  334,  346,
      346,  119,  332,  332,  119,  119,  331,  333,  333,  119,
      349,  349,  335,  335,  119,  338,  119,  337,  337,  336,
      339,  339,  352,  352,  119,  340,  347,  119,  119,  346,
      346,  349,  349,  352,  352,  346,  346,  355,  355,  357,
      357,  351,  119,  119,  119,  348,  360,  360,  350,  119,
      356,  363,  363,  364,  364,  357,  357,  365,  365,  119,

      358,  360,  360,  119,  365,  365,  363,  363,  368,  368,
      369,  369,  359,  368,  368,  369,  369,  375,  366,  362,
      361,  354,  376,  353,  345,  344,  370,  343,  342,  341,
      119,  327,  326,  325,  324,  323,  372,  374,  374,  375,
      374,  374,  374,  374,  376,  374,  374,  374,  374,  374,
      374,  374,  374,  377,  374,  374,  374,  374,  374,  374,
      374,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  374,  374,  374,  374,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  374,  374,  374,  374,  184,

      184,  222,  222,  275,  275,  374,  374,  322,  321,  320,
      319,  223,  119,  119,  119,  297,  296,  295,  294,  293,
      292,  291,  290,  289,  288,  287,  286,  285,  284,  283,
      282,  281,  280,  223,  185,  249,  248,  245,  244,  243,
      242,  241,  240,  239,  238,  237,  236,  235,  234,  233,
      232,  231,  230,  229,  228,  223,  119,  119,  108,  185,
      182,  181,  177,  169,  168,  167,  166,  161,  116,  119,
      116,  108,  378,    3,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,

      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378
    } ;

static yyconst short int yy_chk[937] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    5,    5,    5,    5,    5,    6,    6,
        5,    5,    5,    5,    5,    5,    5,  142,    5,    5,
        5,    5,    5,    5,    5,    8,    8,    5,    9,    9,
        7,    7,   65,    5,   28,    5,    5,    5,    5,   65,

        5,   10,   10,    5,    5,    5,    5,    5,    5,    7,
        5,    5,   11,   11,   28,    5,    5,    5,  142,    5,
        5,    5,   13,   13,   14,   14,   15,   15,   16,   16,
       17,   17,   18,   18,   20,   20,   21,   21,   22,   22,
       16,   23,   23,   17,   25,   25,   26,   26,   16,   29,
       22,   30,   30,   31,   31,   32,   32,   22,   33,   33,
       23,   34,   35,   36,   37,   38,   18,   81,   43,   39,
      122,   29,   81,   40,   42,   29,   41,   45,  123,   46,
       47,   47,   44,  210,   30,   71,   30,   48,   48,   71,
       32,  122,   47,   51,   51,   36,  250,   38,   53,   53,

       35,  123,   36,   34,   37,   39,   42,   34,   41,   30,
       40,   41,   41,   43,   44,   40,  210,   42,   46,   45,
       44,  250,   48,   52,   52,   54,   54,   44,   55,   55,
       57,   57,   58,   58,   59,   59,   60,   60,   47,   61,
       61,  145,   52,   62,   62,   48,   48,   48,   60,   63,
       63,   76,   61,   64,   64,   76,   60,   66,   66,   68,
       68,   69,   69,   72,   72,   73,   73,   74,   74,   75,
       75,   82,   83,   85,   82,   82,   66,   62,  121,   85,
       88,   88,  145,   83,   89,   89,   85,   91,   91,   92,
       92,  379,   88,   93,   93,  121,   72,  193,   72,   94,

       94,  374,   74,   95,   95,   96,   96,   97,   97,   98,
       98,   99,   99,  100,  100,  101,  101,  103,  103,   89,
      193,   72,  104,  104,  105,  105,  106,  106,  107,  107,
      109,  109,  110,  110,  111,  111,  112,  112,   88,  113,
      113,  132,   89,   89,   89,  114,  114,  115,  115,  116,
      116,  117,  117,  118,  118,  124,  124,  125,  125,  126,
      126,  127,  127,  128,  128,  129,  129,  130,  130,  131,
      131,  133,  134,  135,  136,  137,  132,  139,  138,  140,
      140,  141,  143,  144,  146,  140,  147,  147,  148,  152,
      149,  150,  147,  151,  153,  153,  155,  155,  156,  156,

      157,  157,  158,  158,  134,  170,  170,  177,  177,  139,
      373,  136,  371,  180,  183,  183,  367,  133,  138,  362,
      135,  137,  202,  150,  206,  143,  149,  148,  141,  180,
      144,  146,  151,  186,  186,  194,  152,  187,  187,  150,
      188,  188,  189,  189,  190,  190,  191,  191,  192,  192,
      195,  196,  196,  197,  197,  198,  198,  199,  199,  194,
      158,  200,  200,  201,  202,  203,  204,  200,  205,  209,
      206,  207,  208,  208,  195,  211,  212,  212,  213,  214,
      214,  216,  212,  215,  215,  214,  217,  218,  219,  220,
      223,  254,  221,  224,  224,  225,  225,  203,  255,  201,

      226,  226,  256,  204,  205,  209,  207,  227,  227,  228,
      228,  232,  232,  262,  213,  241,  241,  243,  243,  253,
      253,  216,  211,  259,  219,  257,  257,  263,  217,  218,
      221,  257,  220,  258,  258,  266,  254,  223,  271,  258,
      255,  260,  260,  261,  261,  264,  264,  260,  273,  256,
      274,  264,  265,  265,  267,  267,  268,  268,  262,  259,
      269,  269,  263,  270,  270,  276,  269,  277,  277,  270,
      278,  278,  279,  279,  284,  284,  285,  285,  287,  287,
      290,  290,  266,  300,  271,  292,  292,  293,  293,  274,
      273,  298,  298,  299,  299,  301,  302,  298,  303,  303,

      304,  304,  306,  306,  307,  307,  308,  309,  309,  311,
      307,  315,  276,  310,  310,  312,  312,  313,  313,  314,
      314,  316,  316,  317,  318,  318,  330,  316,  319,  319,
      300,  301,  322,  322,  326,  326,  328,  328,  308,  329,
      329,  331,  332,  332,  336,  329,  302,  333,  333,  338,
      334,  334,  335,  335,  348,  315,  334,  337,  337,  311,
      339,  339,  340,  340,  350,  317,  330,  351,  340,  341,
      341,  342,  342,  345,  345,  346,  346,  347,  347,  349,
      349,  338,  359,  347,  366,  331,  352,  352,  336,  370,
      348,  355,  355,  356,  356,  357,  357,  358,  358,  356,

      350,  360,  360,  358,  361,  361,  363,  363,  364,  364,
      365,  365,  351,  368,  368,  369,  369,  376,  359,  354,
      353,  344,  376,  343,  327,  325,  366,  324,  323,  320,
      305,  297,  296,  294,  291,  289,  370,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  380,

      380,  381,  381,  382,  382,  383,  383,  288,  286,  283,
      280,  275,  272,  252,  251,  249,  248,  247,  246,  245,
      244,  242,  240,  239,  238,  237,  236,  235,  234,  233,
      231,  230,  229,  222,  184,  182,  181,  179,  178,  176,
      175,  174,  173,  172,  171,  169,  168,  167,  166,  165,
      164,  163,  162,  161,  160,  154,  120,  119,  108,  102,
       87,   86,   84,   80,   79,   78,   77,   70,   67,   27,
       24,   19,    3,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,

      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#define INITIAL 0
#line 2 "scanner.l"
#define YYSTYPE exprt
#include "expr.h"
#include "y.tab.h"
#include "cvc_parser.h"
#define YY_NO_UNPUT 1
#line 731 "lex.yy.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 17 "scanner.l"


#line 885 "lex.yy.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 379 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 874 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 19 "scanner.l"
return NEWLINE;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 20 "scanner.l"
/* eat up single blanks and tabs */
	YY_BREAK
case 3:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 21 "scanner.l"
/* eat up comments */
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 22 "scanner.l"
/* eat up block comments */
	YY_BREAK
case 5:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 23 "scanner.l"
/* eat up transparent-declarations from FDR-2-files. */
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 25 "scanner.l"
return ASSERT;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 26 "scanner.l"
return LSQUARE;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 27 "scanner.l"
return RSQUARE;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 28 "scanner.l"
return LSUBST;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 29 "scanner.l"
return RSUBST;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 30 "scanner.l"
return LBRACE;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 31 "scanner.l"
return RBRACE;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 32 "scanner.l"
return LPBRACE;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 33 "scanner.l"
return RPBRACE;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 34 "scanner.l"
return OPEN;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 35 "scanner.l"
return CLOSE;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 36 "scanner.l"
return LT;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 37 "scanner.l"
return GT;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 38 "scanner.l"
return LE;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 39 "scanner.l"
return GE;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 40 "scanner.l"
return LCOMM;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 41 "scanner.l"
return RCOMM;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 42 "scanner.l"
return PAR;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 43 "scanner.l"
return BOX;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 44 "scanner.l"
return NDET;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 45 "scanner.l"
return INTL;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 46 "scanner.l"
return PIPE;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 47 "scanner.l"
return BACKSLASH;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 48 "scanner.l"
return ARROW;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 49 "scanner.l"
return BECOMES;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 50 "scanner.l"
return COLON;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 51 "scanner.l"
return INTR;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 52 "scanner.l"
return SEMI;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 53 "scanner.l"
return DOT;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 54 "scanner.l"
return QUERY;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 55 "scanner.l"
return PLING;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 56 "scanner.l"
return AT;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 57 "scanner.l"
return COMMA;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 58 "scanner.l"
return EQUAL;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 59 "scanner.l"
return PLUS;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 60 "scanner.l"
return MINUS;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 61 "scanner.l"
return TIMES;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 62 "scanner.l"
return SLASH;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 63 "scanner.l"
return MOD;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 64 "scanner.l"
return HASH;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 65 "scanner.l"
return EQ;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 66 "scanner.l"
return NE;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 67 "scanner.l"
return CAT;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 68 "scanner.l"
return GUARD;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 69 "scanner.l"
return DOTDOT;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 71 "scanner.l"
return STOP;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 72 "scanner.l"
return SKIP;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 73 "scanner.l"
return CHAOS;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 74 "scanner.l"
return CSPTRUE;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 75 "scanner.l"
return CSPFALSE;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 76 "scanner.l"
return CHANNEL;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 77 "scanner.l"
return DATATYPE;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 78 "scanner.l"
return NAMETYPE;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 79 "scanner.l"
return UNION;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 80 "scanner.l"
return INTER;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 81 "scanner.l"
return DIFF;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 82 "scanner.l"
return HEAD;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 83 "scanner.l"
return TAIL;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 84 "scanner.l"
return NOT;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 85 "scanner.l"
return AND;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 86 "scanner.l"
return OR;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 87 "scanner.l"
return IF;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 88 "scanner.l"
return THEN;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 89 "scanner.l"
return ELSE;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 90 "scanner.l"
return LET;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 91 "scanner.l"
return WITHIN;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 92 "scanner.l"
return LAMBDA;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 93 "scanner.l"
return LDOT;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 95 "scanner.l"
{ yycvclval.id(yytext); return NAME; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 96 "scanner.l"
{ yycvclval.id(yytext); return NUMBER; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 98 "scanner.l"
;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 100 "scanner.l"
ECHO;
	YY_BREAK
#line 1359 "lex.yy.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 379 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 379 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 378);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 100 "scanner.l"

