// Auto-generated harness for: tolower
// Source: src/c2goto/library/ctype.c:133
// Generated by Byte Repair Contractor

extern int tolower(int c);

void __byterepair_harness_main(void) {
    // --- Symbolic inputs ---
    int c = nondet_int();

    // --- Precondition assumptions ---
    __ESBMC_assume((c >= -1) && (c <= 255));

    // --- Call under test ---
    int result = tolower(c);

    // --- Postcondition assertions ---
    __ESBMC_assert(result == ((c >= 'A' && c <= 'Z') ? c + ('a' - 'A') : c), "system property");
    // __ESBMC_assert(/* mirror __ESBMC_ensures conditions */, "description");
}
