// Auto-generated harness for: strcmp
// Source: src/c2goto/library/string.c:146
// Generated by Byte Repair Contractor

#include <stddef.h>

extern int strcmp(const char *p1, const char *p2);

void __byterepair_harness_main(void) {
    // --- Symbolic inputs ---
    char a[8], b[8];
    a[7] = '\0';
    b[7] = '\0';
    const char *p1 = (const char *)a;
    const char *p2 = (const char *)b;

    // --- Call under test ---
    int result = strcmp(p1, p2);

    // --- Postcondition assertions ---
    __ESBMC_assert(result == 0 || result < 0 || result > 0,
        "system property: strcmp returns int (sign-only)");
}
