/* Generated by CIL v. 1.3.6 */
/* print_CIL_Input is true */

#line 1 "/home/lucas/cprover/regression/regression/esbmc/01_cbmc_Malloc2/main.c"
typedef unsigned int size_t;
#line 3 "/home/lucas/cprover/regression/regression/esbmc/01_cbmc_Malloc2/main.c"
typedef int atomic_t;
#line 4 "/home/lucas/cprover/regression/regression/esbmc/01_cbmc_Malloc2/main.c"
typedef unsigned int gfp_t;
#line 8 "/home/lucas/cprover/regression/regression/esbmc/01_cbmc_Malloc2/main.c"
struct pp_struct {
   atomic_t irqc ;
};
#line 12
extern void *malloc(size_t size ) ;
#line 14 "/home/lucas/cprover/regression/regression/esbmc/01_cbmc_Malloc2/main.c"
void *kmalloc(size_t size , gfp_t flags ) 
{ void *tmp ;

  {
#line 16
  tmp = malloc(size);
#line 16
  return (tmp);
}
}
#line 19 "/home/lucas/cprover/regression/regression/esbmc/01_cbmc_Malloc2/main.c"
int main(void) 
{ struct pp_struct *pp ;
  void *tmp ;

  {
#line 23
  tmp = kmalloc(sizeof(struct pp_struct ), 10U);
#line 23
  pp = (struct pp_struct *)tmp;
#line 28
  if (! pp) {
#line 29
    return (-10);
  }
#line 31
  pp->irqc = 0;
#line 33
  return (0);
}
}
