// CXL mailbox doorbell wait as an LTL response property, WITH the timeout.
//
// Models cxl_pci_mbox_wait_for_doorbell() (drivers/cxl/pci.c:57): the driver
// sets the doorbell to submit a command, polls until the device clears it,
// and gives up after CXL_MAILBOX_TIMEOUT_MS (CXL 2.0 §8.2.8.4).
//
// The obligation is a response property, not an invariant:
//
//     G (doorbell_busy -> F mbox_settled)
//
// "a submitted command is eventually answered or abandoned". No single-state
// assertion expresses it. The monitor is generated by
// scripts/ltl_response_ba.py, which reproduces ltl2ba's output for this
// pattern.
//
// READ THIS WITH ITS PAIR. cxl_ltl_doorbell_02 is this driver with the
// timeout removed -- a real bug, an unbounded wait on a device that may never
// answer -- and ESBMC reports the SAME outcome, LTL_FAILING, for both. That
// is not a defect in the encoding: `G (p -> F q)` is pure liveness, so it has
// no finite counterexample, and the generated automaton's
// _ltl2ba_bad_prefix_states is all-false by construction. Bounded model
// checking cannot refute liveness. The pair exists to record that, and to
// break if ESBMC's LTL support ever becomes able to tell them apart.
// Expected: VERIFICATION SUCCESSFUL, LTL_FAILING

int doorbell_busy = 0;
int mbox_settled = 1; /* nothing outstanding before the first submit */

#define CXL_MAILBOX_POLL_LIMIT 4

int main()
{
  for (int cmd = 0; cmd < 2; cmd++)
  {
    /* Submit: set the doorbell, and the command is now outstanding. */
    doorbell_busy = 1;
    mbox_settled = 0;

    for (int i = 0; i < CXL_MAILBOX_POLL_LIMIT; i++)
    {
      if (nondet_int())
      {
        /* Device cleared the doorbell. */
        doorbell_busy = 0;
        mbox_settled = 1;
        break;
      }
    }

    /* The timeout is what makes the obligation dischargeable at all: a
       device that never answers still leaves the driver settled. */
    if (doorbell_busy)
    {
      doorbell_busy = 0;
      mbox_settled = 1; /* -ETIMEDOUT */
    }
  }

  return 0;
}
