#if 0
/* Precomputed transition data
 * Generated by scripts/ltl_response_ba.py -- LTL response pattern.
 *
 * Formula: G (doorbell_busy -> F mbox_settled)
 *
 * States:
 *   0  init, accepting -- no outstanding obligation
 *   1                  -- a doorbell_busy was seen, a mbox_settled is owed
 */
#endif
#include <pthread.h>
#include <stdbool.h>
#include <stdint.h>

void __ESBMC_switch_to_monitor(void);
void __ESBMC_switch_from_monitor(void);
void __ESBMC_register_monitor(pthread_t t);
void __ESBMC_really_atomic_begin();
void __ESBMC_really_atomic_end();
void __ESBMC_atomic_begin();
void __ESBMC_atomic_end();
void __ESBMC_assume(_Bool prop);
void __ESBMC_kill_monitor();
unsigned int nondet_uint();

extern int doorbell_busy;
extern int mbox_settled;

char __ESBMC_property__ltl2ba_cexpr_0[] = "doorbell_busy";
int _ltl2ba_cexpr_0_status(void) { return doorbell_busy; }
char __ESBMC_property__ltl2ba_cexpr_1[] = "mbox_settled";
int _ltl2ba_cexpr_1_status(void) { return mbox_settled; }

typedef enum {
	_ltl2ba_state_0,
	_ltl2ba_state_1,
} _ltl2ba_state;

_ltl2ba_state _ltl2ba_statevar =_ltl2ba_state_0;

unsigned int _ltl2ba_visited_states[2];

void
ltl2ba_fsm(bool state_stats, unsigned int num_iters)
{
	unsigned int choice;
	unsigned int iters;
	_Bool state_is_viable;

	/* Original formula:
	 * G({doorbell_busy} -> F {mbox_settled})
	 */

	for (iters = 0; iters < num_iters; iters++) {
		choice = nondet_uint();

		__ESBMC_atomic_begin();

		switch(_ltl2ba_statevar) {
		case _ltl2ba_state_0:
			state_is_viable = (((!(doorbell_busy)) || ((mbox_settled))) || ((1)) || (((mbox_settled))) || ((false)));
			if (choice == 0) {
				__ESBMC_assume(((!(doorbell_busy)) || ((mbox_settled))));
				_ltl2ba_statevar = _ltl2ba_state_0;
			} else if (choice == 1) {
				__ESBMC_assume(((1)));
				_ltl2ba_statevar = _ltl2ba_state_1;
			} else if (choice == 2) {
				__ESBMC_assume((((mbox_settled))));
				_ltl2ba_statevar = _ltl2ba_state_0;
			} else {
				__ESBMC_assume(0);
			}
			break;
		case _ltl2ba_state_1:
			state_is_viable = (((1)) || (((mbox_settled))) || ((false)));
			if (choice == 0) {
				__ESBMC_assume(((1)));
				_ltl2ba_statevar = _ltl2ba_state_1;
			} else if (choice == 1) {
				__ESBMC_assume((((mbox_settled))));
				_ltl2ba_statevar = _ltl2ba_state_0;
			} else {
				__ESBMC_assume(0);
			}
			break;
		}
		if (state_stats)
			_ltl2ba_visited_states[_ltl2ba_statevar]++;

		__ESBMC_atomic_end();
		// __ESBMC_switch_from_monitor();
	}

	__ESBMC_assert(num_iters == iters, "Unwind bound on ltl2ba_fsm insufficient");

	return;
}

#ifndef LTL_PREFIX_BOUND
#define LTL_PREFIX_BOUND 2147483648
#endif

#define max(x,y) ((x) < (y) ? (y) : (x))

void * ltl2ba_thread(void *dummy)
{
	ltl2ba_fsm(false, LTL_PREFIX_BOUND);
	return 0;
	(void)dummy;
}

void ltl2ba_start_monitor(void)
{
	pthread_t t;

//	__ESBMC_atomic_begin();
	pthread_create(&t, NULL, ltl2ba_thread, NULL);
	__ESBMC_register_monitor(t);
//	__ESBMC_atomic_end();

	// __ESBMC_switch_to_monitor();
}

_Bool _ltl2ba_stutter_accept_table[4][2] = {
{
  true, false, 
},
{
  false, false, 
},
{
  true, true, 
},
{
  true, true, 
},
};

_Bool _ltl2ba_good_prefix_excluded_states[2] = {
true, true, 
};

_Bool _ltl2ba_bad_prefix_states[2] = {
false, false, 
};

unsigned int
_ltl2ba_sym_to_idx(void)
{
	unsigned int idx = 0;
	idx |= ((doorbell_busy)) ? 1 : 0;
	idx |= ((mbox_settled)) ? 2 : 0;
	return idx;
}

void
ltl2ba_finish_monitor(void)
{
	__ESBMC_kill_monitor();

	__ESBMC_assert(!_ltl2ba_bad_prefix_states[_ltl2ba_statevar],"LTL_BAD");

	__ESBMC_assert(!_ltl2ba_stutter_accept_table[_ltl2ba_sym_to_idx()][_ltl2ba_statevar],"LTL_FAILING");

	__ESBMC_assert(!_ltl2ba_good_prefix_excluded_states[_ltl2ba_statevar],"LTL_SUCCEEDING");

	return;
}
