// Auto-generated harness for: ffs
// Source: src/c2goto/library/strings.c:5
// Generated by Byte Repair Contractor

extern int ffs(int x);

void __byterepair_harness_main(void) {
    // --- Symbolic inputs ---
    int x = nondet_int();

    // --- Precondition assumptions ---
    // ffs is total over int (no UB inputs per glibc).

    // --- Call under test ---
    int result = ffs(x);

    // --- Postcondition assertions ---
    __ESBMC_assert(
        result >= 0 &&
        result <= (int)(8 * sizeof(int)) &&
        ((x == 0) == (result == 0)) &&
        ((result == 0) || (((unsigned)x & (1u << (result - 1))) != 0)) &&
        ((result <= 1) || (((unsigned)x & ((1u << (result - 1)) - 1u)) == 0)),
        "system property");
}
