// Auto-generated harness for: strdup
// Source: src/c2goto/library/string.c:378
// Generated by Byte Repair Contractor

#include <stddef.h>
#include <stdlib.h>

extern char *strdup(const char *str);

void __byterepair_harness_main(void) {
    // --- Symbolic inputs ---
    char buf[8];
    buf[7] = '\0';
    const char *str = (const char *)buf;

    // --- Call under test ---
    char *result = strdup(str);

    // --- Postcondition assertions ---
    if (result != ((char *)0))
        free(result);
}
