// Auto-generated by ESBMC 7.11.0
// Test case 2 of 6
// This file provides concrete implementations of __VERIFIER_nondet_* functions

_Bool __VERIFIER_nondet_bool(void) {
  static int i = 0;
  static const _Bool v[] = { 0 };
  return v[i++];
}

char __VERIFIER_nondet_char(void) {
  static int i = 0;
  static const char v[] = { 0 };
  return v[i++];
}

unsigned char __VERIFIER_nondet_uchar(void) {
  static int i = 0;
  static const unsigned char v[] = { 224 };
  return v[i++];
}

