// Auto-generated harness for: iscntrl
// Source: src/c2goto/library/ctype.c:48
// Generated by Byte Repair Contractor

extern int iscntrl(int c);

void __byterepair_harness_main(void) {
    // --- Symbolic inputs ---
    int c = nondet_int();

    // --- Precondition assumptions ---
    __ESBMC_assume((c >= -1) && (c <= 255));

    // --- Call under test ---
    int result = iscntrl(c);

    // --- Postcondition assertions ---
    __ESBMC_assert((result != 0) == ((c >= 0 && c <= 31) || c == 127), "system property");
    // __ESBMC_assert(/* mirror __ESBMC_ensures conditions */, "description");
}
