#include <boost/program_options/value_semantic.hpp>
#include <esbmc/esbmc_parseoptions.h>
#include <fstream>
#include <solvers/solver_config.h>
#include <util/cmdline.h>

const struct group_opt_templ all_cmd_options[] = {
  {"Main Usage",
   {{"input-file",
     boost::program_options::value<std::vector<std::string>>()->value_name(
       "file.c ..."),
     "Source file names"}}},
  {"Options",
   {{"help,?", NULL, "Show help"},
    {"function",
     boost::program_options::value<std::string>()->value_name("name"),
     "Set main function name"},
    {"class",
     boost::program_options::value<std::string>()->value_name("cname"),
     "Set the class/namespace name where the function is inside"},
    {"claim",
     boost::program_options::value<std::vector<int>>()->value_name("nr"),
     "Only check specific claim"},
    {"instruction",
     boost::program_options::value<int>()->value_name("nr"),
     "Limit the number of instructions executed during symbolic execution"},
    {"git-hash", NULL, "Show ESBMC version with git hash and exit"},
    {"verbosity",
     boost::program_options::value<std::vector<std::string>>(),
     "Verbosity of log output, can be given multiple times. Parameter is "
     "either a decimal N or 'module:N' to set the log-level of debug messages "
     "of the module to N; without module, it sets the global log-level"}}},
  {"Printing options",
   {{"symbol-table-only", NULL, "Only show symbol table"},
    {"symbol-table-too", NULL, "Show symbol table and verify"},
    {"parse-tree-only", NULL, "Only show parse tree"},
    {"parse-tree-too", NULL, "Show parse tree and verify"},
    {"goto-functions-only", NULL, "Only show goto program"},
    {"goto-functions-too", NULL, "Show goto program and verify"},
    {"dump-goto-cfg",
     NULL,
     "create a file for each function with the associated CFG in DOT format"},
    {"show-call-sites",
     NULL,
     "show each function call site with its arguments"},
    {"program-only", NULL, "Only show program expression"},
    {"program-too", NULL, "Show program expression and verify"},
    {"ssa-symbol-table", NULL, "Show symbol table along with SSA"},
    {"ssa-guards", NULL, "Print guard expressions in SSA output"},
    {"ssa-sliced", NULL, "Print the sliced SSAs"},
    {"ssa-no-location", NULL, "Omit location info from SSA output"},
    {"smt-formula-only",
     NULL,
     "only show SMT formula (not supported by all solvers)"},
    {"smt-formula-too",
     NULL,
     "show SMT formula (not supported by all solvers), and verify"},
    {"smt-model",
     NULL,
     "show SMT model (not supported by all solvers), if the formula is SAT"},
    {"color",
     boost::program_options::value<std::string>()
       ->default_value("auto")
       ->value_name("auto|always|never"),
     "show colored output"},
    {"log-message",
     NULL,
     "print LOG message including file, line, and timestamp"},
    {"keep-alive-interval",
     boost::program_options::value<int>()->value_name("interval"),
     "Set interval (in seconds) for keep alive messages (default: 60)"},
    {"enable-keep-alive",
     NULL,
     "Enable keep alive messages during long solving processes"}}},
  {"Trace",
   {{"quiet",
     NULL,
     "do not print unwinding information during symbolic execution"},
    {"compact-trace",
     NULL,
     "enable --no-slice and hide internal symbols from the trace"},
    {"symex-trace", NULL, "Print instructions during symbolic execution"},
    {"ssa-trace", NULL, "Print SSA during SMT encoding"},
    {"ssa-smt-trace", NULL, "Print generated SMT during SMT encoding"},
    {"ssa-features-dump",
     NULL,
     "print features in the SSA (just before conversion)"},
    {"symex-ssa-trace", NULL, "Print generated SSA during symbolic execution"},
    {"goto2c", NULL, "Translate the GOTO program to C"},
    {"show-goto-value-sets",
     NULL,
     "show value-set analysis for the goto functions"},
    {"show-symex-value-sets",
     NULL,
     "show value-set analysis during symbolic execution"}}},
#ifdef ENABLE_PYTHON_FRONTEND
  {"Python frontend",
   {
     {"python",
      boost::program_options::value<std::string>()->value_name("path"),
      "Python interpreter binary to use (searched in $PATH; default: python)"},
     {"override-return-annotation",
      NULL,
      "Override return annotation with inferred type"},
     {"strict-types",
      NULL,
      "Enforce strict type checking for function arguments during "
      "verification"},
     {"nondet-str-length",
      boost::program_options::value<int>()->default_value(16)->value_name("nr"),
      "set maximum length for non-deterministic strings (default is 16)"},
     {"python-list-compare-depth",
      boost::program_options::value<int>()->default_value(4)->value_name("nr"),
      "set maximum nesting depth for Python list comparison (default is 4)"},
   }},
#endif
#ifdef ENABLE_SOLIDITY_FRONTEND
  {"Solidity frontend",
   {{"sol",
     boost::program_options::value<std::string>()->value_name("path"),
     ".sol and .solast file names"},
    {"contract",
     boost::program_options::value<std::string>()->value_name("cname"),
     "set contract name"},
    {"no-visibility",
     NULL,
     "force to verify every function, even it's an unreachable "
     "internal/private function"},
    {"unbound", NULL, "Model external function calls as arbitrary behavior"},
    {"bound",
     NULL,
     "model inter-contract function calls within a bounded system (default)"},
    {"reentry-check",
     NULL,
     "detect reentrancy behavior during contract execution"},
    {"negating-property",
     boost::program_options::value<std::string>()->value_name("fname"),
     "convert the assert(cond) to assert(!cond)"}}},
#endif
  {"Frontend",
   {{"include,I",
     boost::program_options::value<std::vector<std::string>>()->value_name(
       "path"),
     "set include path"},
    {"include-file",
     boost::program_options::value<std::vector<std::string>>()->value_name(
       "file"),
     "include files via frontend's -include option before anything else"},
    {"nostdinc", NULL, "Do not include from standard system paths"},
    {"idirafter",
     boost::program_options::value<std::vector<std::string>>()->value_name(
       "path"),
     "append system include path to search after system headers"},
    {"define,D",
     boost::program_options::value<std::vector<std::string>>()->value_name(
       "macro"),
     "define preprocessor macro"},
    {"warning,W",
     boost::program_options::value<std::vector<std::string>>(),
     "enable specific frontend warnings, disable with \"no-\" prefix, or pass "
     "options directly to the C/C++ frontends with the form "
     "-Wc,OPT1,OPT2,..."},
    {"std",
     boost::program_options::value<std::string>()->value_name("version"),
     "set C/C++ standard version"},
    {"sysroot",
     boost::program_options::value<std::string>()->value_name("<path>"),
     "set the sysroot for the frontend"},
    {"no-abstracted-cpp-includes",
     NULL,
     "do not include abstract cpp operational models"},
    {"force,f",
     boost::program_options::value<std::vector<std::string>>(),
     "pass -f flags to the C/C++ frontend"},
    {"preprocess", NULL, "Stop after preprocessing"},
    {"no-inlining", NULL, "Disable inlining function calls"},
    {"full-inlining", NULL, "Perform full inlining of function calls"},
    {"all-claims", NULL, "Keep all claims"},
    {"keep-verified-claims",
     NULL,
     "do not skip verified claims in multi-property verification"},
    {"show-loops", NULL, "Show the loops in the program"},
    {"show-claims", NULL, "Only show claims"},
    {"show-vcc", NULL, "Show the verification conditions"},
    {"show-stacktrace",
     NULL,
     "show the stack trace of function call in the counterexample"},
    {"simplify-trace",
     NULL,
     "simplify the trace and exclude the assignments whose variables are not "
     "from user-input files"},
    {"document-subgoals", NULL, "Generate subgoals documentation"},
    {"no-arch", NULL, "Don't set up an architecture"},
    {"no-library", NULL, "Disable built-in abstract C library"},
    {"no-string-literal", NULL, "Ignores string literals (replace by NULL)"},
    {"output-goto",
     boost::program_options::value<std::string>(),
     "export generated goto program"},
    {"binary", NULL, "Read goto program instead of source code"},
    {"cprover", NULL, "Add compatibility layer for CPROVER gotos"},
    {"little-endian", NULL, "Allow little-endian word-byte conversions"},
    {"big-endian", NULL, "Allow big-endian word-byte conversions"},
    {"16", NULL, "Set width of machine word (default is 64)"},
    {"32", NULL, "Set width of machine word (default is 64)"},
    {"64", NULL, "Set width of machine word (default is 64)"},
    {"cheri",
     boost::program_options::value<std::string>()->value_name("mode"),
     "enable CHERI-C in 'hybrid' or 'purecap' mode (default is off)"},
    {"cheri-uncompressed",
     NULL,
     "use full CHERI capabilities instead of the concentrate format"},
    {"version", NULL, "Show current ESBMC version and exit"},
    {"cex-output",
     boost::program_options::value<std::string>(),
     "save the counterexample into a file or, "
     "in multi-property mode, multiple files with name prefix 'N-' "
     "where 'N' is a decimal increasing from zero"},
    {"file-output",
     boost::program_options::value<std::string>(),
     "redirects every message into a file (no stdout/stderr)"},
    {"dont-care-about-missing-extensions",
     NULL,
     "Don't crash on unsupported extensions."},
    {"witness-output",
     boost::program_options::value<std::string>()->value_name("path"),
     "generate the verification result witness in both Yaml and GraphML "
     "format."},
    {"witness-output-graphml",
     boost::program_options::value<std::string>()->value_name("{ path | - }"),
     "generate the verification result witness in GraphML format; use '-' for "
     "output to stdout"},
    {"witness-output-yaml",
     boost::program_options::value<std::string>()->value_name("{ path | - }"),
     "generate the verification result witness in Yaml format; use '-' for "
     "output to stdout"},
    {"witness-producer",
     boost::program_options::value<std::string>(),
     "override the producer name in witness files"},
    {"witness-programfile",
     boost::program_options::value<std::string>(),
     "override the program file name in witness files"},
    {"validate-correctness-witness",
     NULL,
     "validates the YAML correctness witness (2.0)"},
    {"witness-parse-tree",
     NULL,
     "show YAML correctness witness c_expression parse tree"},
    {"witness",
     boost::program_options::value<std::string>()->value_name("<path>"),
     "set the witness path"},
    {"generate-testcase",
     NULL,
     "if a solution is found, generates a testcase in XML"},
    {"generate-pytest-testcase",
     NULL,
     "if a solution is found, generates a pytest testcase for Python programs"},
    {"generate-ctest-testcase",
     NULL,
     "if a solution is found, generates CTest testcases for C programs"},
    {"generate-html-report",
     NULL,
     "if a violation is found, generates a HTML report"},
    {"generate-json-report",
     NULL,
     "if a violation is found, generates a JSON report"},
    {"old-frontend",
     NULL,
     "parse source files using the old frontend (deprecated)"},
    {"result-only", NULL, "Do not print the counter-example"},
#ifdef _WIN32
    {"i386-macos", NULL, "Set MACOS/I386 architecture"},
    {"ppc-macos", NULL, "Set PPC/I386 architecture"},
    {"i386-linux", NULL, "Set Linux/I386 architecture"},
    {"i386-win32", NULL, "Set Windows/I386 architecture (default)"},
#elif __APPLE__
    {"i386-macos", NULL, "Set MACOS/I386 architecture (default)"},
    {"ppc-macos", NULL, "Set PPC/I386 architecture"},
    {"i386-linux", NULL, "Set Linux/I386 architecture"},
    {"i386-win32", NULL, "Set Windows/I386 architecture"},
#else
    {"i386-macos", NULL, "Set MACOS/I386 architecture"},
    {"ppc-macos", NULL, "Set PPC/I386 architecture"},
    {"i386-linux", NULL, "Set Linux/I386 architecture (default)"},
    {"i386-win32", NULL, "Set Windows/I386 architecture"},
#endif
    {"funsigned-char", NULL, "make \"char\" unsigned by default"},
    {"fms-extensions", NULL, "Enable microsoft C extensions"}}},
  {"Function Contracts",
   {{"enforce-contract",
     boost::program_options::value<std::vector<std::string>>()->value_name(
       "fun"),
     "wrap function to check its contract (use \"*\" for all functions)"},
    {"replace-call-with-contract",
     boost::program_options::value<std::vector<std::string>>()->value_name(
       "fun"),
     "replace function calls with contract semantics (use \"*\" for all "
     "functions)"},
    {"assume-nonnull-valid",
     nullptr,
     "in --enforce-contract mode, assume non-null pointer parameters are valid "
     "objects"},
    {"enforce-all-contracts",
     nullptr,
     "enforce contracts for all functions marked with __ESBMC_contract"},
    {"replace-all-contracts",
     nullptr,
     "replace calls to all functions marked with __ESBMC_contract"}}},
  {"BMC",
   {{"unwind",
     boost::program_options::value<int>()->value_name("nr"),
     "unwind nr times"},
    {"unwindset",
     boost::program_options::value<std::string>()->value_name("L:nr,..."),
     "unwind loop L with nr times (use --show-loops to get the loops info)"},
    {"unwindsetname",
     boost::program_options::value<std::string>()->value_name(
       "name:idx:nr,..."),
     "unwind loop idx (0-indexed) in function name with nr times.\n"
     "\tSyntax: func, N@ns@func, S@Class@method, file.c@func,\n"
     "\t        N@ns@S@Class@method, file.c@N@ns@S@Class@method\n"
     "\tAlso accepts Clang USR format (e.g., c:@F@func# or c:file.c@F@func#)\n"
     "\tExample: --unwindsetname compute:0:10,N@math@sum:1:5\n"
     "\tUse --show-loops to see available functions and loop indices"},
    {"no-unwinding-assertions", NULL, "Do not generate unwinding assertions"},
    {"no-remove-unreachable",
     NULL,
     "disable the removal of unreachable code in GOTO programs"},
    {"no-remove-no-op",
     NULL,
     "disable the removal of NO-OP instructions in GOTO programs"},
    {"partial-loops", NULL, "Permit paths with partial loops"},
    {"no-slice", NULL, "Do not remove unused equations"},
    {"multi-fail-fast",
     boost::program_options::value<int>()->value_name("n"),
     "stops after first n VCC violation found in multi property mode"},
    {"no-slice-name",
     boost::program_options::value<std::vector<std::string>>()->value_name(
       "name"),
     "disable slicing for all symbols generated with the given name"},
    {"no-slice-id",
     boost::program_options::value<std::vector<std::string>>()->value_name(
       "id"),
     "disable slicing for the symbol with the given id"},
    {"goto-unwind", NULL, "Unroll bounded loops at goto level"},
    {"unlimited-goto-unwind",
     NULL,
     "do not unroll bounded loops at goto level (need to enable "
     "--goto-unwind)"},
    {"slice-assumes", NULL, "Remove unused assume statements"},
    {"extended-try-analysis",
     NULL,
     "skip backward stack search for C++ throw targets"},
    {"skip-bmc", NULL, "Do not perform bounded model checking"},
    {"loop-invariant",
     NULL,
     "verify using loop invariant + k-induction (combined mode)"},
    {"loop-invariant-check",
     NULL,
     "verify using loop invariant inductive check (standalone mode)"},
    {"no-cache-asserts",
     NULL,
     "do not cache asserts that were already proven correct"}}},
  {"Incremental BMC",
   {{"incremental-bmc", NULL, "Incremental loop unwinding verification"},
    {"falsification", NULL, "Incremental loop unwinding for bug searching"},
    {"termination",
     NULL,
     "incremental loop unwinding assertion verification"}}},
  {"Solver",
   {{"list-solvers", NULL, "List available solvers and exit"},
    {"boolector", NULL, "Use Boolector (default)"},
    {"z3", NULL, "Use Z3"},
    {"z3-debug", NULL, "Extracts Z3 dump and SMT2 formula"},
    {"z3-debug-dump-file",
     boost::program_options::value<std::string>()->value_name("z3.log"),
     "name for Z3 dump file"},
    {"z3-debug-smt-file",
     boost::program_options::value<std::string>()->value_name("log.smt2"),
     "name for Z3 smt2 file"},
    {"mathsat", NULL, "Use MathSAT"},
    {"cvc", NULL, "Alias for --cvc4; this may change in the future to --cvc5"},
    {"cvc4", NULL, "Use CVC4"},
    {"cvc5", NULL, "Use CVC5"},
    {"yices", NULL, "Use Yices"},
    {"bitwuzla", NULL, "Use Bitwuzla"},
    {"bv", NULL, "Use solver with bit-vector arithmetic"},
    {"ir",
     NULL,
     "use solver with integer/real arithmetic. Integer/real have an unbounded "
     "range, overapproximating normal integers/reals while significantly "
     "boosting performance"},
    {"ir-ieee",
     NULL,
     "use integer/real arithmetic with real-arithmetic enclosure constraints "
     "for floating-point operations"},
    {"parallel-solving",
     NULL,
     "solve each VCC in parallel (this activates --multi-property)"},
    {"smtlib", NULL, "Use SMT lib format"},
    {"default-solver",
     boost::program_options::value<std::string>()->value_name("<solver>"),
     "override default solver used if no concrete one is specified"
#ifdef BOOLECTOR
     " (Boolector)"
#endif
    },
    {"non-supported-models-as-zero",
     NULL,
     "if ESBMC can't extract a type/expression from the solver, then the value "
     "will be set to zero"},
    {"smtlib-solver-prog",

     boost::program_options::value<std::string>(),
     "SMT lib program name"},
    {"output",
     boost::program_options::value<std::string>()->value_name("<filename>"),
     "output VCCs in SMT lib format to given file (or stdout if it is '-')"},
    {"floatbv",
     NULL,
     "encode floating-point using the SMT floating-point theory (default)"},
    {"fixedbv", NULL, "Encode floating-point as fixed bit-vectors"},
    {"fp2bv",
     NULL,
     "encode floating-point as bit-vectors(default for solvers that don't "
     "support the SMT floating-point theory)"},
    {"tuple-node-flattener", NULL, "Encode tuples using our tuple to node API"},
    {"tuple-sym-flattener",
     NULL,
     "encode tuples using our tuple to symbol API"},
    {"array-flattener", NULL, "Encode arrays using our array API"},
    {"no-return-value-opt",
     NULL,
     "disable return value optimization to compute the stack size"}}},

  {"Incremental SMT",
   {{"smt-during-symex", NULL, "Enable incremental SMT solving"},
    {"smt-thread-guard",
     NULL,
     "check the thread guard during thread exploration"},
    {"smt-symex-guard",
     NULL,
     "check conditional goto statements during symbolic execution"},
    {"smt-symex-assert",
     NULL,
     "check assertion statements during symbolic execution"},
    {"smt-symex-assume",
     NULL,
     "check assume statements during symbolic execution"}}},
  {"Property checking",
   {{"multi-property",
     NULL,
     "verify satisfiability of all claims of the current bound"},
    {"no-standard-checks", NULL, "Disable default checks"},
    {"no-assertions", NULL, "Ignore assertions"},
    {"no-bounds-check", NULL, "Do not do array bounds check"},
    {"no-div-by-zero-check", NULL, "Do not do division by zero check"},
    {"no-pointer-check", NULL, "Do not do pointer check"},
    {"no-align-check", NULL, "Do not check pointer alignment"},
    {"no-unlimited-scanf-check",
     NULL,
     "do not do overflow check for scanf/fscanf with unlimited character "
     "width."},
    {"no-vla-size-check",
     NULL,
     "do not check whether the size of VLAs overflows the available address "
     "space"},
    {"no-abnormal-memory-leak",
     NULL,
     "affects --memory-leak-check; if both are enabled, the check for memory "
     "leaks is only performed for normal termination, that is, not for "
     "abort()"},
    {"no-reachable-memory-leak",
     NULL,
     "exclude still reachable objects from --memory-leak-check"},
    {"printf-check", NULL, "Enable pointer validation for printf arguments"},
    {"nan-check", NULL, "Check floating-point for NaN"},
    {"is-instance-check",
     NULL,
     "enable runtime isinstance assertions for annotated code"},
    {"memory-leak-check", NULL, "Enable memory leak check"},
    {"overflow-check", NULL, "Enable arithmetic over- and underflow check"},
    {"unsigned-overflow-check",
     NULL,
     "enable arithmetic over- and underflow check for unsigned integers"},
    {"ub-shift-check",
     NULL,
     "enable undefined behavior check on shift operations"},
    {"struct-fields-check",
     NULL,
     "enable over-sized read checks for struct fields"},
    {"deadlock-check",
     NULL,
     "enable global and local deadlock check with mutex"},
    {"data-races-check", NULL, "Enable data races check"},
    {"data-races-check-only",
     NULL,
     "enable data races check and only focus on race checks to reduce "
     "thread interleaving"},
    {"lock-order-check", NULL, "Enable for lock acquisition ordering check"},
    {"atomicity-check", NULL, "Enable atomicity check at visible assignments"},
    {"volatile-check", NULL, "Enable check for volatile variable"},
    {"stack-limit",
     boost::program_options::value<int>()->default_value(-1)->value_name(
       "bits"),
     "check if stack limit is respected"},
    {"error-label",
     boost::program_options::value<std::string>()->value_name("label"),
     "check if label is unreachable"},
    {"force-malloc-success", NULL, "Do not check for malloc/new failure"},
    {"force-realloc-success", NULL, "Do not check for realloc failure"},
    {"malloc-zero-is-null", NULL, "Force malloc(0) to return NULL"},
    {"max-symbolic-realloc-copy",
     boost::program_options::value<int>()->default_value(128)->value_name("nr"),
     "set maximum number of elements to copy symbolically in realloc (default "
     "is 128)"},
    {"enable-unreachability-intrinsic",
     NULL,
     "enable the functionality of the __ESBMC_unreachable() intrinsic, which "
     "results in a verification failure when its call is reachable"},
    {"conv-assert-to-assume",
     NULL,
     "convert assertions for bounds and pointer checks into assumptions"},
    {"unknown-method-args-check",
     NULL,
     "check pointer type arguments passed to the unknown function call"}}},
  {"k-induction",
   {{"base-case", NULL, "Check the base case"},
    {"forward-condition", NULL, "Check the forward condition"},
    {"inductive-step", NULL, "Check the inductive step"},
    {"k-induction", NULL, "Prove by k-induction "},
    {"goto-contractor",
     NULL,
     "enable contractor-based interval refinements on goto level on asserts"},
    {"goto-contractor-condition",
     NULL,
     "enable contractor-based interval refinements on goto level on "
     "conditions"},
    {"k-induction-parallel",
     NULL,
     "prove by k-induction, running each step on a separate process"},
    {"k-step",
     boost::program_options::value<int>()->default_value(1)->value_name("nr"),
     "set k increment (default is 1)"},
    {"max-k-step",
     boost::program_options::value<int>()->default_value(50)->value_name("nr"),
     "set max number of iteration (default is 50)"},
    {"base-k-step",
     boost::program_options::value<int>()->default_value(1)->value_name("nr"),
     "start the base case from n step (default is 1)"},
    {"show-cex",
     NULL,
     "print the counter-example produced by the inductive step"},
    {"cex-only", NULL, "Do not print the state trace"},
    {"bidirectional",
     NULL,
     "search the inductive step counterexample for assignments"},
    {"unlimited-k-steps", NULL, "Set max number of iteration to UINT_MAX"},
    {"max-inductive-step",
     boost::program_options::value<int>()->default_value(-1)->value_name("nr"),
     "set max k value for the inductive step"}}},
  {"Scheduling",
   {
     {"schedule", NULL, "Use schedule recording approach"},
   }},
  {"Concurrency checking",
   {{"context-bound",
     boost::program_options::value<int>()->default_value(-1)->value_name("nr"),
     "limit number of context switches for each thread"},
    {"state-hashing", NULL, "Enable state-hashing, prunes duplicate states"},
    {"no-goto-merge",
     NULL,
     "do not merge gotos when restoring paths after a context-switch"},
    {"no-por", NULL, "Do not do partial order reduction"},
    {"all-runs",
     NULL,
     "check all interleavings, even if a bug was already found"}}},
  {"Interval Analysis",
   {{"interval-analysis",
     NULL,
     "enable interval analysis for integer and float variables and add "
     "assumes to the "
     "program"},
    {"interval-analysis-dump",
     NULL,
     "dump resulting intervals for the analysis"},
    {"interval-analysis-csv-dump",
     boost::program_options::value<std::string>(),
     "dump resulting intervals for the analysis in a csv file"},
    {"interval-analysis-wrapped",
     NULL,
     "enable analysis using wrapped intervals (disables Integers)"},
    {"interval-analysis-arithmetic",
     NULL,
     "enable interval arithmetic for integer variables (Integers and "
     "Wrapped)"},
    {"interval-analysis-bitwise",
     NULL,
     "enable interval bitwise for integer variables (Integers and Wrapped"},
    {"interval-analysis-modular",
     NULL,
     "enable modular arithmetic for integer variables (Integers and Wrapped)"},
    {"interval-analysis-simplify",
     NULL,
     "enable assertion simplification during interval analysis (all)"},
    {"interval-analysis-no-contract",
     NULL,
     "disables use of contractors in abstract states (Integers, Reals)"},
    {"interval-analysis-assume-asserts",
     NULL,
     "propagates asserts as being assertions (Integers, Reals)"},
    {"interval-analysis-eval-assumptions",
     NULL,
     "evaluates assumptions/guards as boolean operators, accelerating the "
     "convergence (Integers, Reals)"},
    {"interval-analysis-ibex-contractor",
     NULL,
     "enable use of ibex contractors"},
    {"interval-analysis-extrapolate",
     NULL,
     "enables use of extrapolation in abstract states (all)"},
    {"interval-analysis-extrapolate-limit",
     boost::program_options::value<int>()->default_value(1)->value_name("nr"),
     "set limit for reaching a fixpoint (default is 1)"},
    {"interval-analysis-extrapolate-under-approximate",
     NULL,
     "assumes that Integers will not overflow (Integers)"},
    {"interval-analysis-narrowing",
     NULL,
     "enables use of narrowing in abstract states (Integers and Reals)"}}},
  {"Miscellaneous options",
   {{"memlimit",
     boost::program_options::value<std::string>()->value_name("limit"),
     "configure memory limit, of form \"100m\" or \"2g\"; without suffix the "
     "default unit is 'm'."},
    {"memstats", NULL, "Print memory usage statistics"},
    {"timeout",
     boost::program_options::value<std::string>()->value_name("t"),
     "configure time limit, integer followed by {s,m,h}"},
    {"enable-core-dump", NULL, "Do not disable core dump output"},
    {"no-simplify", NULL, "Do not simplify any expression"},
    {"no-propagation", NULL, "Disable constant propagation"},
    {"gcse",
     NULL,
     "adds intermediate variables to precompute common sub-expressions between "
     "assignments"},
    {"add-symex-value-sets",
     NULL,
     "enable value-set analysis for pointers and add assumes to the "
     "program"},
    {"segfault-handler", NULL, "Print stacktrace on segmentation fault"}}},
  {"Coverage options",
   {
     {"assertion-coverage", NULL, "Shows the coverage of assertion statements"},
     {"assertion-coverage-claims",
      NULL,
      "enable assertion-coverage and shows all reached claims"},
     {"condition-coverage",
      NULL,
      "this activates --multi-property, "
      "deactivates --keep-verified-claims, and "
      "shows the coverage of condition statements"},
     {"condition-coverage-claims",
      NULL,
      "enable condition-coverage and shows the instrumented claims"},
     {"condition-coverage-rm",
      NULL,
      "use '--condition-coverage' while disable "
      "'--no-remove-unreachable'"},
     {"condition-coverage-claims-rm",
      NULL,
      "use '--condition-coverage-claims' while disable "
      "'--no-remove-unreachable'"},
     {"no-cov-asserts", NULL, "Does not count the guard in the assertions"},
     {"cov-assume-asserts",
      NULL,
      "convert assertions to assumptions in coverage mode "
      "to preserve path constraints"},
     {"branch-coverage", NULL, "Shows the coverage of branch"},
     {"branch-coverage-claims",
      NULL,
      "enable branch-coverage and shows all reached claims"},
     {"branch-function-coverage",
      NULL,
      "shows the coverage of branch and function entry"},
     {"branch-function-coverage-claims",
      NULL,
      "enable branch-coverage-ext and shows all reached claims"},
     {"assign-param-nondet",
      NULL,
      "explicitly assign every function parameters to NONDET in function "
      "mode"},
     {"cov-report-json",
      NULL,
      "output coverage report as JSON file (cov-report.json)"},
   }},
  {"DEBUG options",
   {
     {"double-assign-check",
      NULL,
      "Check for duplicate SSA symbol assignments"},
     {"no-pointer-relation-check",
      NULL,
      "Do not check whether pointers in order relations refer to the same "
      "object (unsound)"},
     {"abort-on-recursion", NULL, "Abort if the program contains recursion"},
     {"ltl", NULL, "Enable Linear Temporal Logic property checking"},
     {"break-at",
      boost::program_options::value<std::string>(),
      "Trigger a breakpoint at the given GOTO instruction number"},
     {"direct-interleavings",
      NULL,
      "Use directed thread interleavings via intrinsics"},
     {"show-ileave-points",
      NULL,
      "Show instructions that access global variables and exit"},
     {"print-stack-traces",
      NULL,
      "Print all thread stack traces at each interleaving point"},
     {"interactive-ileaves",
      NULL,
      "Interactively choose thread scheduling at interleaving points"},
   }},
  {"end", {{"", NULL, "End of options"}}},
  {"Hidden Options",
   {{"depth", boost::program_options::value<int>(), "Instruction"},
    {"explain,h", NULL, ""}}}};
