#include <boost/program_options/value_semantic.hpp>
#include <esbmc/esbmc_parseoptions.h>
#include <fstream>
#include <limits>
#include <solvers/solver_config.h>
#include <util/cmdline.h>

const struct group_opt_templ all_cmd_options[] = {
  {"Main Usage",
   {{"input-file",
     boost::program_options::value<std::vector<std::string>>()->value_name(
       "file.c ..."),
     "Source file names"}}},
  {"Options",
   {{"help,?", NULL, "Show help"},
    {"function",
     boost::program_options::value<std::string>()->value_name("name"),
     "Set main function name"},
    {"class",
     boost::program_options::value<std::string>()->value_name("cname"),
     "Set the class/namespace name where the function is inside"},
    {"claim",
     boost::program_options::value<std::vector<int>>()->value_name("nr"),
     "Only check specific claims"},
    {"instruction",
     boost::program_options::value<int>()->value_name("nr"),
     "Limit the number of instructions executed during symbolic execution"},
    {"git-hash", NULL, "Show ESBMC version with git hash and exit"},
    {"version", NULL, "Show current ESBMC version and exit"},
    {"verbosity",
     boost::program_options::value<std::vector<std::string>>(),
     "Verbosity of log output, can be given multiple times. Parameter is "
     "either a decimal N or 'module:N' to set the log-level of debug messages "
     "of the module to N; without module, it sets the global log-level"}}},
  {"Printing options",
   {{"symbol-table-only", NULL, "Only show symbol table"},
    {"symbol-table-too", NULL, "Show symbol table and verify"},
    {"parse-tree-only", NULL, "Only show parse tree"},
    {"parse-tree-too", NULL, "Show parse tree and verify"},
    {"goto-functions-only", NULL, "Only show goto program"},
    {"goto-functions-too", NULL, "Show goto program and verify"},
    {"dump-goto-cfg",
     NULL,
     "Create a file for each function with the associated CFG in DOT format"},
    {"show-call-sites",
     NULL,
     "Show each function call site with its arguments"},
    {"program-only", NULL, "Only show program expression"},
    {"program-too", NULL, "Show program expression and verify"},
    {"ssa-symbol-table", NULL, "Show symbol table along with SSA"},
    {"ssa-guards", NULL, "Print guard expressions in SSA output"},
    {"ssa-sliced", NULL, "Print the sliced SSAs"},
    {"ssa-no-location", NULL, "Omit location info from SSA output"},
    {"smt-formula-only",
     NULL,
     "Only show SMT formula (not supported by all solvers)"},
    {"smt-formula-too",
     NULL,
     "Show SMT formula (not supported by all solvers), and verify"},
    {"smt-model",
     NULL,
     "Show SMT model (not supported by all solvers), if the formula is SAT"},
    {"color",
     boost::program_options::value<std::string>()
       ->default_value("auto")
       ->value_name("auto|always|never"),
     "Show colored output"},
    {"log-message",
     NULL,
     "Print LOG message including file, line, and timestamp"},
    {"keep-alive-interval",
     boost::program_options::value<int>()->value_name("interval"),
     "Set interval (in seconds) for keep alive messages (default: 60)"},
    {"enable-keep-alive",
     NULL,
     "Enable keep alive messages during long solving processes"}}},
  {"Trace",
   {{"quiet",
     NULL,
     "Do not print unwinding information during symbolic execution"},
    {"compact-trace",
     NULL,
     "Enable --no-slice and hide internal symbols from the trace"},
    {"symex-trace", NULL, "Print instructions during symbolic execution"},
    {"ssa-trace", NULL, "Print SSA during SMT encoding"},
    {"ssa-smt-trace", NULL, "Print generated SMT during SMT encoding"},
    {"ssa-features-dump",
     NULL,
     "Print features in the SSA (just before conversion)"},
    {"symex-ssa-trace", NULL, "Print generated SSA during symbolic execution"},
    {"show-goto-value-sets",
     NULL,
     "Show value-set analysis for the goto functions"},
    {"show-symex-value-sets",
     NULL,
     "Show value-set analysis during symbolic execution"},
    {"show-stacktrace",
     NULL,
     "Show the stack trace of function call in the counterexample"},
    {"simplify-trace",
     NULL,
     "Simplify the trace and exclude the assignments whose variables are not "
     "from user-input files"}}},
#ifdef ENABLE_PYTHON_FRONTEND
  {"Python frontend",
   {
     {"python",
      boost::program_options::value<std::string>()->value_name("path"),
      "Python interpreter binary to use (searched in $PATH; default: python)"},
     {"override-return-annotation",
      NULL,
      "Override return annotation with inferred type"},
     {"strict-types",
      NULL,
      "Enforce strict type checking for function arguments during "
      "verification"},
     {"nondet-str-length",
      boost::program_options::value<int>()->default_value(16)->value_name("nr"),
      "Set maximum length for non-deterministic strings (default is 16)"},
     {"python-list-compare-depth",
      boost::program_options::value<int>()->default_value(4)->value_name("nr"),
      "Set maximum nesting depth for Python list comparison (default is 4)"},
   }},
#endif
#ifdef ENABLE_SOLIDITY_FRONTEND
  {"Solidity frontend",
   {{"sol",
     boost::program_options::value<std::string>()->value_name("path"),
     "Solidity source file (.sol) — also accepted as a positional argument"},
    {"solc-bin",
     boost::program_options::value<std::string>()->value_name("path"),
     "path to solc binary (default: $SOLC or solc in $PATH)"},
    {"contract",
     boost::program_options::value<std::string>()->value_name("cname"),
     "Set contract name"},
    {"focus-function",
     boost::program_options::value<std::string>()->value_name("name"),
     "Restrict the contract harness to verify only the named public/external "
     "function. The constructor and state initialization still run (unlike "
     "--function), but the nondet dispatch loop calls only this function. "
     "Requires --contract when the source declares more than one contract."},
    {"no-visibility",
     NULL,
     "Force to verify every function, even if it's an unreachable "
     "internal/private function"},
    {"unbound", NULL, "Model external function calls as arbitrary behavior"},
    {"bound",
     NULL,
     "Model inter-contract function calls within a bounded system (default)"},
    {"reentry-check",
     NULL,
     "Detect reentrancy behavior during contract execution"},
    {"negating-property",
     boost::program_options::value<std::string>()->value_name("fname"),
     "Convert the assert(cond) to assert(!cond)"}}},
#endif
  {"Frontend",
   {{"include,I",
     boost::program_options::value<std::vector<std::string>>()->value_name(
       "path"),
     "Set include path"},
    {"include-file",
     boost::program_options::value<std::vector<std::string>>()->value_name(
       "file"),
     "Include files via frontend's -include option before anything else"},
    {"nostdinc", NULL, "Do not include from standard system paths"},
    {"idirafter",
     boost::program_options::value<std::vector<std::string>>()->value_name(
       "path"),
     "Append system include path to search after system headers"},
    {"define,D",
     boost::program_options::value<std::vector<std::string>>()->value_name(
       "macro"),
     "Define preprocessor macro"},
    {"warning,W",
     boost::program_options::value<std::vector<std::string>>(),
     "Enable specific frontend warnings, disable with \"no-\" prefix, or pass "
     "options directly to the C/C++ frontends with the form "
     "-Wc,OPT1,OPT2,..."},
    {"std",
     boost::program_options::value<std::string>()->value_name("version"),
     "Set C/C++ standard version"},
    {"sysroot",
     boost::program_options::value<std::string>()->value_name("<path>"),
     "Set the sysroot for the frontend"},
    {"no-abstracted-cpp-includes",
     NULL,
     "Do not include abstract C++ operational models"},
    {"force,f",
     boost::program_options::value<std::vector<std::string>>(),
     "Pass -f flags to the C/C++ frontend"},
    {"preprocess", NULL, "Stop after preprocessing"},
    {"no-inlining", NULL, "Disable inlining function calls"},
    {"full-inlining", NULL, "Perform full inlining of function calls"},
    {"all-claims", NULL, "Keep all claims"},
    {"keep-verified-claims",
     NULL,
     "Do not skip verified claims in multi-property verification"},
    {"show-loops", NULL, "Show the loops in the program"},
    {"show-claims", NULL, "Only show claims"},
    {"show-vcc", NULL, "Show the verification conditions"},
    {"document-subgoals", NULL, "Generate subgoals documentation"},
    {"no-library", NULL, "Disable built-in abstract C library"},
    {"no-string-literal", NULL, "Ignore string literals (replace with NULL)"},
    {"binary", NULL, "Read goto program instead of source code"},
    {"cprover", NULL, "Add compatibility layer for CPROVER gotos"},
    {"dont-care-about-missing-extensions",
     NULL,
     "Don't crash on unsupported extensions"},
    {"old-frontend",
     NULL,
     "Parse source files using the old frontend (deprecated)"},
    {"funsigned-char", NULL, "Make \"char\" unsigned by default"},
    {"fms-extensions", NULL, "Enable microsoft C extensions"},
    {"argv-max-args",
     boost::program_options::value<int>()->default_value(2)->value_name("nr"),
     "Maximum number of argv entries backed with nondet strings (default 2). "
     "Higher values widen coverage at the cost of a larger SMT formula."},
    {"argv-max-strlen",
     boost::program_options::value<int>()->default_value(256)->value_name("nr"),
     "Maximum length (in bytes, including the null terminator) of each backed "
     "argv string (default 256)."},
    {"gcc-nested-functions",
     NULL,
     "Enable GCC nested functions extension (source-level lambda lifting)"}}},
  {"Architecture",
   {
     {"no-arch", NULL, "Don't set up an architecture"},
     {"little-endian", NULL, "Allow little-endian word-byte conversions"},
     {"big-endian", NULL, "Allow big-endian word-byte conversions"},
     {"16", NULL, "Set width of machine word (default is 64)"},
     {"32", NULL, "Set width of machine word (default is 64)"},
     {"64", NULL, "Set width of machine word (default is 64)"},
     {"cheri",
      boost::program_options::value<std::string>()->value_name("mode"),
      "Enable CHERI-C in 'hybrid' or 'purecap' mode (default is off)"},
     {"cheri-uncompressed",
      NULL,
      "Use full CHERI capabilities instead of the compressed format"},
#ifdef _WIN32
     {"i386-macos", NULL, "Set MACOS/I386 architecture"},
     {"ppc-macos", NULL, "Set PPC/I386 architecture"},
     {"i386-linux", NULL, "Set Linux/I386 architecture"},
     {"i386-win32", NULL, "Set Windows/I386 architecture (default)"},
#elif __APPLE__
     {"i386-macos", NULL, "Set MACOS/I386 architecture (default)"},
     {"ppc-macos", NULL, "Set PPC/I386 architecture"},
     {"i386-linux", NULL, "Set Linux/I386 architecture"},
     {"i386-win32", NULL, "Set Windows/I386 architecture"},
#else
     {"i386-macos", NULL, "Set MACOS/I386 architecture"},
     {"ppc-macos", NULL, "Set PPC/I386 architecture"},
     {"i386-linux", NULL, "Set Linux/I386 architecture (default)"},
     {"i386-win32", NULL, "Set Windows/I386 architecture"},
#endif
   }},
  {"Witness",
   {{"witness-output",
     boost::program_options::value<std::string>()->value_name("path"),
     "Generate the verification result witness in both Yaml and GraphML "
     "format"},
    {"sarif-output",
     boost::program_options::value<std::string>()->value_name("{ path | - }"),
     "Generate a SARIF 2.1.0 report of the violation; use '-' for stdout. "
     "Each result is annotated with the matching CWE ids (CWE 4.20)."},
    {"witness-output-graphml",
     boost::program_options::value<std::string>()->value_name("{ path | - }"),
     "Generate the verification result witness in GraphML format; use '-' for "
     "output to stdout"},
    {"witness-output-yaml",
     boost::program_options::value<std::string>()->value_name("{ path | - }"),
     "Generate the verification result witness in Yaml format; use '-' for "
     "output to stdout"},
    {"witness-producer",
     boost::program_options::value<std::string>(),
     "Override the producer name in witness files"},
    {"witness-programfile",
     boost::program_options::value<std::string>(),
     "Override the program file name in witness files"},
    {"validate-correctness-witness",
     NULL,
     "Validate the YAML correctness witness (2.0)"},
    {"validate-violation-witness",
     NULL,
     "Validate the YAML violation witness (2.0)"},
    {"witness",
     boost::program_options::value<std::string>()->value_name("<path>"),
     "Set the witness path"},
    {"all-witnesses",
     NULL,
     "After a property fails, enumerate further input vectors that also "
     "violate it (until UNSAT or --max-witnesses is reached). "
     "Implies --multi-property."},
    {"max-witnesses",
     boost::program_options::value<int>()->default_value(16)->value_name("n"),
     "Cap the number of witnesses reported per property "
     "(default: 16; 0 = unlimited). Only meaningful with --all-witnesses."}}},
  {"Output",
   {{"output-goto",
     boost::program_options::value<std::string>(),
     "Export generated goto program"},
    {"cex-output",
     boost::program_options::value<std::string>(),
     "Save the counterexample into a file or, "
     "in multi-property mode, multiple files with name prefix 'N-' "
     "where 'N' is a decimal increasing from zero"},
    {"file-output",
     boost::program_options::value<std::string>(),
     "Redirect all output to a file (no stdout/stderr)"},
    {"goto2c", NULL, "Translate the GOTO program to C"},
    {"generate-testcase",
     NULL,
     "If a solution is found, generates a testcase in XML"},
    {"generate-pytest-testcase",
     NULL,
     "If a solution is found, generates a pytest testcase for Python programs"},
    {"generate-ctest-testcase",
     NULL,
     "If a solution is found, generates CTest testcases for C programs"},
    {"generate-html-report",
     NULL,
     "If a violation is found, generates a HTML report"},
    {"generate-json-report",
     NULL,
     "If a violation is found, generates a JSON report"},
    {"result-only", NULL, "Do not print the counter-example"}}},
  {"Function Contracts",
   {{"enforce-contract",
     boost::program_options::value<std::vector<std::string>>()->value_name(
       "fun"),
     "Wrap function to check its contract (use \"*\" for all functions)"},
    {"replace-call-with-contract",
     boost::program_options::value<std::vector<std::string>>()->value_name(
       "fun"),
     "Replace function calls with contract semantics (use \"*\" for all "
     "functions)"},
    {"enforce-all-contracts",
     nullptr,
     "Enforce contracts for all functions marked with __ESBMC_contract"},
    {"replace-all-contracts",
     nullptr,
     "Replace calls to all functions marked with __ESBMC_contract"}}},
  {"BMC",
   {{"unwind",
     boost::program_options::value<int>()->value_name("nr"),
     "Unwind nr times"},
    {"unwindset",
     boost::program_options::value<std::string>()->value_name("L:nr,..."),
     "Unwind loop L with nr times (use --show-loops to get the loops info)"},
    {"unwindsetname",
     boost::program_options::value<std::string>()->value_name(
       "name:idx:nr,..."),
     "Unwind loop idx (0-indexed) in function name with nr times.\n"
     "\tSyntax: func, N@ns@func, S@Class@method, file.c@func,\n"
     "\t        N@ns@S@Class@method, file.c@N@ns@S@Class@method\n"
     "\tAlso accepts Clang USR format (e.g., c:@F@func# or c:file.c@F@func#)\n"
     "\tExample: --unwindsetname compute:0:10,N@math@sum:1:5\n"
     "\tUse --show-loops to see available functions and loop indices"},
    {"no-unwinding-assertions", NULL, "Do not generate unwinding assertions"},
    {"no-remove-unreachable",
     NULL,
     "Disable the removal of unreachable code in GOTO programs"},
    {"no-remove-no-op",
     NULL,
     "Disable the removal of NO-OP instructions in GOTO programs"},
    {"partial-loops", NULL, "Permit paths with partial loops"},
    {"no-slice", NULL, "Do not remove unused equations"},
    {"multi-fail-fast",
     boost::program_options::value<int>()->value_name("n"),
     "Stop after first n VCC violations in multi-property mode"},
    {"no-slice-name",
     boost::program_options::value<std::vector<std::string>>()->value_name(
       "name"),
     "Disable slicing for all symbols generated with the given name"},
    {"no-slice-id",
     boost::program_options::value<std::vector<std::string>>()->value_name(
       "id"),
     "Disable slicing for the symbol with the given id"},
    {"goto-unwind", NULL, "Unroll bounded loops at goto level"},
    {"unlimited-goto-unwind",
     NULL,
     "Do not unroll bounded loops at goto level (need to enable "
     "--goto-unwind)"},
    {"slice-assumes", NULL, "Remove unused assume statements"},
    {"extended-try-analysis",
     NULL,
     "Skip backward stack search for C++ throw targets"},
    {"skip-bmc", NULL, "Do not perform bounded model checking"},
    {"no-cache-asserts",
     NULL,
     "Do not cache asserts that were already proven correct"}}},
  {"Incremental BMC",
   {{"incremental-bmc", NULL, "Incremental loop unwinding verification"},
    {"falsification", NULL, "Incremental loop unwinding for bug searching"},
    {"termination",
     NULL,
     "Incremental loop unwinding assertion verification"}}},
  {"k-induction",
   {{"base-case", NULL, "Check the base case"},
    {"forward-condition", NULL, "Check the forward condition"},
    {"inductive-step", NULL, "Check the inductive step"},
    {"k-induction", NULL, "Prove by k-induction"},
    {"goto-contractor",
     NULL,
     "Enable contractor-based interval refinements on goto level on asserts"},
    {"goto-contractor-condition",
     NULL,
     "Enable contractor-based interval refinements on goto level on "
     "conditions"},
    {"k-induction-parallel",
     NULL,
     "Prove by k-induction, running each step on a separate process"},
    {"k-step",
     boost::program_options::value<int>()->default_value(1)->value_name("nr"),
     "Set k increment (default is 1)"},
    {"max-k-step",
     boost::program_options::value<int>()->default_value(50)->value_name("nr"),
     "Set max number of iteration (default is 50)"},
    {"base-k-step",
     boost::program_options::value<int>()->default_value(1)->value_name("nr"),
     "Start the base case from n step (default is 1)"},
    {"show-cex",
     NULL,
     "Print the counter-example produced by the inductive step"},
    {"cex-only", NULL, "Do not print the state trace"},
    {"bidirectional",
     NULL,
     "Search the inductive step counterexample for assignments"},
    {"unlimited-k-steps", NULL, "Set max number of iteration to UINT_MAX"},
    {"max-inductive-step",
     boost::program_options::value<int>()->default_value(-1)->value_name("nr"),
     "Set max k value for the inductive step"},
    {"loop-invariant",
     NULL,
     "Verify using loop invariant + k-induction (combined mode)"},
    {"loop-invariant-check",
     NULL,
     "Verify using loop invariant inductive check (standalone mode)"},
    {"loop-frame-rule",
     NULL,
     "Enable frame rule for loop invariant checking "
     "(snapshot-havoc-assume pattern, requires --loop-invariant-check)"}}},
  {"Concurrency and Scheduling",
   {{"schedule", NULL, "Use schedule recording approach"},
    {"context-bound",
     boost::program_options::value<int>()->default_value(-1)->value_name("nr"),
     "Limit number of context switches for each thread"},
    {"state-hashing", NULL, "Enable state-hashing, prunes duplicate states"},
    {"no-goto-merge",
     NULL,
     "Do not merge gotos when restoring paths after a context-switch"},
    {"no-por", NULL, "Do not do partial order reduction"},
    {"all-runs",
     NULL,
     "Check all interleavings, even if a bug was already found"}}},
  {"Solver",
   {{"list-solvers", NULL, "List available solvers and exit"},
    {"boolector", NULL, "Use Boolector"},
    {"z3", NULL, "Use Z3"},
    {"z3-debug", NULL, "Extracts Z3 dump and SMT2 formula"},
    {"z3-debug-dump-file",
     boost::program_options::value<std::string>()->value_name("z3.log"),
     "Name for Z3 dump file"},
    {"z3-debug-smt-file",
     boost::program_options::value<std::string>()->value_name("log.smt2"),
     "Name for Z3 smt2 file"},
    {"mathsat", NULL, "Use MathSAT"},
    {"cvc", NULL, "Alias for --cvc4; this may change in the future to --cvc5"},
    {"cvc4", NULL, "Use CVC4"},
    {"cvc5", NULL, "Use CVC5"},
    {"yices", NULL, "Use Yices"},
    {"bitwuzla", NULL, "Use Bitwuzla (default)"},
    {"bv", NULL, "Use solver with bit-vector arithmetic"},
    {"ir",
     NULL,
     "Use solver with integer/real arithmetic. Integer/real have an unbounded "
     "range, overapproximating normal integers/reals while significantly "
     "boosting performance"},
    {"ir-ieee",
     NULL,
     "Use integer/real arithmetic with real-arithmetic enclosure constraints "
     "for floating-point operations"},
    {"parallel-solving",
     NULL,
     "Solve each VCC in parallel (this activates --multi-property)"},
    {"smtlib", NULL, "Use SMT lib format"},
    {"default-solver",
     boost::program_options::value<std::string>()->value_name("<solver>"),
     "Override default solver used if no concrete one is specified"},
    {"non-supported-models-as-zero",
     NULL,
     "If ESBMC can't extract a type/expression from the solver, then the value "
     "will be set to zero"},
    {"smtlib-solver-prog",

     boost::program_options::value<std::string>(),
     "Path to the SMT-LIB solver executable"},
    {"output",
     boost::program_options::value<std::string>()->value_name("<filename>"),
     "Output VCCs in SMT lib format to given file (or stdout if it is '-')"},
    {"floatbv",
     NULL,
     "Encode floating-point using the SMT floating-point theory (default)"},
    {"fixedbv", NULL, "Encode floating-point as fixed bit-vectors"},
    {"fp2bv",
     NULL,
     "Encode floating-point as bit-vectors (default for solvers that don't "
     "support the SMT floating-point theory)"},
    {"tuple-node-flattener", NULL, "Encode tuples using our tuple to node API"},
    {"tuple-sym-flattener",
     NULL,
     "Encode tuples using our tuple to symbol API"},
    {"array-flattener", NULL, "Encode arrays using our array API"},
    {"no-return-value-opt",
     NULL,
     "Disable return value optimization to compute the stack size"}}},

  {"Incremental SMT",
   {{"smt-during-symex", NULL, "Enable incremental SMT solving"},
    {"smt-thread-guard",
     NULL,
     "Check the thread guard during thread exploration"},
    {"smt-symex-guard",
     NULL,
     "Check conditional goto statements during symbolic execution"},
    {"smt-symex-assert",
     NULL,
     "Check assertion statements during symbolic execution"},
    {"smt-symex-assume",
     NULL,
     "Check assume statements during symbolic execution"}}},
  {"Property checking",
   {{"multi-property",
     NULL,
     "Verify satisfiability of all claims of the current bound"},
    {"no-standard-checks", NULL, "Disable default checks"},
    {"no-assertions", NULL, "Ignore assertions"},
    {"no-bounds-check", NULL, "Do not do array bounds check"},
    {"no-div-by-zero-check", NULL, "Do not do division by zero check"},
    {"no-pointer-check", NULL, "Do not do pointer check"},
    {"no-align-check", NULL, "Do not check pointer alignment"},
    {"no-unlimited-scanf-check",
     NULL,
     "Do not do overflow check for scanf/fscanf with unlimited character "
     "width"},
    {"no-vla-size-check",
     NULL,
     "Do not check whether the size of VLAs overflows the available address "
     "space"},
    {"no-abnormal-memory-leak",
     NULL,
     "Affects --memory-leak-check; if both are enabled, the check for memory "
     "leaks is only performed for normal termination, that is, not for "
     "abort()"},
    {"no-reachable-memory-leak",
     NULL,
     "Exclude still reachable objects from --memory-leak-check"},
    {"printf-check", NULL, "Enable pointer validation for printf arguments"},
    {"nan-check", NULL, "Check floating-point for NaN"},
    {"is-instance-check",
     NULL,
     "Enable runtime isinstance assertions for annotated code"},
    {"memory-leak-check", NULL, "Enable memory leak check"},
    {"overflow-check", NULL, "Enable arithmetic over- and underflow check"},
    {"unsigned-overflow-check",
     NULL,
     "Enable arithmetic over- and underflow check for unsigned integers"},
    {"ub-shift-check",
     NULL,
     "Enable undefined behavior check on shift operations"},
    {"struct-fields-check",
     NULL,
     "Enable over-sized read checks for struct fields"},
    {"deadlock-check",
     NULL,
     "Enable global and local deadlock check with mutex"},
    {"data-races-check", NULL, "Enable data races check"},
    {"data-races-check-only",
     NULL,
     "Enable data races check and only focus on race checks to reduce "
     "thread interleaving"},
    {"lock-order-check", NULL, "Enable for lock acquisition ordering check"},
    {"atomicity-check", NULL, "Enable atomicity check at visible assignments"},
    {"uninitialised-vars-check",
     NULL,
     "Enable check for reads of uninitialised local variables (CWE-457)"},
    {"volatile-check", NULL, "Enable check for volatile variable"},
    {"stack-limit",
     boost::program_options::value<int>()->default_value(-1)->value_name(
       "bits"),
     "Check if stack limit is respected"},
    {"error-label",
     boost::program_options::value<std::string>()->value_name("label"),
     "Check if label is unreachable"},
    {"force-malloc-success", NULL, "Do not check for malloc/new failure"},
    {"force-realloc-success", NULL, "Do not check for realloc failure"},
    {"malloc-zero-is-null", NULL, "Force malloc(0) to return NULL"},
    {"max-symbolic-realloc-copy",
     boost::program_options::value<int>()->default_value(128)->value_name("nr"),
     "Set maximum number of elements to copy symbolically in realloc (default "
     "is 128)"},
    {"enable-unreachability-intrinsic",
     NULL,
     "Enable the functionality of the __ESBMC_unreachable() intrinsic, which "
     "results in a verification failure when its call is reachable"},
    {"conv-assert-to-assume",
     NULL,
     "Convert assertions for bounds and pointer checks into assumptions"},
    {"unknown-method-args-check",
     NULL,
     "Check pointer type arguments passed to the unknown function call"}}},
  {"Interval Analysis",
   {{"interval-analysis",
     NULL,
     "Enable interval analysis for integer and float variables and add "
     "assumes to the "
     "program"},
    {"interval-analysis-dump",
     NULL,
     "Dump resulting intervals for the analysis"},
    {"interval-analysis-csv-dump",
     boost::program_options::value<std::string>(),
     "Dump resulting intervals for the analysis in a csv file"},
    {"interval-analysis-wrapped",
     NULL,
     "Enable analysis using wrapped intervals (disables Integers)"},
    {"interval-analysis-arithmetic",
     NULL,
     "Enable interval arithmetic for integer variables (Integers and "
     "Wrapped)"},
    {"interval-analysis-bitwise",
     NULL,
     "Enable interval bitwise for integer variables (Integers and Wrapped)"},
    {"interval-analysis-modular",
     NULL,
     "Enable modular arithmetic for integer variables (Integers and Wrapped)"},
    {"interval-analysis-simplify",
     NULL,
     "Enable assertion simplification during interval analysis (all)"},
    {"interval-analysis-no-contract",
     NULL,
     "Disable use of contractors in abstract states (Integers, Reals)"},
    {"interval-analysis-assume-asserts",
     NULL,
     "Propagate assertions as invariants during interval analysis (Integers, "
     "Reals)"},
    {"interval-analysis-eval-assumptions",
     NULL,
     "Evaluate assumptions and guards as boolean operators to accelerate "
     "convergence (Integers, Reals)"},
    {"interval-analysis-ibex-contractor",
     NULL,
     "Enable use of ibex contractors"},
    {"interval-analysis-extrapolate",
     NULL,
     "Enable extrapolation in abstract states (all)"},
    {"interval-analysis-extrapolate-limit",
     boost::program_options::value<int>()->default_value(1)->value_name("nr"),
     "Set limit for reaching a fixpoint (default is 1)"},
    {"interval-analysis-extrapolate-under-approximate",
     NULL,
     "Assume integers will not overflow (Integers)"},
    {"interval-analysis-narrowing",
     NULL,
     "Enable narrowing in abstract states (Integers and Reals)"},
    {"no-interval-symex-guard",
     NULL,
     "Disable interval-based guard pruning during symbolic execution (enabled "
     "by default)"},
    {"interval-symex-assert",
     NULL,
     "Use interval-based assertion pruning during symbolic execution to "
     "skip assertions that are provably true under the tracked intervals"}}},
  {"Coverage options",
   {
     {"assertion-coverage", NULL, "Show the coverage of assertion statements"},
     {"assertion-coverage-claims",
      NULL,
      "Enable assertion-coverage and shows all reached claims"},
     {"condition-coverage",
      NULL,
      "This activates --multi-property, "
      "deactivates --keep-verified-claims, and "
      "shows the coverage of condition statements"},
     {"condition-coverage-claims",
      NULL,
      "Enable condition-coverage and shows the instrumented claims"},
     {"condition-coverage-rm",
      NULL,
      "Use '--condition-coverage' while disable "
      "'--no-remove-unreachable'"},
     {"condition-coverage-claims-rm",
      NULL,
      "Use '--condition-coverage-claims' while disable "
      "'--no-remove-unreachable'"},
     {"no-cov-asserts", NULL, "Do not count the guard in the assertions"},
     {"cov-assume-asserts",
      NULL,
      "Convert assertions to assumptions in coverage mode "
      "to preserve path constraints"},
     {"branch-coverage", NULL, "Show the coverage of branches"},
     {"branch-coverage-claims",
      NULL,
      "Enable branch-coverage and shows all reached claims"},
     {"branch-function-coverage",
      NULL,
      "Show the coverage of branches and function entry"},
     {"branch-function-coverage-claims",
      NULL,
      "Enable branch-coverage-ext and shows all reached claims"},
     {"k-path-coverage",
      // INT_MIN is the implicit_value sentinel for "no =N supplied".
      // -1 / 0 are explicit user inputs and rejected at parse time;
      // INT_MIN is unambiguous since no user would ever type it.
      boost::program_options::value<int>()
        ->implicit_value(std::numeric_limits<int>::min())
        ->value_name("N"),
      "Show the coverage of k-path witnesses (PathCrawler-style; "
      "Williams et al., EDCC 2005). N is the prefix depth (1..30); if "
      "omitted, tied to --unwind, falling back to 4 when --unwind is unset"},
     {"k-path-coverage-claims",
      NULL,
      "Enable --k-path-coverage with default N (use --k-path-coverage=N "
      "directly to override) and show all reached claims"},
     {"k-path-witness-depth",
      boost::program_options::value<int>()->default_value(8)->value_name("D"),
      "Cap on post-simplification witness expression depth in --k-path-"
      "coverage; deeper witnesses are dropped (default 8)"},
     {"k-path-max-goals",
      boost::program_options::value<int>()->default_value(10000)->value_name(
        "M"),
      "Per-function goal cap for --k-path-coverage; on overflow the "
      "instrumentation aborts rather than truncating (default 10000)"},
     {"assign-param-nondet",
      NULL,
      "Explicitly assign every function parameters to NONDET in function "
      "mode"},
     {"cov-report-json",
      NULL,
      "Output coverage report as JSON file (cov-report.json)"},
   }},
  {"Miscellaneous options",
   {{"memlimit",
     boost::program_options::value<std::string>()->value_name("limit"),
     "Configure memory limit, of form \"100m\" or \"2g\"; without suffix the "
     "default unit is 'm'"},
    {"memstats", NULL, "Print memory usage statistics"},
    {"timeout",
     boost::program_options::value<std::string>()->value_name("t"),
     "Configure time limit, integer followed by {s,m,h}"},
    {"enable-core-dump", NULL, "Do not disable core dump output"},
    {"no-simplify", NULL, "Do not simplify any expression"},
    {"no-propagation", NULL, "Disable constant propagation"},
    {"gcse",
     NULL,
     "Adds intermediate variables to precompute common sub-expressions between "
     "assignments"},
    {"add-symex-value-sets",
     NULL,
     "Enable value-set analysis for pointers and add assumes to the "
     "program"},
    {"segfault-handler", NULL, "Print stacktrace on segmentation fault"}}},
  {"DEBUG options",
   {
     {"double-assign-check",
      NULL,
      "Check for duplicate SSA symbol assignments"},
     {"no-pointer-relation-check",
      NULL,
      "Do not check whether pointers in order relations refer to the same "
      "object (unsound)"},
     {"abort-on-recursion", NULL, "Abort if the program contains recursion"},
     {"ltl", NULL, "Enable Linear Temporal Logic property checking"},
     {"break-at",
      boost::program_options::value<std::string>(),
      "Trigger a breakpoint at the given GOTO instruction number"},
     {"direct-interleavings",
      NULL,
      "Use directed thread interleavings via intrinsics"},
     {"show-ileave-points",
      NULL,
      "Show instructions that access global variables and exit"},
     {"print-stack-traces",
      NULL,
      "Print all thread stack traces at each interleaving point"},
     {"interactive-ileaves",
      NULL,
      "Interactively choose thread scheduling at interleaving points"},
   }},
  {"end", {{"", NULL, "End of options"}}},
  {"Hidden Options",
   {{"depth", boost::program_options::value<int>(), "Instruction"},
    {"explain,h", NULL, ""}}}};
