// Auto-generated harness for: strncmp
// Source: src/c2goto/library/string.c:173
// Generated by Byte Repair Contractor

#include <stddef.h>

extern int strncmp(const char *s1, const char *s2, size_t n);

void __byterepair_harness_main(void) {
    // --- Symbolic inputs ---
    char a[8], b[8];
    const char *s1 = (const char *)a;
    const char *s2 = (const char *)b;
    size_t n = nondet_uint();
    __ESBMC_assume(n <= 8);

    // --- Call under test ---
    int result = strncmp(s1, s2, n);

    // --- Postcondition assertions ---
    __ESBMC_assert(result == 0 || result == 1 || result == -1,
        "system property: strncmp returns -1, 0, or 1");
}
