# Auto-generated by ESBMC 8.0.0
# Original file: test.py


from test import *
import pytest

@pytest.mark.parametrize("dict0", [
    {0: 0},
    {1375: 1375},
    {0: 0},
    {0: 0},
])
def test_sum_of_positive_elements(dict0):
    """Auto-generated test cases for sum_of_positive_elements"""
    sum_of_positive_elements(dict0)

