# Auto-generated by ESBMC 8.0.0
# Original file: test.py


from test import *
import pytest

@pytest.mark.parametrize("dict0", [
    {144115188075855873: 144115188075855873},
])
def test_sum_of_positive_elements(dict0):
    """Auto-generated test cases for sum_of_positive_elements"""
    sum_of_positive_elements(dict0)

