// Auto-generated harness for: strlen
// Source: src/c2goto/library/string.c:88
// Generated by Byte Repair Contractor

#include <stddef.h>

extern size_t strlen(const char *s);

void __byterepair_harness_main(void) {
    // --- Symbolic inputs ---
    char buf[8];
    // Force a null terminator within the buffer so strlen terminates within
    // the BMC bound. The contract requires the string to be null-terminated
    // somewhere in the underlying object.
    buf[7] = '\0';
    const char *s = (const char *)buf;

    // --- Call under test ---
    size_t result = strlen(s);

    // --- Postcondition assertions ---
    __ESBMC_assert(result <= 7, "system property: strlen result <= buffer-1");
    __ESBMC_assert(s[result] == '\0',
        "system property: s[result] is the null terminator");
    size_t k = nondet_uint();
    __ESBMC_assume(k < result);
    __ESBMC_assert(s[k] != '\0',
        "system property: no '\\0' before result");
}
