/*******************************************************************\

Module: Symbolic Execution of ANSI-C

Author: Daniel Kroening, kroening@kroening.com

\*******************************************************************/

#include <fstream>

#include <solvers/cvc/cvc_dec.h>

#include "version.h"
#include "bmc.h"

/*******************************************************************\

Function: bmc_baset::cvc

  Inputs:

 Outputs:

 Purpose:

\*******************************************************************/

bool bmc_baset::cvc()
{
  const std::string &filename=options.get_option("outfile");

  if(filename=="")
  {
    cvc_dect cvc_dec;
    return run_decision_procedure(cvc_dec);
  }
  else if(filename=="-")
    return cvc_conv(std::cout);
  else
  {
    std::ofstream out(filename.c_str());
    if(!out)
    {
      std::cerr << "failed to open " << filename << std::endl;
      return false;
    }

    return cvc_conv(out);
  }
}

/*******************************************************************\

Function: bmc_baset::cvc_conv

  Inputs:

 Outputs:

 Purpose:

\*******************************************************************/

bool bmc_baset::cvc_conv(std::ostream &out)
{
  out << "%%%\n";
  out << "%%% Generated by ESBMC " << ESBMC_VERSION << "\n";
  out << "%%%\n\n";

  cvc_convt cvc_conv(out);
  cvc_conv.set_message_handler(message_handler);

  do_unwind_module(cvc_conv);
  do_cbmc(cvc_conv);

  cvc_conv.dec_solve();

  return false;
}
