#!/bin/bash

make
strip cbmc.exe

VERSION=`./cbmc.exe --version`
VERSION_FILE=`echo $VERSION | sed "y/./-/"`

echo $VERSION_FILE

cd ../hw-cbmc
make
strip hw-cbmc.exe

mkdir /tmp/cbmc-dist
cp hw-cbmc.exe ../cbmc/cbmc.exe /tmp/cbmc-dist/
cp ../../LICENSE /tmp/cbmc-dist/
cd /tmp/cbmc-dist
zip -9 cbmc-${VERSION_FILE}-win.zip hw-cbmc.exe cbmc.exe LICENSE

echo Copying.
scp cbmc-${VERSION_FILE}-win.zip kroening@dkr1.inf.ethz.ch:/www/cprover.org/cbmc/download/

cd /tmp
rm -R /tmp/cbmc-dist
