/* Generated by scripts/rv2c.py from snep.h -- do not edit.
 *
 * Linux RV monitor 'snep', as an ESBMC-checkable specification.
 * The obligation is the one in include/rv/da_monitor.h: an event that
 * has no transition from the current state drives the automaton to
 * INVALID_STATE, and the monitor reacts. Here that is an assertion.
 *
 * This file is the SPECIFICATION. Supply an implementation that calls
 * rv_snep_event() and prove it never trips the assertion; driving
 * it with unconstrained events reaches INVALID_STATE at once and
 * establishes nothing.
 */
#ifndef RV_SPEC_SNEP_H
#define RV_SPEC_SNEP_H

#include <assert.h>

enum rv_snep_state { non_scheduling_context_snep, scheduling_contex_snep, RV_SNEP_INVALID };
enum rv_snep_event { preempt_disable_snep, preempt_enable_snep, schedule_entry_snep, schedule_exit_snep };

#define RV_SNEP_STATES 2
#define RV_SNEP_EVENTS 4

static const unsigned char rv_snep_function[2][4] = {
  /* non_scheduling_context_snep  */ { non_scheduling_context_snep, non_scheduling_context_snep, scheduling_contex_snep, RV_SNEP_INVALID },
  /* scheduling_contex_snep       */ { RV_SNEP_INVALID, RV_SNEP_INVALID, RV_SNEP_INVALID, non_scheduling_context_snep },
};

static enum rv_snep_state rv_snep_cur = non_scheduling_context_snep;

static void rv_snep_reset(void) { rv_snep_cur = non_scheduling_context_snep; }

/* Feed one event. Trips the RV obligation if the automaton rejects it. */
static void rv_snep_event(enum rv_snep_event ev)
{
  assert(rv_snep_cur < RV_SNEP_STATES);
  assert((unsigned)ev < RV_SNEP_EVENTS);
  enum rv_snep_state next =
    (enum rv_snep_state)rv_snep_function[rv_snep_cur][ev];
  /* include/rv/da_monitor.h:690 -- the monitor's whole obligation. */
  assert(next != RV_SNEP_INVALID);
  rv_snep_cur = next;
}

#endif