# Auto-generated by ESBMC 7.11.0
# Original file: main.py
# Generated: 2025-Dec-29 20:08:38.424354

from main import *
import pytest

@pytest.mark.parametrize("score", [
    15,
    65,
    61,
    73,
    63,
    84,
    57,
    100,
    28,
    -35184372088748,
])
def test_grade(score):
    """Auto-generated test cases for grade"""
    grade(score)

