// Auto-generated harness for: strcpy
// Source: src/c2goto/library/string.c:27
// Generated by Byte Repair Contractor

#include <stddef.h>

extern char *strcpy(char *dst, const char *src);

void __byterepair_harness_main(void) {
    // --- Symbolic inputs ---
    char dbuf[8], sbuf[8];
    sbuf[7] = '\0';
    char *dst = dbuf;
    const char *src = (const char *)sbuf;

    // --- Call under test ---
    char *result = strcpy(dst, src);

    // --- Postcondition assertions ---
    __ESBMC_assert(result == dst, "system property: strcpy returns dst");
}
