#include <goto2c/goto2c.h>
#include <goto2c/expr2c.h>
#include <irep2/irep2_utils.h>

#include <map>
#include <unordered_map>
#include <util/expr/expr_util.h>
#include <util/lang/c_sizeof.h>
#include <util/config/config.h>

// This translates the given GOTO program (aka list of GOTO functions)
std::string goto2ct::translate()
{
  std::ostringstream out;

  // Banner
  out << "///////////////////////////////////////////////////////\n";
  out << "//\n";
  out << "// This program is generated by the GOTO2C translator\n";
  out << "//\n";
  out << "///////////////////////////////////////////////////////\n";
  out << "\n\n\n";

  // Includes
  out << "///////////////////   HEADERS   ///////////////////////\n";
  out << "#include <esbmc_intrinsics.h> // included automatically\n";
  out << "\n\n";

  // Types
  out << "/////////////////////   GLOBAL TYPES  ////////////////////////\n";
  for (auto type : global_types)
    out << typedef2c(type, ns) << "; // " << type.location() << "\n";
  out << "\n\n";

  // External variables
  out << "/////////////////  EXTERNAL VARIABLES   ////////////////////\n";
  for (auto s : extern_vars)
    out << expr2c(code_declt(symbol_expr(s)), ns) << "; // " << s.location
        << "\n";
  out << "\n\n";

  // Function declarations
  out << "/////////////////  FUNCTION DECLARATIONS   ////////////////////\n";
  for (auto s : fun_decls)
    out << expr2c(code_declt(symbol_expr(s)), ns) << "; // " << s.location
        << "\n";
  out << "\n\n";

  // Global variables declarations
  out << "//////////////// GLOBAL VARIABLE DECLARATIONS ///////////////////\n";
  for (auto s : global_vars)
    out << expr2c(code_declt(symbol_expr(s)), ns) << "; // " << s.location
        << "\n";
  out << "\n\n";

  // Global variables definitions
  out << "//////////////// GLOBAL VARIABLE DEFINITIONS ///////////////////\n";
  for (auto s : global_vars)
  {
    if (initializers.count(s.id.as_string()) > 0)
    {
      out << expr2c(
               code_declt(symbol_expr(s), initializers[s.id.as_string()]), ns)
          << "; // " << s.location << "\n";
    }
  }
  out << "\n\n";

  // Function definitions
  out << "/////////////////   FUNCTION DEFINITIONS   ////////////////////\n";
  out << translate(goto_functions) << "\n";

  out << "////////////////////// PROGRAM END /////////////////////////////\n";
  return out.str();
}

// Convert GOTO functions (without the context) to C
std::string goto2ct::translate(goto_functionst &goto_functions)
{
  std::ostringstream out;

  // Iterating through the available GOTO functions
  for (auto &it : goto_functions.function_map)
    out << translate(it.first.as_string(), it.second) << "\n";

  return out.str();
}

// Convert GOTO function (without the context) to C
std::string
goto2ct::translate(std::string function_id, goto_functiont &goto_function)
{
  std::ostringstream out;

  std::string fun_name_short = expr2ct::get_name_shorthand(function_id);
  // Creating a function symbol
  symbolt fun_sym;
  fun_sym.id = function_id;
  set_symbol_type(fun_sym, goto_function.type);
  // Translating the function declaration
  out << expr2c(code_declt(symbol_expr(fun_sym)), ns) << "\n";
  // Translating the function body
  out << "{\n";
  // Translating local types if there are any
  if (local_types[fun_name_short].size() > 0)
  {
    out << "////////////////////   LOCAL TYPES  ///////////////////////\n";
    for (auto type : local_types[fun_name_short])
      out << typedef2c(type, ns) << "; // " << type.location() << "\n";
  }
  // Translating local static variables if there are any
  if (local_static_vars[fun_name_short].size() > 0)
  {
    out << "///////////////   LOCAL STATIC VARIABLES /////////////////\n";
    for (auto s : local_static_vars[fun_name_short])
    {
      out << expr2c(
               code_declt(symbol_expr(s), initializers[s.id.as_string()]), ns)
          << "; // " << s.location << "\n";
    }
  }
  // Translating the rest of the function body
  out << translate(goto_function.body);
  out << "}\n";
  return out.str();
}

// A block never closes the scopes below `floor`, open before it began.
void goto2ct::enter_scope(
  const goto_programt::instructiont &instruction,
  std::vector<unsigned int> &scopes,
  std::size_t floor,
  std::ostream &out)
{
  unsigned int cur_scope_id = scopes.back();
  if (instruction.scope_id == cur_scope_id)
    return;
  // Entering a new scope
  if (instruction.parent_scope_id == cur_scope_id)
  {
    out << "{ // SCOPE BEGIN {" << cur_scope_id << "}->{"
        << instruction.scope_id << "}\n";
    scopes.push_back(instruction.scope_id);
    return;
  }
  if (scopes.size() <= floor)
    return;
  // Leaving the scope back to the current parent scope
  leave_scope(scopes, out);
  cur_scope_id = scopes.back();
  // If there two scopes next to each other (i.e., {inst1;}{inst2;})
  // we need to open a new scope immediately after the previous one
  // so that we do not skip through the first instruction
  // in the new scope
  if (instruction.scope_id != cur_scope_id)
  {
    out << "{ // SCOPE BEGIN {" << cur_scope_id << "}->{"
        << instruction.scope_id << "}\n";
    scopes.push_back(instruction.scope_id);
  }
}

// A block may not cut a scope, or a variable could escape its braces.
static enclosablet scope_respecting_blocks(const goto_programt &goto_program)
{
  std::unordered_map<const goto_programt::instructiont *, std::size_t> position;
  std::map<unsigned int, std::pair<std::size_t, std::size_t>> extent;
  for (const auto &instruction : goto_program.instructions)
  {
    const std::size_t n = position.size();
    position.emplace(&instruction, n);
    extent.emplace(instruction.scope_id, std::make_pair(n, n))
      .first->second.second = n;
  }
  const auto end = goto_program.instructions.end();
  return
    [position, extent, end](
      goto_programt::const_targett first, goto_programt::const_targett last) {
      auto at = [&](goto_programt::const_targett it) {
        return it == end ? position.size() : position.at(&*it);
      };
      const std::size_t a = at(first), b = at(last);
      for (const auto &[scope, span] : extent)
      {
        // The function scope is always open.
        if (scope == 1)
          continue;
        const auto [lo, hi] = span;
        const bool inside = lo >= a && hi < b;
        const bool outside = hi < a || lo >= b;
        const bool around = lo < a && hi >= b;
        if (!inside && !outside && !around)
          return false;
      }
      return true;
    };
}

void goto2ct::leave_scope(std::vector<unsigned int> &scopes, std::ostream &out)
{
  const unsigned int left = scopes.back();
  scopes.pop_back();
  out << "} // SCOPE END {" << left << "}->{" << scopes.back() << "}\n";
}

// Convert GOTO program to C
std::string goto2ct::translate(goto_programt &goto_program)
{
  std::ostringstream out;
  std::vector<unsigned int> scopes = {1};
  if (structured_loops)
  {
    translate(
      recover_structure(goto_program, scope_respecting_blocks(goto_program)),
      scopes,
      1,
      out);
    return out.str();
  }
  for (const auto &instruction : goto_program.instructions)
  {
    enter_scope(instruction, scopes, 1, out);
    out << translate(instruction) << "\n";
  }
  return out.str();
}

void goto2ct::translate(
  const std::vector<structured_stmtt> &stmts,
  std::vector<unsigned int> &scopes,
  std::size_t floor,
  std::ostream &out)
{
  for (const structured_stmtt &stmt : stmts)
    translate(stmt, scopes, floor, out);
}

void goto2ct::translate_block(
  const std::vector<structured_stmtt> &stmts,
  std::vector<unsigned int> &scopes,
  std::ostream &out)
{
  const std::size_t floor = scopes.size();
  out << "{\n";
  translate(stmts, scopes, floor, out);
  while (scopes.size() > floor)
    leave_scope(scopes, out);
  out << "}\n";
}

void goto2ct::translate(
  const structured_stmtt &stmt,
  std::vector<unsigned int> &scopes,
  std::size_t floor,
  std::ostream &out)
{
  if (stmt.instruction)
    enter_scope(*stmt.instruction, scopes, floor, out);
  auto guard = [&] { return expr2c(migrate_expr_back(stmt.condition), ns); };
  switch (stmt.kind)
  {
  case structured_stmtt::INSTRUCTION:
  case structured_stmtt::GOTO:
    out << translate(*stmt.instruction) << "\n";
    return;
  case structured_stmtt::ANCHOR:
    out << label(*stmt.instruction);
    return;
  case structured_stmtt::BREAK:
  case structured_stmtt::CONTINUE:
    out << label(*stmt.instruction)
        << (is_true(stmt.condition) ? "" : "if(" + guard() + ") ")
        << (stmt.kind == structured_stmtt::BREAK ? "break;" : "continue;")
        << "\n";
    return;
  case structured_stmtt::IF:
    out << label(*stmt.instruction) << "if(" << guard() << ")\n";
    translate_block(stmt.body, scopes, out);
    if (!stmt.otherwise.empty())
    {
      out << "else\n";
      translate_block(stmt.otherwise, scopes, out);
    }
    return;
  case structured_stmtt::WHILE:
    out << label(*stmt.instruction) << "while(" << guard() << ")\n";
    translate_block(stmt.body, scopes, out);
    return;
  case structured_stmtt::DO_WHILE:
    out << "do\n";
    translate_block(stmt.body, scopes, out);
    out << "while(" << guard() << ");\n";
    return;
  case structured_stmtt::FOREVER:
    out << "while(1)\n";
    translate_block(stmt.body, scopes, out);
    return;
  }
}

std::string goto2ct::label(const goto_programt::instructiont &instruction)
{
  if (!instruction.is_target())
    return "";
  return "__ESBMC_goto_label_" + std::to_string(instruction.target_number) +
         ":; // Target\n";
}

// Convert GOTO instruction to C
std::string goto2ct::translate(const goto_programt::instructiont &instruction)
{
  std::ostringstream out;
  out << label(instruction);

  // Identifying the type of the GOTO instruction
  switch (instruction.type)
  {
  case ASSERT:
    out << expr2c(code_assertt(migrate_expr_back(instruction.guard)), ns);
    break;
  case ASSUME:
    out << "// "
        << expr2c(code_assumet(migrate_expr_back(instruction.guard)), ns);
    break;
  case GOTO:
    // If we know that the guard is TRUE, then just skip the "if" part
    if (!is_true(instruction.guard))
      out << "if(" << expr2c(migrate_expr_back(instruction.guard), ns) << ") ";
    // It is guaranteed that every GOTO instruction has only one target
    out << "goto __ESBMC_goto_label_"
        << instruction.targets.front()->target_number;
    break;
  // These expressions can be just translated directly
  case FUNCTION_CALL:
  case RETURN:
  case DECL:
  case ASSIGN:
  case OTHER:
    out << expr2c(migrate_expr_back(instruction.code), ns);
    break;
  // "Silent" instructions. They cannot be translated directly into C.
  // So we just keep them for debugging purposes.
  case END_FUNCTION:
    out << "// " << instruction.location.function();
    break;
  case DEAD:
    out << "// " << expr2c(migrate_expr_back(instruction.code), ns);
    break;
  case LOCATION:
    out << "// " << instruction.location;
    break;
  case SKIP:
    out << "// " << instruction.location;
    break;
  case NO_INSTRUCTION_TYPE:
    out << "// " << instruction.location << "";
    break;
  case ATOMIC_BEGIN:
    out << "__ESBMC_atomic_begin()";
    break;
  case ATOMIC_END:
    out << "__ESBMC_atomic_end()";
    break;
  case LOOP_INVARIANT:
  {
    const char *separator = "";
    for (const expr2tc &invariant : instruction.get_loop_invariants())
    {
      out << separator << "__ESBMC_loop_invariant("
          << expr2c(migrate_expr_back(invariant), ns) << ")";
      separator = "; ";
    }
    // What __ESBMC_loop_assigns(x, ...) expands to.
    const std::list<expr2tc> assigns = instruction.get_loop_assigns_targets();
    if (!assigns.empty())
    {
      out << separator << "__ESBMC_loop_assigns_impl(";
      for (const expr2tc &target : assigns)
        out << (&target == &assigns.front() ? "" : ", ") << "&("
            << expr2c(migrate_expr_back(target), ns) << ")";
      out << ")";
    }
    break;
  }
  // These are C++ instructions. We do not translate those at the moment.
  case THROW:
  case CATCH:
    assert(!"C++ instructions are not supported by GOTO2C");
    out << "C++ instruction";
    break;
  default:
    assert(!"Unknown instruction type");
    out << "unknown instruction";
  }
  out << ";";
  out << " // " << instruction.location.comment() << " // " << instruction.type;
  return out.str();
}
