// Auto-generated harness for: memcmp
// Source: src/c2goto/library/string.c:370
// Generated by Byte Repair Contractor

#include <stddef.h>

extern int memcmp(const void *s1, const void *s2, size_t n);

void __byterepair_harness_main(void) {
    // --- Symbolic inputs ---
    size_t n = nondet_uint();
    __ESBMC_assume(n <= 8);
    unsigned char buf1[8];
    unsigned char buf2[8];
    const void *s1 = (const void *)buf1;
    const void *s2 = (const void *)buf2;

    // --- Call under test ---
    int result = memcmp(s1, s2, n);

    // --- Postcondition assertions ---
    // result == 0 iff every byte in [0, n) is equal.
    size_t k;
    __ESBMC_assert(
        (result == 0)
        == __ESBMC_forall(&k,
               !(k < n) || ((const unsigned char *)s1)[k]
                           == ((const unsigned char *)s2)[k]),
        "system property: memcmp returns 0 iff all n bytes equal");
}
