// Auto-generated by ESBMC 8.1.0
// Test case 1 of 2
// This file provides concrete implementations of __VERIFIER_nondet_* functions

void __VERIFIER_assume(int cond) { (void)cond; }

_Bool __VERIFIER_nondet_bool(void) {
  static int i = 0;
  static const _Bool v[] = { 0 };
  return v[i++];
}

