/* Generated by scripts/rv2c.py from cxl_mbox.h -- do not edit.
 *
 * Linux RV monitor 'cxl_mbox', as an ESBMC-checkable specification.
 * The obligation is the one in include/rv/da_monitor.h: an event that
 * has no transition from the current state drives the automaton to
 * INVALID_STATE, and the monitor reacts. Here that is an assertion.
 *
 * This file is the SPECIFICATION. Supply an implementation that calls
 * rv_cxl_mbox_event() and prove it never trips the assertion; driving
 * it with unconstrained events reaches INVALID_STATE at once and
 * establishes nothing.
 */
#ifndef RV_SPEC_CXL_MBOX_H
#define RV_SPEC_CXL_MBOX_H

#include <assert.h>

enum rv_cxl_mbox_state { mbox_idle, mbox_busy, RV_CXL_MBOX_INVALID };
enum rv_cxl_mbox_event { doorbell_clear, mbox_submit, mbox_timeout };

#define RV_CXL_MBOX_STATES 2
#define RV_CXL_MBOX_EVENTS 3

static const unsigned char rv_cxl_mbox_function[2][3] = {
  /* mbox_idle                    */ { RV_CXL_MBOX_INVALID, mbox_busy, RV_CXL_MBOX_INVALID },
  /* mbox_busy                    */ { mbox_idle, RV_CXL_MBOX_INVALID, mbox_idle },
};

static enum rv_cxl_mbox_state rv_cxl_mbox_cur = mbox_idle;

static void rv_cxl_mbox_reset(void) { rv_cxl_mbox_cur = mbox_idle; }

/* Feed one event. Trips the RV obligation if the automaton rejects it. */
static void rv_cxl_mbox_event(enum rv_cxl_mbox_event ev)
{
  assert(rv_cxl_mbox_cur < RV_CXL_MBOX_STATES);
  assert((unsigned)ev < RV_CXL_MBOX_EVENTS);
  enum rv_cxl_mbox_state next =
    (enum rv_cxl_mbox_state)rv_cxl_mbox_function[rv_cxl_mbox_cur][ev];
  /* include/rv/da_monitor.h:690 -- the monitor's whole obligation. */
  assert(next != RV_CXL_MBOX_INVALID);
  rv_cxl_mbox_cur = next;
}

#endif