#!/usr/bin/env python3

"""
Generate an lcov-style HTML coverage report from ESBMC's cov-report.json.

Usage:
    python3 scripts/cov-report.py [cov-report.json] [-o output_dir]

Reads the JSON file produced by `esbmc --cov-report-json` and generates
an HTML report with source code annotation showing covered/uncovered branches,
conditions, or assertions.
"""

import argparse
import html
import json
import os
import sys
from collections import defaultdict
from pathlib import Path

# ── HTML templates ──────────────────────────────────────────────────────────

INDEX_HTML = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>ESBMC Coverage Report</title>
<style>
{css}
</style>
</head>
<body>
<div class="header">
  <h1>ESBMC Coverage Report</h1>
  <span class="badge">{coverage_type} coverage</span>
</div>

<div class="summary-bar">
  <div class="summary-fill" style="width:{percentage:.1f}%"></div>
  <span class="summary-text">{covered}/{total} ({percentage:.1f}%)</span>
</div>

<table class="file-table">
<thead>
<tr>
  <th>Source File</th>
  <th>Claims</th>
  <th>Covered</th>
  <th>Uncovered</th>
  <th>Coverage</th>
  <th class="bar-col">Bar</th>
</tr>
</thead>
<tbody>
{file_rows}
</tbody>
</table>

<div class="footer">Generated by ESBMC cov-report.py</div>
</body>
</html>
"""

FILE_ROW = """\
<tr>
  <td><a href="{link}">{display_name}</a></td>
  <td>{total}</td>
  <td class="cov">{covered}</td>
  <td class="uncov">{uncovered}</td>
  <td>{percentage:.1f}%</td>
  <td class="bar-col"><div class="bar"><div class="bar-fill" style="width:{percentage:.1f}%"></div></div></td>
</tr>"""

SOURCE_HTML = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Coverage: {filename}</title>
<style>
{css}
</style>
</head>
<body>
<div class="header">
  <h1><a href="index.html">&larr; Back</a> &nbsp; {filename}</h1>
  <span class="badge">{coverage_type} coverage</span>
</div>

<div class="summary-bar">
  <div class="summary-fill" style="width:{percentage:.1f}%"></div>
  <span class="summary-text">{covered}/{total} ({percentage:.1f}%)</span>
</div>

<div class="legend">
  <span class="leg-cov">&#9632; Covered</span>
  <span class="leg-uncov">&#9632; Uncovered</span>
</div>

<table class="source-table">
<thead>
<tr><th class="ln-col">Line</th><th class="ann-col">Claims</th><th>Source</th></tr>
</thead>
<tbody>
{source_rows}
</tbody>
</table>

<div class="footer">Generated by ESBMC cov-report.py</div>
</body>
</html>
"""

CSS = """\
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, "Segoe UI", Roboto, Helvetica, sans-serif;
       background: #f5f5f5; color: #333; padding: 20px; }
a { color: #0366d6; text-decoration: none; }
a:hover { text-decoration: underline; }
.header { display: flex; align-items: center; gap: 16px; margin-bottom: 16px; }
.header h1 { font-size: 20px; }
.badge { background: #0366d6; color: #fff; padding: 3px 10px; border-radius: 12px;
         font-size: 13px; }

/* summary bar */
.summary-bar { position: relative; background: #e74c3c; border-radius: 4px;
               height: 24px; margin-bottom: 20px; overflow: hidden; }
.summary-fill { background: #27ae60; height: 100%; transition: width .3s; }
.summary-text { position: absolute; top: 0; left: 0; right: 0; text-align: center;
                line-height: 24px; font-size: 13px; font-weight: 600; color: #fff; }

/* file table */
.file-table { width: 100%; border-collapse: collapse; background: #fff;
              border-radius: 6px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,.1); }
.file-table th { background: #fafafa; text-align: left; padding: 8px 12px;
                 font-size: 13px; border-bottom: 2px solid #eee; }
.file-table td { padding: 8px 12px; font-size: 13px; border-bottom: 1px solid #eee; }
.file-table .cov { color: #27ae60; font-weight: 600; }
.file-table .uncov { color: #e74c3c; font-weight: 600; }
.bar-col { width: 160px; }
.bar { background: #e74c3c; border-radius: 3px; height: 14px; overflow: hidden; }
.bar-fill { background: #27ae60; height: 100%; }

/* source table */
.source-table { width: 100%; border-collapse: collapse; background: #fff;
                box-shadow: 0 1px 3px rgba(0,0,0,.1); font-size: 13px; }
.source-table th { background: #fafafa; text-align: left; padding: 4px 8px;
                   border-bottom: 2px solid #eee; font-size: 12px; }
.source-table td { padding: 0 8px; vertical-align: top; border-bottom: 1px solid #f0f0f0; }
.ln-col { width: 55px; text-align: right; color: #999; user-select: none; }
.ann-col { width: 220px; }
pre { margin: 0; white-space: pre-wrap; word-break: break-all; font-family: "SFMono-Regular",
      Consolas, "Liberation Mono", Menlo, monospace; font-size: 13px; line-height: 20px; }
.line-cov { background: #e6ffec; }
.line-uncov { background: #ffebe9; }
.ann { font-size: 11px; line-height: 18px; }
.ann-cov { color: #27ae60; }
.ann-uncov { color: #e74c3c; }

.legend { margin-bottom: 12px; font-size: 13px; }
.leg-cov { color: #27ae60; margin-right: 16px; }
.leg-uncov { color: #e74c3c; }

.footer { margin-top: 24px; font-size: 12px; color: #999; text-align: center; }
"""


# ── helpers ─────────────────────────────────────────────────────────────────

def load_report(path: str) -> dict:
    with open(path) as f:
        return json.load(f)


def read_source(path: str) -> list[str]:
    """Read source file lines, return empty list if not found."""
    try:
        with open(path) as f:
            return f.read().splitlines()
    except FileNotFoundError:
        return []


def group_claims_by_file(claims: list[dict]) -> dict[str, list[dict]]:
    by_file: dict[str, list[dict]] = defaultdict(list)
    for c in claims:
        by_file[c["file"]].append(c)
    return dict(by_file)


def file_stats(claims: list[dict]) -> tuple[int, int, int, float]:
    total = len(claims)
    covered = sum(1 for c in claims if c["status"] == "covered")
    uncovered = total - covered
    pct = covered * 100.0 / total if total else 0.0
    return total, covered, uncovered, pct


def safe_filename(path: str) -> str:
    """Turn an absolute path into a safe HTML filename."""
    return path.replace("/", "_").replace("\\", "_").lstrip("_") + ".html"


# ── generators ──────────────────────────────────────────────────────────────

def build_source_page(filepath: str, claims: list[dict], coverage_type: str) -> str:
    lines = read_source(filepath)
    total, covered, uncovered, pct = file_stats(claims)

    # Build per-line annotation map: line -> list of (condition, status)
    line_anns: dict[int, list[tuple[str, str]]] = defaultdict(list)
    for c in claims:
        line_anns[c["line"]].append((c["condition"], c["status"]))

    # Determine per-line highlight status
    line_status: dict[int, str] = {}
    for line_no, anns in line_anns.items():
        statuses = {s for _, s in anns}
        if "uncovered" in statuses:
            line_status[line_no] = "uncov"
        else:
            line_status[line_no] = "cov"

    rows = []
    for i, line_text in enumerate(lines, 1):
        css_class = ""
        ann_html = ""

        if i in line_anns:
            css_class = f' class="line-{"cov" if line_status[i] == "cov" else "uncov"}"'
            parts = []
            for cond, status in line_anns[i]:
                cls = "ann-cov" if status == "covered" else "ann-uncov"
                symbol = "&#10004;" if status == "covered" else "&#10008;"
                parts.append(f'<span class="ann {cls}">{symbol} {html.escape(cond)}</span>')
            ann_html = "<br>".join(parts)

        rows.append(
            f'<tr{css_class}>'
            f'<td class="ln-col">{i}</td>'
            f'<td class="ann-col">{ann_html}</td>'
            f'<td><pre>{html.escape(line_text)}</pre></td>'
            f'</tr>'
        )

    return SOURCE_HTML.format(
        filename=os.path.basename(filepath),
        css=CSS,
        coverage_type=coverage_type,
        percentage=pct,
        covered=covered,
        total=total,
        source_rows="\n".join(rows),
    )


def build_index(report: dict, by_file: dict[str, list[dict]]) -> str:
    summary = report["summary"]
    file_rows = []

    for filepath in sorted(by_file):
        claims = by_file[filepath]
        total, covered, uncovered, pct = file_stats(claims)
        link = safe_filename(filepath)
        display = os.path.basename(filepath)
        file_rows.append(FILE_ROW.format(
            link=link, display_name=display,
            total=total, covered=covered, uncovered=uncovered, percentage=pct,
        ))

    return INDEX_HTML.format(
        css=CSS,
        coverage_type=report["coverage_type"],
        percentage=summary["percentage"],
        covered=summary["covered"],
        total=summary["total"],
        file_rows="\n".join(file_rows),
    )


# ── main ────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Generate HTML coverage report from ESBMC cov-report.json")
    parser.add_argument("json_file", nargs="?", default="cov-report.json",
                        help="Path to cov-report.json (default: cov-report.json)")
    parser.add_argument("-o", "--output", default="cov-report-html",
                        help="Output directory (default: cov-report-html)")
    args = parser.parse_args()

    if not os.path.isfile(args.json_file):
        print(f"Error: {args.json_file} not found", file=sys.stderr)
        sys.exit(1)

    report = load_report(args.json_file)
    by_file = group_claims_by_file(report["claims"])

    out_dir = Path(args.output)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Write index
    (out_dir / "index.html").write_text(build_index(report, by_file))

    # Write per-file pages
    for filepath, claims in by_file.items():
        page = build_source_page(filepath, claims, report["coverage_type"])
        (out_dir / safe_filename(filepath)).write_text(page)

    total = report["summary"]["total"]
    covered = report["summary"]["covered"]
    pct = report["summary"]["percentage"]
    print(f"Coverage report: {covered}/{total} ({pct:.1f}%) -> {out_dir}/index.html")


if __name__ == "__main__":
    main()
