#!/usr/bin/env python3
# Generate the allowlist of Python operational-model entry points.
#
# ESBMC's Python frontend lowers str/int/math/list operations to C operational
# models defined under src/c2goto/library/python/*.c. For a model body to be
# linked into the program under analysis, its name must be passed to
# goto_binary_reader::set_functions_to_read (see python_c_models in
# src/c2goto/cprover_library.cpp). Maintaining that allowlist by hand let new
# models silently fall back to nondeterministic values when an entry was missed.
#
# This script scans the model sources for non-static, top-level function
# definitions and emits their names as a C array, so every model registers
# automatically. The stable external dependencies (libc/libm/threading helpers
# defined outside library/python) remain an explicit list in cprover_library.cpp.
#
# Args are: -o <output header> <input.c>+

import argparse
import re
import sys

# A function definition's header, found only at file scope (brace depth 0):
# an optional return type, the function name, a parenthesised parameter list,
# and the opening body brace. The header runs from the start of a logical
# statement up to the '{', so it can never reach into a function body, which is
# what distinguishes a definition from a call.
HEADER_RE = re.compile(
    r'(?s)([A-Za-z_][\w\s\*]*?[\s\*])([A-Za-z_]\w*)\s*\(([^;{}]*)\)\s*$')


def _strip_noise(text):
    """Remove comments and string/char literals so braces and ';' are reliable."""
    text = re.sub(r'/\*.*?\*/', ' ', text, flags=re.S)
    text = re.sub(r'//[^\n]*', '', text)
    text = re.sub(r'"(?:\\.|[^"\\])*"', '""', text)
    text = re.sub(r"'(?:\\.|[^'\\])*'", "''", text)
    text = re.sub(r'(?m)^[ \t]*#.*$', '', text)
    return text


def model_names(path):
    """Return the names of non-static, top-level functions defined in a C file.

    Scans at brace depth 0 only, so calls and constructs inside function bodies
    are never mistaken for definitions. 'static' and 'typedef' functions are
    excluded; the goto allowlist only needs externally linkable entry points.
    """
    text = _strip_noise(open(path, encoding='utf-8').read())
    names = []
    depth = 0
    statement_start = 0
    for pos, char in enumerate(text):
        if char == '{':
            if depth == 0:
                match = HEADER_RE.match(text[statement_start:pos].strip())
                if match and not re.search(
                    r'\b(static|typedef)\b', match.group(1)):
                    names.append(match.group(2))
            depth += 1
        elif char == '}':
            depth = max(0, depth - 1)
            statement_start = pos + 1
        elif char == ';' and depth == 0:
            statement_start = pos + 1
    return names


def main():
    argp = argparse.ArgumentParser(description=__doc__)
    argp.add_argument('-o', '--output', required=True, help='output header file')
    argp.add_argument('inputs', nargs='+', help='Python model C sources')
    opts = argp.parse_args()

    names = sorted({name for path in opts.inputs for name in model_names(path)})
    if not names:
        sys.exit('gen_python_c_models: no model functions found in inputs')

    lines = [
        '// GENERATED by scripts/gen_python_c_models.py -- DO NOT EDIT.',
        '// Non-static model functions defined in src/c2goto/library/python/*.c.',
        '#pragma once',
        'static const char *const python_c_models_generated[] = {',
    ]
    lines += ['  "' + name + '",' for name in names]
    lines.append('};')
    with open(opts.output, 'w', encoding='utf-8') as out:
        out.write('\n'.join(lines) + '\n')


if __name__ == '__main__':
    main()
