#!/usr/bin/env bash
# clang-format 23 helper. CI uses the same clang-format 23 and the same
# changed-lines-only check, so passing locally means passing CI's code-style
# job.
#
# Usage:
#   scripts/install-format-hook.sh            Install the pre-commit hook
#                                             (formats changed lines on every
#                                             future commit). Default.
#   scripts/install-format-hook.sh --fix [BASE]
#                                             Reformat the lines this branch
#                                             changed vs BASE (default
#                                             origin/master) in the working
#                                             tree, so you can fix lines that
#                                             are already committed/pushed.
#                                             After it runs, commit & push.
#
# Both modes download clang-format and git-clang-format from the PyPI
# clang-format wheel (the version CI installs) into a cache dir under the
# repo, reusing it if already present.
set -euo pipefail

mode="install"
fix_base="origin/master"
case "${1:-}" in
  --fix)
    mode="fix"
    [ -n "${2:-}" ] && fix_base="$2"
    ;;
  --install | "")
    mode="install"
    ;;
  -h | --help)
    sed -n '2,17p' "$0"
    exit 0
    ;;
  *)
    echo "install-format-hook: unknown argument '$1' (use --install or --fix)" >&2
    exit 2
    ;;
esac

# Resolve the repo root from this script's location so it works from anywhere.
script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
repo_root=$(cd "$script_dir/.." && git rev-parse --show-toplevel)

clang_format_version="23.1.1"
cache_dir="$repo_root/.cache/clang-format-23"
clang_format="$cache_dir/bin/clang-format"
git_clang_format="$cache_dir/bin/git-clang-format"

download_clang_format() {
  local platform url tmp
  case "$(uname -s)-$(uname -m)" in
    Linux-x86_64) platform="manylinux_2_27_x86_64.manylinux_2_28_x86_64" ;;
    Linux-aarch64) platform="manylinux_2_26_aarch64.manylinux_2_28_aarch64" ;;
    Darwin-x86_64) platform="macosx_10_9_x86_64" ;;
    Darwin-arm64) platform="macosx_11_0_arm64" ;;
    *)
      echo "install-format-hook: no clang-format wheel for $(uname -s)-$(uname -m)." >&2
      echo "Install clang-format $clang_format_version manually and point the hook at it." >&2
      exit 1
      ;;
  esac
  url="https://files.pythonhosted.org/packages/py2.py3/c/clang-format/clang_format-$clang_format_version-py2.py3-none-$platform.whl"

  echo "Downloading clang-format $clang_format_version ($url)..."
  tmp=$(mktemp -d)
  curl -fL --retry 3 -o "$tmp/clang-format.whl" "$url"

  # A wheel is a zip archive: take only the two tools out of it.
  mkdir -p "$cache_dir/bin"
  python3 - "$tmp/clang-format.whl" "$clang_format" "$git_clang_format" <<'PY'
import sys
import zipfile

wheel, clang_format, git_clang_format = sys.argv[1:]
with zipfile.ZipFile(wheel) as z:
    for member, dest in (("clang_format/data/bin/clang-format", clang_format),
                         ("clang_format/git_clang_format.py", git_clang_format)):
        with open(dest, "wb") as f:
            f.write(z.read(member))
PY
  chmod +x "$clang_format" "$git_clang_format"
  rm -rf "$tmp"
}

if [ ! -x "$clang_format" ] || [ ! -f "$git_clang_format" ]; then
  download_clang_format
else
  echo "Reusing cached clang-format $clang_format_version at $clang_format"
fi

echo "clang-format version: $("$clang_format" --version)"

# --- fix mode: reformat already-committed changed lines in the working tree --
if [ "$mode" = "fix" ]; then
  mapfile -t files < <(
    git -C "$repo_root" diff --name-only --diff-filter=d "$fix_base"...HEAD -- src unit |
    grep -E '\.(h|c|cpp|hpp|hh)$' |
    grep -v '^src/ansi-c/cpp/' |
    grep -v '^src/clang-c-frontend/headers/' |
    grep -v '^src/c2goto/library/libm/musl/' || true
  )
  if [ ${#files[@]} -eq 0 ]; then
    echo "No changed C/C++ files vs $fix_base; nothing to fix."
    exit 0
  fi

  # Reformat only the lines changed since the base, in place. Mirrors CI's
  # --diff check, minus --diff, so the working tree ends up CI-clean.
  ( cd "$repo_root" && python3 "$git_clang_format" \
      --binary "$clang_format" \
      --style file \
      --extensions h,c,cpp,hpp,hh \
      "$fix_base" -- "${files[@]}" )

  echo
  echo "Reformatted changed lines vs $fix_base. Review, then commit & push:"
  echo "  git add -u && git commit -m 'apply clang-format' && git push"
  exit 0
fi

hook_path="$(git -C "$repo_root" rev-parse --git-path hooks)/pre-commit"
mkdir -p "$(dirname "$hook_path")"

cat > "$hook_path" <<HOOK
#!/usr/bin/env bash
# Auto-generated by scripts/install-format-hook.sh — formats only the lines
# changed in the staged diff with clang-format 23, then re-stages them. Re-run
# that script to regenerate this hook.
set -euo pipefail

clang_format="$clang_format"
git_clang_format="$git_clang_format"

if [ ! -x "\$clang_format" ] || [ ! -f "\$git_clang_format" ]; then
  echo "pre-commit: clang-format 23 missing; run scripts/install-format-hook.sh" >&2
  exit 0
fi

# Staged C/C++ files (added/copied/modified/renamed; deletions excluded),
# matching CI's path filters so local and CI agree on scope.
mapfile -d '' -t files < <(
  git diff --cached --name-only --diff-filter=ACMR -z -- src unit |
  grep -zE '\.(c|cc|cpp|cxx|h|hh|hpp|hxx)\$' |
  grep -zv '^src/ansi-c/cpp/' |
  grep -zv '^src/clang-c-frontend/headers/' |
  grep -zv '^src/c2goto/library/libm/musl/' || true
)
if [ \${#files[@]} -eq 0 ]; then
  exit 0
fi

# Only re-stage files with no unstaged changes; otherwise a re-add would pull
# in working-tree edits the user deliberately left unstaged.
clean=()
for f in "\${files[@]}"; do
  if git diff --quiet -- "\$f"; then
    clean+=("\$f")
  fi
done

# Format only the lines changed since HEAD, not whole files.
python3 "\$git_clang_format" \\
  --binary "\$clang_format" \\
  --style file \\
  --extensions c,cc,cpp,cxx,h,hh,hpp,hxx \\
  HEAD -- "\${files[@]}" >/dev/null 2>&1 || true

restaged=()
for f in "\${clean[@]}"; do
  if ! git diff --quiet -- "\$f"; then
    git add -- "\$f"
    restaged+=("\$f")
  fi
done

if [ \${#restaged[@]} -gt 0 ]; then
  echo "pre-commit: clang-format applied to \${#restaged[@]} staged file(s):" >&2
  printf '  %s\n' "\${restaged[@]}" >&2
fi
exit 0
HOOK

chmod +x "$hook_path"

echo
echo "Installed pre-commit hook at: $hook_path"
echo "It formats only changed lines with clang-format 23 (matches CI)."
