#!/usr/bin/env python3
"""Emit an ESBMC --ltl Buchi monitor for the LTL *response* pattern.

    G (p -> F q)      "every p is eventually followed by a q"

ESBMC's --ltl mode does not take an LTL string. It takes a C file containing a
precomputed Buchi automaton plus the four-valued acceptance tables that
ltl2ba emits (see regression/ltl/basic/test.ba-2.c). The patched ltl2ba that
produces those files is not in this tree and is not publicly available, so
this script generates the one pattern the CXL work needs.

SCOPE, stated plainly: this is not an LTL-to-Buchi translator. It emits a
single, fixed two-state automaton -- the standard one for the response
pattern -- with the atomic propositions substituted in. Give it any other
formula and it will silently produce the wrong monitor, because it does not
parse a formula at all. Anything beyond `G (p -> F q)` needs the real tool.

The automaton and its tables are transcribed from the ltl2ba output already
committed at regression/ltl/basic/test.ba-2.c, which ESBMC's own regression
suite exercises. `--self-test` regenerates that file's monitor and diffs the
executable part against it, which is what makes this trustworthy rather than
merely plausible.

Usage:
  ltl_response_ba.py --p '<C expr>' --q '<C expr>' \
                     [--extern '<decl>' ...] [-o out.c]
  ltl_response_ba.py --self-test
"""

import argparse
import subprocess
import sys
import tempfile
from pathlib import Path

# The response automaton, from ltl2ba:
#
#   state 0 (init, accepting) -- no outstanding obligation
#   state 1                   -- a p was seen, a q is owed
#
# Acceptance is over the four AP valuations (index = p | q<<1); the tables
# below are ltl2ba's, not reconstructed by hand.
STUTTER_ACCEPT = [  # [sym][state]
    ("true", "false"),   # !p & !q
    ("false", "false"),  #  p & !q
    ("true", "true"),    # !p &  q
    ("true", "true"),    #  p &  q
]
GOOD_PREFIX_EXCLUDED = ("true", "true")
BAD_PREFIX = ("false", "false")

TEMPLATE = r'''#if 0
/* Precomputed transition data
 * Generated by scripts/ltl_response_ba.py -- LTL response pattern.
 *
 * Formula: G ({P} -> F {Q})
 *
 * States:
 *   0  init, accepting -- no outstanding obligation
 *   1                  -- a {P} was seen, a {Q} is owed
 */
#endif
#include <pthread.h>
#include <stdbool.h>
#include <stdint.h>

void __ESBMC_switch_to_monitor(void);
void __ESBMC_switch_from_monitor(void);
void __ESBMC_register_monitor(pthread_t t);
void __ESBMC_really_atomic_begin();
void __ESBMC_really_atomic_end();
void __ESBMC_atomic_begin();
void __ESBMC_atomic_end();
void __ESBMC_assume(_Bool prop);
void __ESBMC_kill_monitor();
unsigned int nondet_uint();

{EXTERNS}

char __ESBMC_property__ltl2ba_cexpr_0[] = "{P_ESC}";
int _ltl2ba_cexpr_0_status(void) {{ return {P}; }}
char __ESBMC_property__ltl2ba_cexpr_1[] = "{Q_ESC}";
int _ltl2ba_cexpr_1_status(void) {{ return {Q}; }}

typedef enum {{
	_ltl2ba_state_0,
	_ltl2ba_state_1,
}} _ltl2ba_state;

_ltl2ba_state _ltl2ba_statevar =_ltl2ba_state_0;

unsigned int _ltl2ba_visited_states[2];

void
ltl2ba_fsm(bool state_stats, unsigned int num_iters)
{{
	unsigned int choice;
	unsigned int iters;
	_Bool state_is_viable;

	/* Original formula:
	 * G({{{P}}} -> F {{{Q}}})
	 */

	for (iters = 0; iters < num_iters; iters++) {{
		choice = nondet_uint();

		__ESBMC_atomic_begin();

		switch(_ltl2ba_statevar) {{
		case _ltl2ba_state_0:
			state_is_viable = (((!({P})) || (({Q}))) || ((1)) || ((({Q}))) || ((false)));
			if (choice == 0) {{
				__ESBMC_assume(((!({P})) || (({Q}))));
				_ltl2ba_statevar = _ltl2ba_state_0;
			}} else if (choice == 1) {{
				__ESBMC_assume(((1)));
				_ltl2ba_statevar = _ltl2ba_state_1;
			}} else if (choice == 2) {{
				__ESBMC_assume(((({Q}))));
				_ltl2ba_statevar = _ltl2ba_state_0;
			}} else {{
				__ESBMC_assume(0);
			}}
			break;
		case _ltl2ba_state_1:
			state_is_viable = (((1)) || ((({Q}))) || ((false)));
			if (choice == 0) {{
				__ESBMC_assume(((1)));
				_ltl2ba_statevar = _ltl2ba_state_1;
			}} else if (choice == 1) {{
				__ESBMC_assume(((({Q}))));
				_ltl2ba_statevar = _ltl2ba_state_0;
			}} else {{
				__ESBMC_assume(0);
			}}
			break;
		}}
		if (state_stats)
			_ltl2ba_visited_states[_ltl2ba_statevar]++;

		__ESBMC_atomic_end();
		// __ESBMC_switch_from_monitor();
	}}

	__ESBMC_assert(num_iters == iters, "Unwind bound on ltl2ba_fsm insufficient");

	return;
}}

#ifndef LTL_PREFIX_BOUND
#define LTL_PREFIX_BOUND 2147483648
#endif

#define max(x,y) ((x) < (y) ? (y) : (x))

void * ltl2ba_thread(void *dummy)
{{
	ltl2ba_fsm(false, LTL_PREFIX_BOUND);
	return 0;
	(void)dummy;
}}

void ltl2ba_start_monitor(void)
{{
	pthread_t t;

//	__ESBMC_atomic_begin();
	pthread_create(&t, NULL, ltl2ba_thread, NULL);
	__ESBMC_register_monitor(t);
//	__ESBMC_atomic_end();

	// __ESBMC_switch_to_monitor();
}}

_Bool _ltl2ba_stutter_accept_table[4][2] = {{
{STUTTER}
}};

_Bool _ltl2ba_good_prefix_excluded_states[2] = {{
{GOOD_EXCL}
}};

_Bool _ltl2ba_bad_prefix_states[2] = {{
{BAD}
}};

unsigned int
_ltl2ba_sym_to_idx(void)
{{
	unsigned int idx = 0;
	idx |= (({P})) ? 1 : 0;
	idx |= (({Q})) ? 2 : 0;
	return idx;
}}

void
ltl2ba_finish_monitor(void)
{{
	__ESBMC_kill_monitor();

	__ESBMC_assert(!_ltl2ba_bad_prefix_states[_ltl2ba_statevar],"LTL_BAD");

	__ESBMC_assert(!_ltl2ba_stutter_accept_table[_ltl2ba_sym_to_idx()][_ltl2ba_statevar],"LTL_FAILING");

	__ESBMC_assert(!_ltl2ba_good_prefix_excluded_states[_ltl2ba_statevar],"LTL_SUCCEEDING");

	return;
}}
'''


def generate(p_expr: str, q_expr: str, externs) -> str:
    stutter = ",\n".join(
        "{\n  %s, %s, \n}" % row for row in STUTTER_ACCEPT) + ","
    return TEMPLATE.format(
        P=p_expr,
        Q=q_expr,
        P_ESC=p_expr.replace('"', '\\"'),
        Q_ESC=q_expr.replace('"', '\\"'),
        EXTERNS="\n".join(externs),
        STUTTER=stutter,
        GOOD_EXCL="%s, %s, " % GOOD_PREFIX_EXCLUDED,
        BAD="%s, %s, " % BAD_PREFIX,
    )


def executable_part(text: str) -> str:
    """The part ESBMC compiles, i.e. everything after the metadata block."""
    idx = text.index("#endif")
    return text[idx:]


def self_test() -> int:
    """Regenerate regression/ltl/basic's monitor and compare behaviour.

    The committed file is ltl2ba's own output for the same pattern, so if our
    template diverges from it in any way that matters, ESBMC's verdict on the
    same program will differ.
    """
    root = Path(__file__).resolve().parent.parent
    ref = root / "regression/ltl/basic/test.ba-2.c"
    prog = root / "regression/ltl/basic/test.c"
    if not ref.exists():
        print(f"self-test: missing reference {ref}", file=sys.stderr)
        return 2

    ours = generate("pressed", "charge > min",
                    ["extern int pressed;", "extern int charge, min;"])

    ref_body = executable_part(ref.read_text())
    our_body = executable_part(ours)

    # Compare after collapsing whitespace: the reference was emitted by a C
    # program and ours by a template, so layout differs where semantics do not.
    def norm(s):
        return " ".join(s.split())

    if norm(ref_body) == norm(our_body):
        print("self-test: byte-equivalent to ltl2ba output (modulo whitespace)")
        return 0

    print("self-test: text differs from the reference; comparing ESBMC verdicts")
    esbmc = Path(root / "build/src/esbmc/esbmc")
    if not esbmc.exists():
        print("self-test: no esbmc binary; cannot compare verdicts",
              file=sys.stderr)
        return 2

    with tempfile.TemporaryDirectory() as td:
        ours_path = Path(td) / "ours.ba.c"
        ours_path.write_text(ours)
        verdicts = []
        for ba in (ref, ours_path):
            out = subprocess.run(
                [str(esbmc), str(prog), "--ltl", str(ba),
                 "-DLTL_PREFIX_BOUND=10"],
                capture_output=True, text=True, timeout=600).stdout
            line = [l for l in out.splitlines()
                    if "Final lowest outcome" in l or "VERIFICATION" in l]
            verdicts.append(tuple(line))
            print(f"  {ba.name}: {line}")
        if verdicts[0] == verdicts[1]:
            print("self-test: verdicts match")
            return 0
        print("self-test: VERDICTS DIFFER", file=sys.stderr)
        return 1


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--p", help="C expression for the trigger proposition")
    ap.add_argument("--q", help="C expression for the response proposition")
    ap.add_argument("--extern", action="append", default=[],
                    help="declaration to emit (repeatable)")
    ap.add_argument("-o", "--output", help="output file (default: stdout)")
    ap.add_argument("--self-test", action="store_true",
                    help="validate against the committed ltl2ba output")
    args = ap.parse_args()

    if args.self_test:
        return self_test()

    if not args.p or not args.q:
        ap.error("--p and --q are required unless --self-test is given")

    text = generate(args.p, args.q, args.extern)
    if args.output:
        Path(args.output).write_text(text)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
