#!/usr/bin/env python3
"""Emit an ESBMC --ltl Buchi monitor for the LTL *response* pattern.

    G (p -> F q)      "every p is eventually followed by a q"

ESBMC's --ltl mode does not take an LTL string. It takes a C file containing a
precomputed Buchi automaton plus the four-valued acceptance tables that
ltl2ba emits (see regression/ltl/basic/test.ba-2.c).

PREFER THE REAL TOOL: https://github.com/esbmc/libltl2ba (`ltl2ba -O c`).
An earlier version of this docstring said it was not publicly available; that
was wrong, and this script exists only because of that mistake. It handles one
pattern where libltl2ba handles all of LTL.

The one thing to know before switching: the current libltl2ba emits
`pthread_t ltl2ba_start_monitor(void)` and `ltl2ba_finish_monitor(pthread_t)`,
while src/esbmc/parseoptions/property_monitors.cpp inserts no-argument calls to
both. Its output therefore yields no outcome at all until that skew is fixed --
see docs/cxl-temporal-properties.md §7.1. The committed .ba-N.c files predate
the change, which is why this script, transcribed from them, works.

SCOPE, stated plainly: this is not an LTL-to-Buchi translator. It emits a
single, fixed two-state automaton -- the standard one for the response
pattern -- with the atomic propositions substituted in. Give it any other
formula and it will silently produce the wrong monitor, because it does not
parse a formula at all. Anything beyond `G (p -> F q)` needs the real tool.

The automaton and its tables are transcribed from the ltl2ba output already
committed at regression/ltl/basic/test.ba-2.c, which ESBMC's own regression
suite exercises. `--self-test` regenerates that file's monitor and diffs the
executable part against it, which is what makes this trustworthy rather than
merely plausible.

Usage:
  ltl_response_ba.py --p '<C expr>' --q '<C expr>' \
                     [--extern '<decl>' ...] [-o out.c]
  ltl_response_ba.py --self-test
"""

import argparse
import subprocess
import sys
import tempfile
from pathlib import Path

# The response automaton, from ltl2ba:
#
#   state 0 (init, accepting) -- no outstanding obligation
#   state 1                   -- a p was seen, a q is owed
#
# Acceptance is over the four AP valuations (index = p | q<<1); the tables
# below are ltl2ba's, not reconstructed by hand.
STUTTER_ACCEPT = [  # [sym][state]
    ("true", "false"),   # !p & !q
    ("false", "false"),  #  p & !q
    ("true", "true"),    # !p &  q
    ("true", "true"),    #  p &  q
]
GOOD_PREFIX_EXCLUDED = ("true", "true")
BAD_PREFIX = ("false", "false")

TEMPLATE = r'''#if 0
/* Precomputed transition data
 * Generated by scripts/ltl_response_ba.py -- LTL response pattern.
 *
 * Formula: G ({P} -> F {Q})
 *
 * States:
 *   0  init, accepting -- no outstanding obligation
 *   1                  -- a {P} was seen, a {Q} is owed
 */
#endif
#include <pthread.h>
#include <stdbool.h>
#include <stdint.h>

void __ESBMC_switch_to_monitor(void);
void __ESBMC_switch_from_monitor(void);
void __ESBMC_register_monitor(pthread_t t);
void __ESBMC_really_atomic_begin();
void __ESBMC_really_atomic_end();
void __ESBMC_atomic_begin();
void __ESBMC_atomic_end();
void __ESBMC_assume(_Bool prop);
void __ESBMC_kill_monitor();
unsigned int nondet_uint();

{EXTERNS}

char __ESBMC_property__ltl2ba_cexpr_0[] = "{P_ESC}";
int _ltl2ba_cexpr_0_status(void) {{ return {P}; }}
char __ESBMC_property__ltl2ba_cexpr_1[] = "{Q_ESC}";
int _ltl2ba_cexpr_1_status(void) {{ return {Q}; }}

typedef enum {{
	_ltl2ba_state_0,
	_ltl2ba_state_1,
}} _ltl2ba_state;

_ltl2ba_state _ltl2ba_statevar =_ltl2ba_state_0;

unsigned int _ltl2ba_visited_states[2];

void
ltl2ba_fsm(bool state_stats, unsigned int num_iters)
{{
	unsigned int choice;
	unsigned int iters;
	_Bool state_is_viable;

	/* Original formula:
	 * G({{{P}}} -> F {{{Q}}})
	 */

	for (iters = 0; iters < num_iters; iters++) {{
		choice = nondet_uint();

		__ESBMC_atomic_begin();

		switch(_ltl2ba_statevar) {{
		case _ltl2ba_state_0:
			state_is_viable = (((!({P})) || (({Q}))) || ((1)) || ((({Q}))) || ((false)));
			if (choice == 0) {{
				__ESBMC_assume(((!({P})) || (({Q}))));
				_ltl2ba_statevar = _ltl2ba_state_0;
			}} else if (choice == 1) {{
				__ESBMC_assume(((1)));
				_ltl2ba_statevar = _ltl2ba_state_1;
			}} else if (choice == 2) {{
				__ESBMC_assume(((({Q}))));
				_ltl2ba_statevar = _ltl2ba_state_0;
			}} else {{
				__ESBMC_assume(0);
			}}
			break;
		case _ltl2ba_state_1:
			state_is_viable = (((1)) || ((({Q}))) || ((false)));
			if (choice == 0) {{
				__ESBMC_assume(((1)));
				_ltl2ba_statevar = _ltl2ba_state_1;
			}} else if (choice == 1) {{
				__ESBMC_assume(((({Q}))));
				_ltl2ba_statevar = _ltl2ba_state_0;
			}} else {{
				__ESBMC_assume(0);
			}}
			break;
		}}
		if (state_stats)
			_ltl2ba_visited_states[_ltl2ba_statevar]++;

		__ESBMC_atomic_end();
		// __ESBMC_switch_from_monitor();
	}}

	__ESBMC_assert(num_iters == iters, "Unwind bound on ltl2ba_fsm insufficient");

	return;
}}

#ifndef LTL_PREFIX_BOUND
#define LTL_PREFIX_BOUND 2147483648
#endif

#define max(x,y) ((x) < (y) ? (y) : (x))

void * ltl2ba_thread(void *dummy)
{{
	ltl2ba_fsm(false, LTL_PREFIX_BOUND);
	return 0;
	(void)dummy;
}}

void ltl2ba_start_monitor(void)
{{
	pthread_t t;

//	__ESBMC_atomic_begin();
	pthread_create(&t, NULL, ltl2ba_thread, NULL);
	__ESBMC_register_monitor(t);
//	__ESBMC_atomic_end();

	// __ESBMC_switch_to_monitor();
}}

_Bool _ltl2ba_stutter_accept_table[4][2] = {{
{STUTTER}
}};

_Bool _ltl2ba_good_prefix_excluded_states[2] = {{
{GOOD_EXCL}
}};

_Bool _ltl2ba_bad_prefix_states[2] = {{
{BAD}
}};

unsigned int
_ltl2ba_sym_to_idx(void)
{{
	unsigned int idx = 0;
	idx |= (({P})) ? 1 : 0;
	idx |= (({Q})) ? 2 : 0;
	return idx;
}}

void
ltl2ba_finish_monitor(void)
{{
	__ESBMC_kill_monitor();

	__ESBMC_assert(!_ltl2ba_bad_prefix_states[_ltl2ba_statevar],"LTL_BAD");

	__ESBMC_assert(!_ltl2ba_stutter_accept_table[_ltl2ba_sym_to_idx()][_ltl2ba_statevar],"LTL_FAILING");

	__ESBMC_assert(!_ltl2ba_good_prefix_excluded_states[_ltl2ba_statevar],"LTL_SUCCEEDING");

	return;
}}
'''



# ---------------------------------------------------------------------------
# Absence pattern:  G !p   ("p never holds")
#
# Unlike the response pattern this is *safety*: it has a finite counterexample,
# so the automaton has a genuine bad sink and LTL_BAD is reachable. That is the
# whole reason to prefer it -- a monitor that cannot reach LTL_BAD cannot tell
# a correct program from a broken one.
#
#   state 0  init, accepting -- p has never held
#   state 1  bad sink        -- p held at least once
#
# These tables are NOT transcribed from ltl2ba output (there is none committed
# for this pattern). They are constructed, and validated empirically by
# --self-test-absence, which checks that a violating program reaches LTL_BAD
# and a non-violating one does not.
ABSENCE_TEMPLATE = r'''#if 0
/* Precomputed transition data
 * Generated by scripts/ltl_response_ba.py -- LTL absence pattern.
 *
 * Formula: G !({P})
 *
 * States:
 *   0  init, accepting -- {P} has never held
 *   1  bad sink        -- {P} held at least once
 */
#endif
#include <pthread.h>
#include <stdbool.h>
#include <stdint.h>

void __ESBMC_switch_to_monitor(void);
void __ESBMC_switch_from_monitor(void);
void __ESBMC_register_monitor(pthread_t t);
void __ESBMC_really_atomic_begin();
void __ESBMC_really_atomic_end();
void __ESBMC_atomic_begin();
void __ESBMC_atomic_end();
void __ESBMC_assume(_Bool prop);
void __ESBMC_kill_monitor();
unsigned int nondet_uint();

{EXTERNS}

char __ESBMC_property__ltl2ba_cexpr_0[] = "{P_ESC}";
int _ltl2ba_cexpr_0_status(void) {{ return {P}; }}

typedef enum {{
	_ltl2ba_state_0,
	_ltl2ba_state_1,
}} _ltl2ba_state;

_ltl2ba_state _ltl2ba_statevar =_ltl2ba_state_0;

unsigned int _ltl2ba_visited_states[2];

void
ltl2ba_fsm(bool state_stats, unsigned int num_iters)
{{
	unsigned int choice;
	unsigned int iters;
	_Bool state_is_viable;

	/* Original formula:
	 * G(!{{{P}}})
	 */

	for (iters = 0; iters < num_iters; iters++) {{
		choice = nondet_uint();

		__ESBMC_atomic_begin();

		switch(_ltl2ba_statevar) {{
		case _ltl2ba_state_0:
			state_is_viable = (((!({P}))) || ((({P}))) || ((false)));
			if (choice == 0) {{
				__ESBMC_assume(((!({P}))));
				_ltl2ba_statevar = _ltl2ba_state_0;
			}} else if (choice == 1) {{
				__ESBMC_assume(((({P}))));
				_ltl2ba_statevar = _ltl2ba_state_1;
			}} else {{
				__ESBMC_assume(0);
			}}
			break;
		case _ltl2ba_state_1:
			state_is_viable = ((1));
			if (choice == 0) {{
				__ESBMC_assume(((1)));
				_ltl2ba_statevar = _ltl2ba_state_1;
			}} else {{
				__ESBMC_assume(0);
			}}
			break;
		}}
		if (state_stats)
			_ltl2ba_visited_states[_ltl2ba_statevar]++;

		__ESBMC_atomic_end();
	}}

	__ESBMC_assert(num_iters == iters, "Unwind bound on ltl2ba_fsm insufficient");

	return;
}}

#ifndef LTL_PREFIX_BOUND
#define LTL_PREFIX_BOUND 2147483648
#endif

void * ltl2ba_thread(void *dummy)
{{
	ltl2ba_fsm(false, LTL_PREFIX_BOUND);
	return 0;
	(void)dummy;
}}

void ltl2ba_start_monitor(void)
{{
	pthread_t t;
	pthread_create(&t, NULL, ltl2ba_thread, NULL);
	__ESBMC_register_monitor(t);
}}

/* [sym][state], sym = {P} ? 1 : 0.
 * Stuttering the current valuation forever violates G !{P} exactly when {P}
 * holds now, or when the bad sink has already been entered. */
_Bool _ltl2ba_stutter_accept_table[2][2] = {{
{{
  false, true, 
}},
{{
  true, true, 
}},
}};

/* G !p is never *settled* by a finite prefix: however long p has stayed
 * false, it might still hold later. So no state admits a good prefix. */
_Bool _ltl2ba_good_prefix_excluded_states[2] = {{
true, true, 
}};

/* The sink is a genuine finite counterexample -- this is what the response
 * pattern lacks. */
_Bool _ltl2ba_bad_prefix_states[2] = {{
false, true, 
}};

unsigned int
_ltl2ba_sym_to_idx(void)
{{
	unsigned int idx = 0;
	idx |= (({P})) ? 1 : 0;
	return idx;
}}

void
ltl2ba_finish_monitor(void)
{{
	__ESBMC_kill_monitor();

	__ESBMC_assert(!_ltl2ba_bad_prefix_states[_ltl2ba_statevar],"LTL_BAD");

	__ESBMC_assert(!_ltl2ba_stutter_accept_table[_ltl2ba_sym_to_idx()][_ltl2ba_statevar],"LTL_FAILING");

	__ESBMC_assert(!_ltl2ba_good_prefix_excluded_states[_ltl2ba_statevar],"LTL_SUCCEEDING");

	return;
}}
'''


def generate_absence(p_expr: str, externs) -> str:
    return ABSENCE_TEMPLATE.format(
        P=p_expr,
        P_ESC=p_expr.replace('"', '\\"'),
        EXTERNS="\n".join(externs),
    )


def generate(p_expr: str, q_expr: str, externs) -> str:
    stutter = ",\n".join(
        "{\n  %s, %s, \n}" % row for row in STUTTER_ACCEPT) + ","
    return TEMPLATE.format(
        P=p_expr,
        Q=q_expr,
        P_ESC=p_expr.replace('"', '\\"'),
        Q_ESC=q_expr.replace('"', '\\"'),
        EXTERNS="\n".join(externs),
        STUTTER=stutter,
        GOOD_EXCL="%s, %s, " % GOOD_PREFIX_EXCLUDED,
        BAD="%s, %s, " % BAD_PREFIX,
    )


def executable_part(text: str) -> str:
    """The part ESBMC compiles, i.e. everything after the metadata block."""
    idx = text.index("#endif")
    return text[idx:]


def self_test() -> int:
    """Regenerate regression/ltl/basic's monitor and compare behaviour.

    The committed file is ltl2ba's own output for the same pattern, so if our
    template diverges from it in any way that matters, ESBMC's verdict on the
    same program will differ.
    """
    root = Path(__file__).resolve().parent.parent
    ref = root / "regression/ltl/basic/test.ba-2.c"
    prog = root / "regression/ltl/basic/test.c"
    if not ref.exists():
        print(f"self-test: missing reference {ref}", file=sys.stderr)
        return 2

    ours = generate("pressed", "charge > min",
                    ["extern int pressed;", "extern int charge, min;"])

    ref_body = executable_part(ref.read_text())
    our_body = executable_part(ours)

    # Compare after collapsing whitespace: the reference was emitted by a C
    # program and ours by a template, so layout differs where semantics do not.
    def norm(s):
        return " ".join(s.split())

    if norm(ref_body) == norm(our_body):
        print("self-test: byte-equivalent to ltl2ba output (modulo whitespace)")
        return 0

    print("self-test: text differs from the reference; comparing ESBMC verdicts")
    esbmc = Path(root / "build/src/esbmc/esbmc")
    if not esbmc.exists():
        print("self-test: no esbmc binary; cannot compare verdicts",
              file=sys.stderr)
        return 2

    with tempfile.TemporaryDirectory() as td:
        ours_path = Path(td) / "ours.ba.c"
        ours_path.write_text(ours)
        verdicts = []
        for ba in (ref, ours_path):
            out = subprocess.run(
                [str(esbmc), str(prog), "--ltl", str(ba),
                 "-DLTL_PREFIX_BOUND=10"],
                capture_output=True, text=True, timeout=600).stdout
            line = [l for l in out.splitlines()
                    if "Final lowest outcome" in l or "VERIFICATION" in l]
            verdicts.append(tuple(line))
            print(f"  {ba.name}: {line}")
        if verdicts[0] == verdicts[1]:
            print("self-test: verdicts match")
            return 0
        print("self-test: VERDICTS DIFFER", file=sys.stderr)
        return 1



# The absence monitor is validated on *stable* valuations only. A transiently
# true proposition is NOT reliably detected -- see the note in
# docs/cxl-temporal-properties.md; `a && b` held briefly inside a loop is
# reported LTL_SUCCEEDING, and raising --context-bound to 8 does not change
# that. Do not use this pattern to check a property that holds only in a
# window between two assignments.
VIOLATING = """int a = 1, b = 1;
int main(void) { for (int i = 0; i < 3; i++) { a = 1; b = 1; } return 0; }
"""

SATISFYING = """int a = 0, b = 0;
int main(void) { for (int i = 0; i < 3; i++) { a = 0; b = 0; } return 0; }
"""


def _run_ltl(esbmc, prog_src, ba_src, bound=6):
    # NOTE: esbmc is invoked directly. In a container-based setup the binary
    # may not be runnable from the host; pass a wrapper via --esbmc if the
    # outcome comes back as NO_OUTCOME.
    """Run esbmc on a source string with a generated monitor; return the
    'Final lowest outcome' line."""
    with tempfile.TemporaryDirectory() as td:
        d = Path(td)
        (d / "p.c").write_text(prog_src)
        (d / "m.ba.c").write_text(ba_src)
        out = subprocess.run(
            [str(esbmc), "p.c", "--ltl", "m.ba.c",
             f"-DLTL_PREFIX_BOUND={bound}"],
            capture_output=True, text=True, timeout=900, cwd=td)
        # ESBMC writes its progress and the outcome line to stderr, not stdout.
        out = out.stdout + out.stderr
        for line in out.splitlines():
            if line.startswith("Final lowest outcome"):
                return line.split(":", 1)[1].strip()
    return "NO_OUTCOME"


def self_test_absence(esbmc_path=None) -> int:
    """The absence tables are constructed, not transcribed, so check them.

    A program in which p holds stably must reach LTL_BAD; one in which it
    never holds must not. If a monitor cannot reach LTL_BAD it cannot
    distinguish a correct program from a broken one, which is the failure mode
    this pattern exists to avoid.

    This validates the tables, not the monitor's sampling: a *transiently*
    true p is missed regardless (see the note above).
    """
    root = Path(__file__).resolve().parent.parent
    esbmc = Path(esbmc_path) if esbmc_path else root / "build/src/esbmc/esbmc"
    if not esbmc.exists():
        print("self-test-absence: no esbmc binary", file=sys.stderr)
        return 2

    ba = generate_absence("a && b",
                          ["extern int a;", "extern int b;"])

    bad = _run_ltl(esbmc, VIOLATING, ba)
    good = _run_ltl(esbmc, SATISFYING, ba)
    print(f"  violating program (a&&b holds):     {bad}")
    print(f"  satisfying program (never both):    {good}")

    if bad != "LTL_BAD":
        print("self-test-absence: FAILED -- violation not reported as LTL_BAD",
              file=sys.stderr)
        return 1
    if good == "LTL_BAD":
        print("self-test-absence: FAILED -- clean program reported LTL_BAD",
              file=sys.stderr)
        return 1
    print("self-test-absence: the monitor distinguishes the two")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--p", help="C expression for the trigger proposition")
    ap.add_argument("--q", help="C expression for the response proposition")
    ap.add_argument("--extern", action="append", default=[],
                    help="declaration to emit (repeatable)")
    ap.add_argument("-o", "--output", help="output file (default: stdout)")
    ap.add_argument("--self-test", action="store_true",
                    help="validate the response pattern against ltl2ba output")
    ap.add_argument("--absence", action="store_true",
                    help="emit G !p instead of G (p -> F q); uses --p only")
    ap.add_argument("--self-test-absence", action="store_true",
                    help="validate the absence pattern empirically")
    ap.add_argument("--esbmc", help="path to the esbmc binary or a wrapper")
    args = ap.parse_args()

    if args.self_test:
        return self_test()
    if args.self_test_absence:
        return self_test_absence(args.esbmc)

    if args.absence:
        if not args.p:
            ap.error("--p is required")
        text = generate_absence(args.p, args.extern)
        if args.output:
            Path(args.output).write_text(text)
        else:
            sys.stdout.write(text)
        return 0

    if not args.p or not args.q:
        ap.error("--p and --q are required unless --self-test is given")

    text = generate(args.p, args.q, args.extern)
    if args.output:
        Path(args.output).write_text(text)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
