#!/usr/bin/env python3
"""Turn a Linux Runtime Verifier monitor into an ESBMC-checkable specification.

Linux RV (kernel/trace/rv/) specifies monitors as deterministic automata. A
`.dot` model is translated by tools/verification/rvgen into a C header holding
an enum of states, an enum of events, and a transition table

    unsigned char function[state_max][event_max];

with unreachable entries set to INVALID_STATE. The monitor's obligation is
stated in include/rv/da_monitor.h:

    next_state = model_get_next_state(curr_state, event);
    if (next_state == INVALID_STATE) { react(...); return false; }

i.e. `G (state != INVALID_STATE)` -- a safety property, so an assertion
discharges it exactly. No Buchi automaton and no --ltl are involved.

WHAT THIS CHANGES ABOUT THE QUESTION
------------------------------------
RV checks a *running* kernel's event stream against the automaton, so it sees
the interleavings that actually occurred. Feeding the same automaton to ESBMC
asks a different question: can the code under verification emit a rejected
sequence *at all*, over every interleaving and every input. Runtime
verification cannot answer that; bounded model checking can, up to its bound.

So the automaton is the specification and the harness supplies the
implementation. This script emits only the former -- driving it with
unconstrained nondeterministic events would reach INVALID_STATE immediately
and prove nothing, because rejecting bad sequences is what the automaton is
for.

Usage:
  rv2c.py <monitor>.h -o spec.h          # from a kernel RV monitor header
"""

import argparse
import re
import sys
from pathlib import Path


class ParseError(Exception):
    pass


def parse_monitor(text: str, name_hint=None):
    """Accept both rvgen monitor headers and plain dot2c output.

    rvgen emits `#define MONITOR_NAME x` with `enum states_x`; dot2c on its own
    emits bare `enum states`. Both appear in the kernel tree, so handle each.
    """
    m = re.search(r"#define\s+MONITOR_NAME\s+(\w+)", text)
    if m:
        name, suffix = m.group(1), "_" + m.group(1)
    elif re.search(r"enum\s+states\s*\{", text):
        if not name_hint:
            raise ParseError("plain dot2c output needs --name")
        name, suffix = name_hint, ""
    else:
        raise ParseError("neither MONITOR_NAME nor a bare `enum states` found")

    def enum_members(kind):
        mm = re.search(rf"enum\s+{kind}{suffix}\s*\{{(.*?)\}}", text, re.S)
        if not mm:
            raise ParseError(f"no enum {kind}{suffix}")
        out = []
        for item in mm.group(1).split(","):
            item = item.strip()
            if not item or item.startswith("//"):
                continue
            out.append(item)
        # the generated enums end with <kind>_max_<name>
        return [x for x in out if not x.startswith(("state_max", "event_max"))]

    states = enum_members("states")
    events = enum_members("events")

    fm = re.search(r"\.function\s*=\s*\{(.*?)\}\s*,\s*\.initial_state",
                   text, re.S)
    if not fm:
        raise ParseError("no .function table")
    rows = re.findall(r"\{([^{}]*)\}", fm.group(1), re.S)
    table = []
    for row in rows:
        cells = [c.strip() for c in row.split(",") if c.strip()]
        table.append(cells)
    if len(table) != len(states):
        raise ParseError(
            f"table has {len(table)} rows, expected {len(states)}")
    for r in table:
        if len(r) != len(events):
            raise ParseError(
                f"table row has {len(r)} entries, expected {len(events)}")

    im = re.search(r"\.initial_state\s*=\s*(\w+)", text)
    if not im:
        raise ParseError("no .initial_state")
    return name, states, events, table, im.group(1)


def generate(name, states, events, table, initial, source) -> str:
    L = []
    a = L.append
    a(f"/* Generated by scripts/rv2c.py from {source} -- do not edit.")
    a(" *")
    a(f" * Linux RV monitor '{name}', as an ESBMC-checkable specification.")
    a(" * The obligation is the one in include/rv/da_monitor.h: an event that")
    a(" * has no transition from the current state drives the automaton to")
    a(" * INVALID_STATE, and the monitor reacts. Here that is an assertion.")
    a(" *")
    a(" * This file is the SPECIFICATION. Supply an implementation that calls")
    a(f" * rv_{name}_event() and prove it never trips the assertion; driving")
    a(" * it with unconstrained events reaches INVALID_STATE at once and")
    a(" * establishes nothing.")
    a(" */")
    a("#ifndef RV_SPEC_%s_H" % name.upper())
    a("#define RV_SPEC_%s_H" % name.upper())
    a("")
    a("#include <assert.h>")
    a("")
    a("enum rv_%s_state { %s, RV_%s_INVALID };"
      % (name, ", ".join(states), name.upper()))
    a("enum rv_%s_event { %s };" % (name, ", ".join(events)))
    a("")
    a("#define RV_%s_STATES %d" % (name.upper(), len(states)))
    a("#define RV_%s_EVENTS %d" % (name.upper(), len(events)))
    a("")
    a("static const unsigned char rv_%s_function[%d][%d] = {"
      % (name, len(states), len(events)))
    for si, row in enumerate(table):
        cells = []
        for c in row:
            cells.append("RV_%s_INVALID" % name.upper()
                         if c == "INVALID_STATE" else c)
        a("  /* %-28s */ { %s }," % (states[si], ", ".join(cells)))
    a("};")
    a("")
    a("static enum rv_%s_state rv_%s_cur = %s;" % (name, name, initial))
    a("")
    a("static void rv_%s_reset(void) { rv_%s_cur = %s; }"
      % (name, name, initial))
    a("")
    a("/* Feed one event. Trips the RV obligation if the automaton rejects it. */")
    a("static void rv_%s_event(enum rv_%s_event ev)" % (name, name))
    a("{")
    a("  assert(rv_%s_cur < RV_%s_STATES);" % (name, name.upper()))
    a("  assert((unsigned)ev < RV_%s_EVENTS);" % name.upper())
    a("  enum rv_%s_state next =" % name)
    a("    (enum rv_%s_state)rv_%s_function[rv_%s_cur][ev];"
      % (name, name, name))
    a("  /* include/rv/da_monitor.h:690 -- the monitor's whole obligation. */")
    a("  assert(next != RV_%s_INVALID);" % name.upper())
    a("  rv_%s_cur = next;" % name)
    a("}")
    a("")
    a("#endif")
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("header", help="rvgen monitor header, or dot2c output")
    ap.add_argument("--name", help="monitor name (required for dot2c output)")
    ap.add_argument("-o", "--output")
    args = ap.parse_args()

    src = Path(args.header)
    name, states, events, table, initial = parse_monitor(src.read_text(),
                                                        args.name)
    print(f"monitor '{name}': {len(states)} states, {len(events)} events, "
          f"initial={initial}", file=sys.stderr)
    invalid = sum(c == "INVALID_STATE" for r in table for c in r)
    print(f"  {invalid} of {len(states)*len(events)} transitions rejected",
          file=sys.stderr)

    out = generate(name, states, events, table, initial, src.name)
    if args.output:
        Path(args.output).write_text(out)
    else:
        sys.stdout.write(out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
