// Auto-generated harness for: strncpy
// Source: src/c2goto/library/string.c:58
// Generated by Byte Repair Contractor

#include <stddef.h>

extern char *strncpy(char *dst, const char *src, size_t n);

void __byterepair_harness_main(void) {
    // --- Symbolic inputs ---
    char dbuf[8], sbuf[8];
    sbuf[7] = '\0';
    char *dst = dbuf;
    const char *src = (const char *)sbuf;
    size_t n = nondet_uint();
    __ESBMC_assume(n <= 8);

    // --- Call under test ---
    char *result = strncpy(dst, src, n);

    // --- Postcondition assertions ---
    __ESBMC_assert(result == dst, "system property: strncpy returns dst");
}
