// esbmc/esbmc#4715: the implicit union copy constructor's body is generated by
// clang_cpp_adjust::gen_implicit_union_copy_move_constructor, and nothing in the
// suite covered it. Storing that body IREP2-side collapses `*this = *ref` into a
// self-assignment, which this pair makes visible.
#include <cassert>

union U
{
  int i;
  float f;
};

int main()
{
  U a;
  a.i = 7;
  U b = a;
  assert(b.i == 7);
  return 0;
}
