// Auto-generated harness for: isprint
// Source: src/c2goto/library/ctype.c:84
// Generated by Byte Repair Contractor

extern int isprint(int c);

void __byterepair_harness_main(void) {
    // --- Symbolic inputs ---
    int c = nondet_int();

    // --- Precondition assumptions ---
    __ESBMC_assume((c >= -1) && (c <= 255));

    // --- Call under test ---
    int result = isprint(c);

    // --- Postcondition assertions ---
    __ESBMC_assert((result != 0) == (c >= ' ' && c <= '~'), "system property");
    // __ESBMC_assert(/* mirror __ESBMC_ensures conditions */, "description");
}
