# Auto-generated by ESBMC 7.11.0
# Original file: main.py
# Generated: 2025-Dec-29 20:11:26.326342

from main import *
import pytest

@pytest.mark.parametrize("x,y", [
    (-9223372036854775808, -9223372036854759425),
    (-9223372036854775808, 31),
    (1, -9223372036854775793),
    (1, 127),
    (-9223372036854775805, 0),
    (2047, 0),
])
def test_check_range(x,y):
    """Auto-generated test cases for check_range"""
    check_range(x,y)

