// Auto-generated harness for: isupper
// Source: src/c2goto/library/ctype.c:108
// Generated by Byte Repair Contractor

extern int isupper(int c);

void __byterepair_harness_main(void) {
    // --- Symbolic inputs ---
    int c = nondet_int();

    // --- Precondition assumptions ---
    __ESBMC_assume((c >= -1) && (c <= 255));

    // --- Call under test ---
    int result = isupper(c);

    // --- Postcondition assertions ---
    __ESBMC_assert((result != 0) == (c >= 'A' && c <= 'Z'), "system property");
    // __ESBMC_assert(/* mirror __ESBMC_ensures conditions */, "description");
}
