# Auto-generated by ESBMC 8.4.0
# Original file: main.py
# Generated: 2026-Aug-14 17:19:49.820353

from main import *
import pytest

@pytest.mark.parametrize("score", [
    -1,
    100,
    89,
    79,
    69,
    59,
])
def test_grade(score):
    """Auto-generated test cases for grade"""
    grade(score)

