#include <c2goto/cprover_library.h>
#include <util/config/config.h>
#include <util/lang/language.h>
#include <clang-c-frontend/AST/vfs_paths.h>
#include <util/base/filesystem.h>
#include <util/message/message.h>

extern "C"
{
#include <libc.h>
#include <libm.h>
#include <headers/libc_hdr.h>
#undef ESBMC_FLAIL
}

/* The bundled internal libc. The headers generated by the build system contain
 * invocations of the form ESBMC_FLAIL(body, size, name) for each bundled file,
 * see scripts/flail.py --macro. */
static const std::string vfs_prefix = clang_vfs_root() + "/libc";
static const std::string vfs_library = vfs_prefix + "/library";

void register_bundled_libc()
{
  static bool done = false;
  if (done)
    return;
  done = true;

  auto &fs = file_operations::filesystemt::get();
#define ESBMC_FLAIL(body, size, ...)                                           \
  fs.add_bundled(vfs_prefix + "/headers/" #__VA_ARGS__, body, size);
#include <headers/libc_hdr.h>
#undef ESBMC_FLAIL

#define ESBMC_FLAIL(body, size, ...)                                           \
  fs.add_bundled(vfs_library + "/" #__VA_ARGS__, body, size);
#include <libc.h>
#undef ESBMC_FLAIL

#define ESBMC_FLAIL(body, size, ...)                                           \
  fs.add_bundled(vfs_library + "/libm/" #__VA_ARGS__, body, size);
#include <libm.h>
#undef ESBMC_FLAIL
}

const std::string *internal_libc_header_dir()
{
  if (config.ansi_c.lib == configt::ansi_ct::libt::LIB_NONE)
    return nullptr;

  register_bundled_libc();
  // A path inside esbmc_clang_vfs(), never on disk.
  static const std::string dir = vfs_prefix + "/headers";
  return &dir;
}

/* copy of clang_c_convertert::get_filename_from_path(); TODO: unify */
static std::string get_filename_from_path(const std::string &path)
{
  if (path.find_last_of('/') != std::string::npos)
    return path.substr(path.find_last_of('/') + 1);

  return path;
}

void add_bundled_library_sources(contextt &context, const languaget &c_language)
{
  if (!internal_libc_header_dir())
    return;

  bool skip_fenv = false;
#ifdef ESBMC_CHERI_CLANG_MORELLO
  /* Morello is hard-float, which has an incompatible <fenv.h> */
  skip_fenv = config.ansi_c.cheri != configt::ansi_ct::CHERI_OFF;
#endif

  // Parsed straight out of .rodata: clang resolves these through
  // esbmc_clang_vfs(), so no libc source is ever written to disk.
  for (const std::string &path :
       file_operations::filesystemt::get().list(vfs_library))
  {
    if (skip_fenv && get_filename_from_path(path) == "fenv.c")
      continue;

    languaget *l = c_language.new_language();
    log_status("file {}: Parsing", path);
    if (l->parse(path) || l->typecheck(context, path))
    {
      log_error("error processing internal libc source {}", path);
      abort();
    }
    delete l;
  }
}
