# Auto-generated by ESBMC 7.11.0
# Original file: main.py
# Generated: 2025-Dec-29 20:04:10.339273

from main import *
import pytest

@pytest.mark.parametrize("a,b", [
    (0, 0),
    (-9223372036854775808, -9223372036854775808),
])
def test_add_positive(a,b):
    """Auto-generated test cases for add_positive"""
    add_positive(a,b)

