#include <clang-cpp-frontend/esbmc_internal_cpp.h>
#include <util/filesystem.h>
extern "C"
{
#include <abstract_includes/cpp_includes.h>
#undef ESBMC_FLAIL
}

/* Digests of the bundled C++ operational models, emitted next to the arrays by
 * scripts/flail.py, so this key tracks any edit to any of them. */
static std::string cpp_includes_key()
{
  std::string key;
#define ESBMC_FLAIL(body, size, hash, ...) key += hash;
#include <abstract_includes/cpp_includes.h>
#undef ESBMC_FLAIL
  return key;
}

const std::string &esbmct::abstract_cpp_includes()
{
  static const auto dir = file_operations::cached_extract_dir(
    "cpp-headers", cpp_includes_key(), [](const std::string &root) {
#define ESBMC_FLAIL(body, size, hash, ...)                                     \
  file_operations::create_path_and_write(root + "/" #__VA_ARGS__, body, size);
#include <abstract_includes/cpp_includes.h> /* generated by build system */
#undef ESBMC_FLAIL
    });
  return dir.path();
}
