#include <clang-cpp-frontend/esbmc_internal_cpp.h>
#include <clang-c-frontend/AST/vfs_paths.h>
#include <util/base/filesystem.h>
extern "C"
{
#include <abstract_includes/cpp_includes.h>
#undef ESBMC_FLAIL
}

static const std::string vfs_prefix = clang_vfs_root() + "/cpp";

void esbmct::register_bundled_cpp()
{
  static bool done = false;
  if (done)
    return;
  done = true;

#define ESBMC_FLAIL(body, size, ...)                                           \
  file_operations::filesystemt::get().add_bundled(                             \
    vfs_prefix + "/" #__VA_ARGS__, body, size);
#include <abstract_includes/cpp_includes.h> /* generated by build system */
#undef ESBMC_FLAIL
}

const std::string &esbmct::abstract_cpp_includes()
{
  register_bundled_cpp();
  // Inside esbmc_clang_vfs(), never on disk.
  return vfs_prefix;
}
