name: Run a Benchmark
on:
  workflow_dispatch:
    inputs:
      timeout:
        description: 'Timeout for each test case (in seconds)'
        required: true
        default: '300'
      options:
        description: 'Command-line flags to pass via ESBMC_OPTS'
        required: false
        default: '-I /__w/esbmc/esbmc/src/cpp/library'
      benchmark:
        description: 'Benchmark to run (e.g. any benchmark as in regression/<benchmark>)'
        required: true
        default: 'esbmc-cpp/cpp'
      logdirectory:
        description: 'Log directory'
        required: true
        default: 'benchmark_logs'

jobs:
  build-linux:
    name: Build Linux Release
    runs-on: ubuntu-latest
    timeout-minutes: 720 # 12h
    container: rafaelsamenezes/esbmc-ci:clang11
    steps:
      - name: Small test
        run: echo ${{ github.event.inputs.timeout }}
      - name: Checkout code
        uses: actions/checkout@master
      - run: apt update  # Only for Docker jobs
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
      - name: Fix dubious ownership
        run: git config --global --add safe.directory /__w/esbmc/esbmc
      - name: Confirm the benchmark
        run: echo ${{ github.event.inputs.benchmark }}
      - name: Configure CMake
        env:
          TEST_TIMEOUT: ${{ inputs.timeout }}
          BENCHMARK_TO_RUN: ${{ inputs.benchmark }}
          LOG_DIR: ${{ inputs.logdirectory }}
        run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -GNinja -DClang_DIR=/workspace/clang -DLLVM_DIR=/workspace/clang -DBUILD_STATIC=On -DBoolector_DIR=/workspace/boolector-release -DZ3_DIR=/workspace/z3 -DENABLE_YICES=On -DYices_DIR=/workspace/yices -DCVC4_DIR=/workspace/cvc4 -DGMP_DIR=/workspace/gmp -DBitwuzla_DIR=/workspace/bitwuzla-release -DENABLE_REGRESSION=On -DBENCHBRINGUP=On
      - name: Build ESBMC
        run: cd build && cmake --build .
      - uses: actions/upload-artifact@v1
        with:
          name: release-linux
          path: ./build/src/esbmc/esbmc
      - name: Run user-specified benchmark
        continue-on-error: true
        env:
          ESBMC_OPTS: ${{ inputs.options }}
          LOG_DIR: ${{ inputs.logdirectory }}
        run: cd build/ && ctest -j4 --output-on-failure --progress .
      - uses: actions/upload-artifact@v2
        with:
          name: benchmark-logs
          path: ./build/regression/${{ inputs.logdirectory }}
