on:
  workflow_call:
    inputs:
      operating-system:
        description: "Targeted OS (e.g. ubuntu-24.04, windows-latest)"
        required: true
        type: string
      build-flags:
        description: "Flags to be passed to build.sh script"
        required: true
        type: string
      testing:
        description: "Whether to run tests (regression) for this build"
        required: true
        type: boolean

jobs:
  build:
    name: Build ESBMC (${{ inputs.operating-system }})
    runs-on: ${{ inputs.operating-system == 'ubuntu-24.04' && fromJSON('["self-hosted", "development"]') || inputs.operating-system }}
    steps:
      - uses: actions/checkout@v4

      - uses: hendrikmuhs/ccache-action@v1.2
        if: ${{ startsWith(inputs.operating-system, 'ubuntu-') }}
        with:
          restore: ${{ github.event_name == 'push' }}
          save: ${{ github.event_name == 'push' }}
          key: ${{ inputs.operating-system }}-${{ hashFiles('**/*.cpp','**/*.h') }}
          restore-keys: |
            ${{ inputs.operating-system }}
          evict-old-files: 2d

      - name: Build ESBMC
        run: ./scripts/build.sh ${{ inputs.build-flags }}
        env:
          CMAKE_BUILD_PARALLEL_LEVEL: ${{ runner.os == 'Linux' && '16' || '4' }}
          PIP_BREAK_SYSTEM_PACKAGES: "1"

      - uses: actions/upload-artifact@v4
        with:
          name: release-${{ inputs.operating-system }}-${{ inputs.build-flags }}
          path: ./release

      - name: Check Python regression tests
        if: ${{ inputs.testing == true }}
        run: |
          export PATH="$(brew --prefix python@3.12)/bin:$HOME/Library/Python/3.12/bin:$PATH"
          chmod +x scripts/check_python_tests.sh
          ./scripts/check_python_tests.sh

      - name: Run tests
        if: ${{ inputs.testing == true }}
        run: |
          export PATH="$(brew --prefix python@3.12)/bin:$HOME/Library/Python/3.12/bin:$PATH"
          cd build/
          cmake -DESBMC_REGRESS_TIMEOUT=120 .
          if [[ "${{ inputs.operating-system }}" =~ ^macos ]]; then
            ctest -j$(nproc) --output-on-failure --progress -L python
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            ctest -j$(nproc) --output-on-failure --progress -LE python-intensive .
          else
            ctest -j10 --output-on-failure --progress .
          fi
