name: Run clang sanitizers

on: [push, pull_request]
jobs:

  asan:
    name: Compile esbmc with ASAN
    runs-on: ubuntu-latest
    container: rafaelsamenezes/esbmc-ci:clang11
    steps:
    - uses: actions/checkout@v2
    - run: apt update  # Only for Docker jobs
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
    - name: Fix dubious ownership
      run: git config --global --add safe.directory /__w/esbmc/esbmc
    - name: Configure CMake
      run: mkdir build && cd build && CC=/workspace/clang/bin/clang CXX=/workspace/clang/bin/clang++ cmake .. -GNinja  -DCMAKE_BUILD_TYPE=Sanitizer -DSANITIZER_TYPE=ASAN -DClang_DIR=/workspace/clang -DLLVM_DIR=/workspace/clang -DENABLE_JIMPLE_FRONTEND=On -DENABLE_SOLIDITY_FRONTEND=On
    - name: Build ESBMC
      run: cd build && ninja
